<?php
include_once __DIR__.'/includes/session_check.php'; require_login_modal(); include __DIR__.'/db_connect.php';
if(empty($_SESSION['csrf_token'])) $_SESSION['csrf_token']=bin2hex(random_bytes(32));
$csrf=$_SESSION['csrf_token']; $schoolId=(int)($_SESSION['login_school_id']??0); $years=[];
$q=$conn->query("SELECT id,year,is_active FROM academic_year WHERE school_id=$schoolId ORDER BY year DESC");
while($q&&($r=$q->fetch_assoc()))$years[]=$r; $selected=(int)($_GET['academic_year_id']??0);
if(!$selected)foreach($years as $y)if($y['is_active']){$selected=(int)$y['id'];break;} if(!$selected&&$years)$selected=(int)$years[0]['id'];
?>
<style>
.am{padding:8px 4px}.am-head,.am-panel-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.am-head{margin-bottom:14px}.am-heading{display:flex;align-items:center;gap:12px}.am-icon{width:46px;height:46px;border-radius:12px;background:#eaf2ff;color:#2f6fed;display:flex;align-items:center;justify-content:center;font-size:20px}.am-heading h5{margin:0;font-weight:700;color:#233b52}.am-heading small,.am-meta{color:#6c757d}.am-toolbar,.am-stats{display:grid;gap:12px}.am-toolbar{grid-template-columns:1.2fr repeat(3,1fr) 1.5fr auto;background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:14px;margin-bottom:14px}.am-field label{display:block;font-size:.78rem;font-weight:700;color:#526274;margin-bottom:5px}.am-field .form-control{height:38px;border-radius:8px}.am-stats{grid-template-columns:repeat(5,1fr);margin-bottom:14px}.am-stat{background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:13px;display:flex;gap:11px;align-items:center}.am-stat i{width:38px;height:38px;border-radius:10px;background:#edf3ff;color:#2f6fed;display:flex;align-items:center;justify-content:center}.am-stat strong{display:block;font-size:1.22rem;color:#233b52}.am-stat span{font-size:.76rem;color:#6c757d}.am-panel{background:#fff;border:1px solid #e3e8f0;border-radius:12px;overflow:hidden}.am-panel-head{padding:12px 14px;border-bottom:1px solid #e9edf4}.am-body{padding:14px}.am-group{border:1px solid #e1e7f0;border-radius:10px;margin-bottom:12px;overflow:hidden}.am-group-title{padding:11px 14px;background:#f7f9fc;font-weight:700;color:#29445d;display:flex;justify-content:space-between}.am-area{padding:12px 14px;border-top:1px solid #edf0f5}.am-area-title{font-weight:600;margin-bottom:8px}.am-course-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.am-course{border:1px solid #e8ecf2;border-left:4px solid var(--color,#6c757d);border-radius:7px;padding:9px 11px;display:flex;justify-content:space-between;align-items:center;gap:8px}.am-course.inactive{opacity:.58}.am-meta{font-size:.75rem}.am-empty{text-align:center;padding:45px 15px;color:#7a8794}.am-bulk{display:none;background:#f3f7ff;border:1px solid #dce7ff;border-radius:9px;padding:10px;margin-bottom:12px;align-items:center;gap:8px;flex-wrap:wrap}.am-bulk.show{display:flex}.am-check{width:17px;height:17px}.am-view.active{background:#2f6fed;color:#fff}.table td,.table th{vertical-align:middle!important}@media(max-width:1100px){.am-toolbar{grid-template-columns:repeat(3,1fr)}.am-stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.am-head,.am-panel-head{align-items:flex-start;flex-direction:column}.am-toolbar,.am-stats{grid-template-columns:1fr 1fr}.am-course-list{grid-template-columns:1fr}}
</style>
<div class="container-fluid am">
 <div class="am-head"><div class="am-heading"><div class="am-icon"><i class="fa fa-sitemap"></i></div><div><h5>Gestión Académica</h5><small>Estructura curricular por año, nivel, grado y área</small></div></div><div class="btn-group"><button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><i class="fa fa-plus mr-1"></i>Agregar</button><div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#" id="new-area"><i class="fa fa-layer-group text-primary mr-2"></i>Nueva área</a><a class="dropdown-item" href="#" id="new-course"><i class="fa fa-book text-success mr-2"></i>Nuevo curso</a><div class="dropdown-divider"></div><a class="dropdown-item" href="#" id="copy-year"><i class="fa fa-copy text-info mr-2"></i>Copiar estructura</a><a class="dropdown-item" href="#" id="export-am"><i class="fa fa-file-excel text-success mr-2"></i>Exportar vista</a><a class="dropdown-item" href="#" id="show-audit"><i class="fa fa-history text-secondary mr-2"></i>Registro de auditoría</a></div></div></div>
 <div id="migration" class="alert alert-warning d-none"><strong>Migración pendiente:</strong> ejecuta <code>sql/academic_management_upgrade.sql</code>.</div>
 <div class="am-toolbar">
  <div class="am-field"><label>Año académico</label><select id="year" class="form-control"><?php foreach($years as $y):?><option value="<?=$y['id']?>" <?=$selected==(int)$y['id']?'selected':''?>><?=htmlspecialchars($y['year'])?><?=$y['is_active']?' (Activo)':''?></option><?php endforeach?></select></div>
  <div class="am-field"><label>Nivel</label><select id="level" class="form-control"><option value="">Todos</option><option>Inicial</option><option>Primaria</option><option>Secundaria</option></select></div>
  <div class="am-field"><label>Grado</label><select id="grade" class="form-control"><option value="">Todos</option></select></div>
  <div class="am-field"><label>Estado</label><select id="status" class="form-control"><option value="all">Todos</option><option value="active">Activos</option><option value="suspended">Suspendidos</option><option value="inactive">Inactivos</option></select></div>
  <div class="am-field"><label>Buscar</label><input id="search" class="form-control" placeholder="Área, curso o código"></div>
  <div class="am-field"><label>Vista</label><div class="btn-group"><button class="btn btn-outline-primary am-view active" data-view="group"><i class="fa fa-th-large"></i></button><button class="btn btn-outline-primary am-view" data-view="table"><i class="fa fa-list"></i></button></div></div>
 </div>
 <div class="am-stats"><div class="am-stat"><i class="fa fa-layer-group"></i><div><strong id="s-areas">0</strong><span>Áreas visibles</span></div></div><div class="am-stat"><i class="fa fa-book"></i><div><strong id="s-courses">0</strong><span>Cursos visibles</span></div></div><div class="am-stat"><i class="fa fa-check-circle"></i><div><strong id="s-active">0</strong><span>Cursos activos</span></div></div><div class="am-stat"><i class="fa fa-exclamation-circle"></i><div><strong id="s-no-area">0</strong><span>Sin área</span></div></div><div class="am-stat"><i class="fa fa-tasks"></i><div><strong id="s-no-comp">0</strong><span>Sin competencias</span></div></div></div>
 <div class="am-panel"><div class="am-panel-head"><strong><i class="fa fa-project-diagram text-primary mr-2"></i>Estructura curricular</strong><div><button id="reset" class="btn btn-sm btn-outline-secondary"><i class="fa fa-undo mr-1"></i>Restablecer</button> <button id="refresh" class="btn btn-sm btn-outline-primary"><i class="fa fa-sync-alt mr-1"></i>Actualizar</button></div></div><div class="am-body"><div class="am-bulk" id="bulk"><strong><span id="selected-count">0</span> seleccionados</strong><select id="bulk-action" class="form-control form-control-sm" style="max-width:210px"><option value="">Acción masiva</option><option value="activate">Activar</option><option value="suspend">Suspender temporalmente</option><option value="deactivate">Desactivar</option><option value="assign_area">Asignar a un área</option></select><select id="bulk-area" class="form-control form-control-sm d-none" style="max-width:210px"></select><button id="apply-bulk" class="btn btn-sm btn-primary">Aplicar</button><button id="clear" class="btn btn-sm btn-link">Cancelar</button></div><div id="am-loading" class="text-center py-5"><i class="fa fa-spinner fa-spin fa-2x text-primary"></i></div><div id="am-results"></div></div></div>
</div>
<div class="modal fade" id="copyModal"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Copiar estructura académica</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="alert alert-info">Se copiarán áreas y cursos; los duplicados serán omitidos.</div><div class="form-group"><label>Origen</label><select id="source" class="form-control"><?php foreach($years as $y):?><option value="<?=$y['id']?>"><?=htmlspecialchars($y['year'])?></option><?php endforeach?></select></div><div class="form-group"><label>Destino</label><select id="target" class="form-control"><?php foreach($years as $y):?><option value="<?=$y['id']?>" <?=$selected==(int)$y['id']?'selected':''?>><?=htmlspecialchars($y['year'])?></option><?php endforeach?></select></div></div><div class="modal-footer"><button class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button id="confirm-copy" class="btn btn-info">Copiar</button></div></div></div></div>
<div class="modal fade" id="auditModal"><div class="modal-dialog modal-xl"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fa fa-history mr-2"></i>Auditoría académica</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Fecha</th><th>Usuario</th><th>Entidad</th><th>Acción</th><th>Detalle</th></tr></thead><tbody id="audit-body"></tbody></table></div></div></div></div></div>
<script>
(function($){var api='academic_management_api.php',csrf=<?=json_encode($csrf)?>,rows=[],areas=[],selected={},view='group',timer;
function e(v){return $('<div>').text(v==null?'':v).html()} function gradeOptions(){var m={Inicial:['3 años','4 años','5 años'],Primaria:['1°','2°','3°','4°','5°','6°'],Secundaria:['1°','2°','3°','4°','5°']},a=m[$('#level').val()]||[];$('#grade').html('<option value="">Todos</option>'+a.map(x=>'<option>'+x+'</option>').join(''))}
function loadAreas(){return $.getJSON(api,{action:'areas',academic_year_id:$('#year').val()}).done(r=>{areas=r.areas||[];$('#bulk-area').html('<option value="">Selecciona un área</option>'+areas.filter(a=>+a.is_active).map(a=>'<option value="'+a.id+'">'+e(a.name)+'</option>').join(''))})}
function load(){$('#am-loading').show();$('#am-results').empty();$.getJSON(api,{action:'list',academic_year_id:$('#year').val(),level:$('#level').val(),grade:$('#grade').val(),status:$('#status').val(),search:$('#search').val()}).done(r=>{rows=r.courses||[];let s=r.stats||{};$('#s-areas').text(s.areas||0);$('#s-courses').text(s.courses||0);$('#s-active').text(s.active||0);$('#s-no-area').text(s.without_area||0);$('#s-no-comp').text(s.without_competencies||0);render()}).fail(x=>{let r=x.responseJSON||{};if(r.migration_required)$('#migration').removeClass('d-none');$('#am-results').html('<div class="am-empty">'+e(r.message||'No se pudo cargar la estructura.')+'</div>')}).always(()=>$('#am-loading').hide())}
function check(c){return '<input class="am-check row-check" type="checkbox" value="'+c.id+'" '+(selected[c.id]?'checked':'')+'>'} function actions(c){return '<div class="btn-group"><button class="btn btn-sm btn-outline-primary edit" data-id="'+c.id+'" title="Editar"><i class="fa fa-edit"></i></button><button class="btn btn-sm btn-outline-info comp" data-id="'+c.id+'" data-level="'+e(c.level)+'" title="Revisar asignaciones y competencias"><i class="fa fa-tasks"></i></button></div>'}
function render(){if(!rows.length){$('#am-results').html('<div class="am-empty"><i class="fa fa-folder-open fa-3x mb-2"></i><h6>No hay cursos con estos filtros</h6></div>');return}view==='table'?table():groups();bulk()}
function table(){let h='<div class="table-responsive"><table class="table table-hover table-bordered"><thead><tr><th><input id="all" type="checkbox"></th><th>Código</th><th>Curso</th><th>Área</th><th>Nivel</th><th>Grados</th><th>Horas</th><th>Competencias</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>';rows.forEach(c=>{let st=c.course_status||(+c.is_active?'Activo':'Inactivo'),badge=st==='Activo'?'success':(st==='Suspendido'?'warning':'secondary');h+='<tr><td>'+check(c)+'</td><td>'+e(c.course_code||'—')+'</td><td><strong>'+e(c.name)+'</strong><div class="am-meta">'+e(c.course_type)+'</div></td><td>'+e(c.area_name||'Sin área')+'</td><td>'+e(c.level)+'</td><td>'+e(c.grades||'Todos')+'</td><td>'+e(c.weekly_hours)+'</td><td><span class="badge badge-'+(+c.competency_count?'info':'warning')+'">'+c.competency_count+'</span></td><td><span class="badge badge-'+badge+'">'+e(st)+'</span></td><td>'+actions(c)+'</td></tr>'});$('#am-results').html(h+'</tbody></table></div>')}
function groups(){let g={};rows.forEach(c=>{let l=c.level||'Sin nivel',a=c.area_name||'Sin área';g[l]=g[l]||{};g[l][a]=g[l][a]||[];g[l][a].push(c)});let h='';Object.keys(g).forEach(l=>{let n=Object.values(g[l]).reduce((x,a)=>x+a.length,0);h+='<div class="card shadow-sm mb-3"><div class="card-header bg-light d-flex justify-content-between align-items-center py-3"><strong class="text-dark"><i class="fa fa-graduation-cap text-primary mr-2"></i>'+e(l)+'</strong><span class="badge badge-primary px-3 py-2">'+n+' cursos</span></div><div class="card-body p-3">';Object.keys(g[l]).forEach(a=>{let list=g[l][a],color=list[0].area_color||'#6c757d';h+='<div class="mb-4"><div class="d-flex align-items-center mb-2"><span style="width:12px;height:12px;border-radius:50%;background:'+e(color)+';display:inline-block;margin-right:8px"></span><strong class="text-secondary">'+e(a)+'</strong></div><div class="row">';list.forEach(c=>{let st=c.course_status||(+c.is_active?'Activo':'Inactivo'),badge=st==='Activo'?'success':(st==='Suspendido'?'warning':'secondary');h+='<div class="col-xl-6 col-lg-6 col-md-12 mb-2"><div class="card h-100 '+(st==='Activo'?'':'bg-light')+'" style="border-left:4px solid '+e(color)+'"><div class="card-body p-3 d-flex justify-content-between align-items-center"><div class="d-flex align-items-start mr-2">'+check(c)+'<div class="ml-3"><strong class="text-dark">'+e(c.name)+'</strong> <span class="badge badge-'+badge+' ml-1">'+e(st)+'</span><div class="small text-muted mt-1">'+e(c.grades||'Todos los grados')+' &middot; '+e(c.weekly_hours)+' h &middot; '+c.competency_count+' competencias</div></div></div>'+actions(c)+'</div></div></div>'});h+='</div></div>'});h+='</div></div>'});$('#am-results').html(h)}
function bulk(){let n=Object.keys(selected).length;$('#selected-count').text(n);$('#bulk').toggleClass('show',n>0)} function refresh(){selected={};bulk();$.when(loadAreas()).always(load)}
$(document).on('change','.row-check',function(){this.checked?selected[this.value]=1:delete selected[this.value];bulk()});$(document).on('change','#all',function(){rows.forEach(c=>this.checked?selected[c.id]=1:delete selected[c.id]);render()});$('.am-view').click(function(){view=$(this).data('view');$('.am-view').removeClass('active');$(this).addClass('active');render()});
$('#level').change(function(){gradeOptions();load()});$('#year').change(refresh);$('#grade,#status').change(load);$('#search').on('input',function(){clearTimeout(timer);timer=setTimeout(load,300)});$('#reset').click(function(){$('#level,#grade').val('');$('#status').val('all');$('#search').val('');gradeOptions();load()});$('#refresh').click(refresh);$('#clear').click(function(){selected={};render()});$('#bulk-action').change(function(){$('#bulk-area').toggleClass('d-none',this.value!=='assign_area')});
function executeBulk(op){start_load();$.post(api+'?action=bulk',{csrf_token:csrf,ids:JSON.stringify(Object.keys(selected)),operation:op,area_id:$('#bulk-area').val(),academic_year_id:$('#year').val()},null,'json').done(r=>{alert_toast(r.message,r.status==1?'success':'danger');if(r.status==1)refresh()}).fail(x=>alert_toast((x.responseJSON||{}).message||'Error','danger')).always(end_load)}
$('#apply-bulk').click(function(){let op=$('#bulk-action').val(),ids=Object.keys(selected);if(!op)return alert_toast('Selecciona una acción.','warning');if(op==='assign_area'&&!$('#bulk-area').val())return alert_toast('Selecciona un área.','warning');if(op==='activate'||op==='assign_area'){if(confirm('¿Aplicar la acción a '+ids.length+' cursos?'))executeBulk(op);return}start_load();$.post(api+'?action=impact',{ids:JSON.stringify(ids),academic_year_id:$('#year').val()},null,'json').done(function(r){let i=r.impact||{},label=op==='suspend'?'suspender':'desactivar',msg='Antes de '+label+':\n\nDocentes relacionados: '+(i.teachers||0)+'\nAsignaciones: '+(i.assignments||0)+'\nCompetencias: '+(i.competencies||0)+'\nEvaluaciones: '+(i.evaluations||0)+'\nNotas registradas: '+(i.grades||0)+'\n\nTodo el historial se conservará. ¿Deseas continuar?';if(confirm(msg))executeBulk(op)}).fail(x=>alert_toast((x.responseJSON||{}).message||'No se pudo calcular el impacto.','danger')).always(end_load)});
$('#new-area').click(function(x){x.preventDefault();uni_modal('Nueva Área','manage_area.php?academic_year_id='+$('#year').val(),'mid-large')});$('#new-course').click(function(x){x.preventDefault();uni_modal('Nuevo Curso','manage_academic_course.php?academic_year_id='+$('#year').val(),'mid-large')});$(document).on('click','.edit',function(){uni_modal('Editar Curso','manage_academic_course.php?id='+$(this).data('id'),'mid-large')});$(document).on('click','.comp',function(){uni_modal('Competencias del curso','manage_course_competencies_admin.php?course_id='+$(this).data('id')+'&academic_year_id='+$('#year').val(),'modal-xl')});
$('#copy-year').click(function(x){x.preventDefault();$('#target').val($('#year').val());$('#copyModal').modal('show')});$('#confirm-copy').click(function(){let s=$('#source').val(),t=$('#target').val();if(s===t)return alert_toast('Origen y destino deben ser diferentes.','warning');start_load();$.post(api+'?action=copy_year',{csrf_token:csrf,source_year_id:s,target_year_id:t},null,'json').done(r=>{alert_toast(r.message,r.status==1?'success':'danger');if(r.status==1){$('#copyModal').modal('hide');$('#year').val(t);refresh()}}).fail(x=>alert_toast((x.responseJSON||{}).message||'Error','danger')).always(end_load)});$('#export-am').click(function(x){x.preventDefault();location='export_academic_management.php?'+$.param({academic_year_id:$('#year').val(),level:$('#level').val(),grade:$('#grade').val(),status:$('#status').val(),search:$('#search').val()})});$('#show-audit').click(function(x){x.preventDefault();$('#audit-body').html('<tr><td colspan="5" class="text-center"><i class="fa fa-spinner fa-spin"></i></td></tr>');$('#auditModal').modal('show');$.getJSON(api,{action:'audit',academic_year_id:$('#year').val()}).done(function(r){let h='';(r.logs||[]).forEach(function(l){h+='<tr><td>'+e(l.created_at)+'</td><td>'+e(l.user_name)+'</td><td>'+e(l.entity_type)+' #'+e(l.entity_id||'')+'</td><td>'+e(l.action)+'</td><td><small>'+e(l.details||'')+'</small></td></tr>'});$('#audit-body').html(h||'<tr><td colspan="5" class="text-center text-muted">Sin movimientos registrados.</td></tr>')})});$(document).on('academic:changed',refresh);window.updateMainTablesSafely=refresh;gradeOptions();$.getJSON(api,{action:'bootstrap'}).done(r=>{if(!r.upgraded)$('#migration').removeClass('d-none')});refresh();
})(jQuery);
</script>
