<?php
include 'db_connect.php';
if (empty($_SESSION['login_id']) || (int)($_SESSION['login_type'] ?? 0) !== 1) { header('location: login.php'); exit; }
$school_id = (int)($_SESSION['login_school_id'] ?? 0);
if (empty($_SESSION['csrf_token'])) $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
$csrf = $_SESSION['csrf_token'];

function ayp_col($db,$name){$v=$db->real_escape_string($name);$q=$db->query("SHOW COLUMNS FROM academic_year LIKE '$v'");return $q&&$q->num_rows;}
$migration_ready=true;
foreach(['status','period_type','closed_at','closed_by','close_notes','reopened_at','reopened_by','reopen_reason'] as $column){if(!ayp_col($conn,$column)){$migration_ready=false;break;}}
foreach(['academic_periods','academic_year_audit','bimester_locks'] as $table){$safe=$conn->real_escape_string($table);$q=$conn->query("SHOW TABLES LIKE '$safe'");if(!$q||!$q->num_rows){$migration_ready=false;break;}}
if($migration_ready){$q=$conn->query("SHOW COLUMNS FROM academic_periods LIKE 'start_date'");$start=$q?$q->fetch_assoc():null;$q=$conn->query("SHOW COLUMNS FROM academic_periods LIKE 'end_date'");$end=$q?$q->fetch_assoc():null;if(!$start||!$end||strtoupper($start['Null']??'NO')!=='YES'||strtoupper($end['Null']??'NO')!=='YES')$migration_ready=false;}
if(!$migration_ready): ?>
<div class="container-fluid"><div class="alert alert-warning shadow-sm"><h5><i class="fa fa-database mr-2"></i>Actualización de base de datos pendiente</h5><p class="mb-2">El módulo no modificará automáticamente la estructura de la base de datos.</p><p class="mb-0">Ejecute manualmente <code>sql/academic_year_lifecycle_upgrade.sql</code> y vuelva a cargar esta página.</p></div></div>
<?php return; endif;

$years=[];$s=$conn->prepare("SELECT * FROM academic_year WHERE school_id=? ORDER BY FIELD(status,'Activo','Borrador','Cerrado','Archivado'),start_date DESC");$s->bind_param('i',$school_id);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$years[]=$x;$s->close();
$active=null;foreach($years as $y){if((int)$y['is_active']===1){$active=$y;break;}}
$manage = !empty($_GET['manage']);
$selectedId = (int)($_GET['id'] ?? 0);
$selected = null;
if($manage && $selectedId>0){foreach($years as $y){if((int)$y['id']===$selectedId){$selected=$y;break;}}}
if($manage && !$selected){echo '<div class="container-fluid"><div class="alert alert-warning">El año académico solicitado no existe o no pertenece a este colegio.</div><a class="btn btn-light border" href="index.php?page=academic_year">Volver</a></div>';return;}
function ay_badge($status){return ['Activo'=>'success','Borrador'=>'warning','Cerrado'=>'secondary','Archivado'=>'dark'][$status]??'secondary';}
function ay_date($v){return $v?date('d/m/Y',strtotime($v)):'—';}
?>
<style>
.ay-shell{max-width:1500px;margin:auto;padding-top:8px}.ay-hero{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px;padding:0 4px}.ay-heading{display:flex;align-items:center;gap:12px}.ay-hero-icon{width:46px;height:46px;border-radius:12px;background:#eaf2ff;color:#2f6fed;display:flex;align-items:center;justify-content:center;font-size:20px;flex:0 0 46px}.ay-hero h5{margin:0;font-weight:700;color:#233b52}.ay-hero small{display:block;color:#6c757d;margin-top:2px}.ay-actions .btn{margin:2px}.ay-year-link{font-weight:700;color:#2e59d9}.ay-stat{background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:16px;height:100%}.ay-stat strong{font-size:1.35rem;color:#172b4d}.ay-manage-head{background:#fff;border:1px solid #e3e8f0;border-radius:14px;padding:18px 20px}.ay-manage-tabs{background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:6px;display:flex;gap:5px;flex-wrap:wrap}.ay-manage-tabs .nav-link{border-radius:9px;color:#5a5c69;font-weight:700;padding:.6rem .9rem}.ay-manage-tabs .nav-link.active{background:#4e73df;color:#fff}.ay-section{background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:18px}.ay-period-row{display:grid;grid-template-columns:50px 1fr 150px 150px 115px 40px;gap:8px;align-items:center;margin-bottom:8px}.ay-close-card{border:1px solid #e3e8f0;border-radius:12px;background:#fff;padding:14px;height:100%}.ay-close-card.locked{border-left:4px solid #36b9cc}.ay-close-card.open{border-left:4px solid #f6c23e}.ay-close-progress{height:7px}.ay-close-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:10px 0}.ay-close-kpi{background:#f8f9fc;border:1px solid #edf0f5;border-radius:8px;padding:7px 9px}.ay-close-kpi small{display:block;color:#858796;font-size:.68rem}.ay-close-kpi strong{font-size:1rem;color:#334155}.ay-close-actions{display:flex;gap:6px;flex-wrap:wrap}.ay-state-badge{font-size:.7rem}.ay-audit-list{max-height:520px;overflow:auto}.ay-audit-item{border-left:3px solid #dfe6f3}.ay-lock-reason{display:none}.ay-control-note{border-left:4px solid #4e73df}.compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:768px){.ay-hero{align-items:flex-start;flex-direction:column}.ay-manage-head>.d-flex{align-items:flex-start!important;flex-direction:column}.ay-period-row{grid-template-columns:40px 1fr 1fr}.ay-period-row .period-name{grid-column:2/4}.ay-close-kpis{grid-template-columns:1fr 1fr}.compare-grid{grid-template-columns:1fr}}
</style>
<div class="container-fluid ay-shell">
<?php if(!$manage): ?>
 <div class="ay-hero"><div class="ay-heading"><div class="ay-hero-icon"><i class="fa fa-calendar-alt"></i></div><div><h5>Años académicos</h5><small>Consulta el historial y entra a la configuración de cada año escolar.</small></div></div><div><button class="btn btn-outline-info mr-1" id="open-compare"><i class="fa fa-balance-scale mr-1"></i>Comparar</button><button class="btn btn-primary" id="new-year"><i class="fa fa-plus mr-1"></i>Nuevo año</button></div></div>
 <?php if($active): ?><div class="alert alert-light border mb-3"><i class="fas fa-circle text-success mr-2"></i>Año operativo actual: <strong><?php echo htmlspecialchars($active['year']); ?></strong>. Toda la configuración avanzada se administra desde <strong>Gestionar</strong>.</div><?php else: ?><div class="alert alert-warning"><i class="fa fa-exclamation-triangle mr-1"></i>No hay un año académico activo.</div><?php endif; ?>
 <div class="card shadow-sm mb-4"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Historial de años académicos</strong><span class="badge badge-light border"><?php echo count($years); ?> registro(s)</span></div><div class="card-body table-responsive"><table class="table table-hover" id="years-table"><thead class="thead-light"><tr><th>Año</th><th>Fechas</th><th>Organización</th><th>Estado</th><th class="text-right">Acción</th></tr></thead><tbody>
 <?php foreach($years as $y): $status=$y['status']?:((int)$y['is_active']?'Activo':'Borrador'); ?>
 <tr><td><a class="ay-year-link" href="index.php?page=academic_year&manage=1&id=<?php echo (int)$y['id']; ?>"><?php echo htmlspecialchars($y['year']); ?></a><div class="small text-muted"><?php echo htmlspecialchars($y['description']?:'Sin descripción'); ?></div></td><td><?php echo ay_date($y['start_date']); ?> — <?php echo ay_date($y['end_date']); ?></td><td><?php echo htmlspecialchars($y['period_type']); ?></td><td><span class="badge badge-<?php echo ay_badge($status); ?>"><?php echo htmlspecialchars($status); ?></span></td><td class="text-right"><a class="btn btn-sm btn-outline-primary" href="index.php?page=academic_year&manage=1&id=<?php echo (int)$y['id']; ?>"><i class="fas fa-cog mr-1"></i>Gestionar</a></td></tr>
 <?php endforeach; ?>
 </tbody></table></div></div>
<?php else: $status=$selected['status']?:((int)$selected['is_active']?'Activo':'Borrador'); ?>
 <div class="mb-3"><a href="index.php?page=academic_year" class="btn btn-sm btn-light border"><i class="fas fa-arrow-left mr-1"></i>Volver a años académicos</a></div>
 <div class="ay-manage-head mb-3"><div class="d-flex justify-content-between align-items-center"><div><div class="small text-muted text-uppercase font-weight-bold">Gestión del año académico</div><h3 class="mb-1 text-gray-800"><?php echo htmlspecialchars($selected['year']); ?> <span class="badge badge-<?php echo ay_badge($status); ?> align-middle" style="font-size:.75rem"><?php echo htmlspecialchars($status); ?></span></h3><div class="text-muted"><?php echo htmlspecialchars($selected['description']?:'Sin descripción'); ?></div></div><div class="text-md-right mt-3 mt-md-0"><div class="small text-muted">Periodo general</div><strong><?php echo ay_date($selected['start_date']); ?> — <?php echo ay_date($selected['end_date']); ?></strong><div class="small text-muted"><?php echo htmlspecialchars($selected['period_type']); ?></div></div></div></div>
 <ul class="nav ay-manage-tabs mb-3" id="ay-tabs"><li class="nav-item"><a class="nav-link active" data-toggle="pill" href="#ay-resumen"><i class="fas fa-chart-pie mr-1"></i>Resumen</a></li><li class="nav-item"><a class="nav-link" data-toggle="pill" href="#ay-periodos"><i class="fas fa-calendar-check mr-1"></i>Periodos</a></li><li class="nav-item"><a class="nav-link" data-toggle="pill" href="#ay-cierre-notas"><i class="fas fa-user-check mr-1"></i>Cierre de notas</a></li><li class="nav-item"><a class="nav-link" data-toggle="pill" href="#ay-auditoria"><i class="fas fa-history mr-1"></i>Auditoría</a></li></ul>
 <div class="tab-content">
  <div class="tab-pane fade show active" id="ay-resumen"><div class="ay-section"><div class="d-flex justify-content-between align-items-center flex-wrap mb-3"><div><h5 class="mb-1">Resumen del año <?php echo htmlspecialchars($selected['year']); ?></h5><small class="text-muted">Información general y acciones de ciclo de vida.</small></div><div class="mt-2 mt-md-0 ay-actions">
   <?php if(!in_array($status,['Cerrado','Archivado'],true)): ?><button class="btn btn-sm btn-outline-primary" id="edit-selected-year"><i class="fas fa-edit mr-1"></i>Editar datos</button><?php endif; ?>
   <?php if($status==='Borrador'): ?><button class="btn btn-sm btn-outline-info" id="copy-selected-year"><i class="fas fa-copy mr-1"></i>Copiar configuración</button><button class="btn btn-sm btn-success" id="activate-selected-year"><i class="fas fa-play mr-1"></i>Activar año</button><button class="btn btn-sm btn-outline-danger" id="delete-selected-year"><i class="fas fa-trash mr-1"></i>Eliminar</button><?php endif; ?>
   <?php if($status==='Activo'): ?><button class="btn btn-sm btn-danger" id="close-selected-year"><i class="fas fa-lock mr-1"></i>Cerrar año</button><?php endif; ?>
   <?php if($status==='Cerrado'): ?><button class="btn btn-sm btn-warning" id="reopen-selected-year"><i class="fas fa-unlock mr-1"></i>Reabrir</button><button class="btn btn-sm btn-outline-dark" id="archive-selected-year"><i class="fas fa-archive mr-1"></i>Archivar</button><?php endif; ?>
  </div></div><div class="row" id="ay-summary-cards"><div class="col-12 text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Cargando resumen...</div></div><div class="alert alert-light border mt-3 mb-0"><strong>Organización:</strong> <?php echo htmlspecialchars($selected['period_type']); ?> · <strong>Inicio:</strong> <?php echo ay_date($selected['start_date']); ?> · <strong>Fin:</strong> <?php echo ay_date($selected['end_date']); ?></div></div></div>
  <div class="tab-pane fade" id="ay-periodos"><div class="ay-section"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">Periodos académicos</h5><small class="text-muted">Define nombres y fechas. El bloqueo de notas se administra en la pestaña Cierre de notas.</small></div><?php if(!in_array($status,['Cerrado','Archivado'],true)): ?><button class="btn btn-sm btn-outline-primary" id="add-period"><i class="fas fa-plus mr-1"></i>Añadir</button><?php endif; ?></div><div id="period-list"><div class="text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Cargando periodos...</div></div><?php if(!in_array($status,['Cerrado','Archivado'],true)): ?><div class="text-right mt-3"><button class="btn btn-primary" id="save-periods"><i class="fas fa-save mr-1"></i>Guardar periodos</button></div><?php endif; ?></div></div>
  <div class="tab-pane fade" id="ay-cierre-notas"><div class="ay-section"><div class="d-flex justify-content-between align-items-center flex-wrap mb-3"><div><h5 class="mb-1">Control de cierre de notas</h5><small class="text-muted">Seguimiento docente y bloqueo institucional por bimestre.</small></div><button class="btn btn-sm btn-outline-primary mt-2 mt-md-0" id="ay-refresh-grade-control"><i class="fas fa-sync-alt mr-1"></i>Actualizar</button></div><div class="alert alert-light border ay-control-note small"><strong>Flujo:</strong> el docente cierra su curso/aula → Administración revisa el avance → se realiza el bloqueo institucional. Desbloquear un bimestre no reabre los cierres docentes ya realizados.</div><div id="ay-grade-control-body"><div class="text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Consultando cierres...</div></div></div></div>
  <div class="tab-pane fade" id="ay-auditoria"><div class="ay-section"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">Auditoría</h5><small class="text-muted">Historial de cambios y decisiones administrativas de este año.</small></div><button class="btn btn-sm btn-outline-secondary" id="refresh-audit"><i class="fas fa-sync-alt mr-1"></i>Actualizar</button></div><div id="audit-body"><div class="text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Cargando auditoría...</div></div></div></div>
 </div>
<?php endif; ?>
</div>

<div class="modal fade" id="year-modal"><div class="modal-dialog"><div class="modal-content"><form id="year-form"><div class="modal-header"><h5 class="modal-title">Preparar año académico</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input type="hidden" name="id" id="year-id"><div class="form-row"><div class="form-group col-6"><label>Año</label><input class="form-control" name="year" id="year-name" maxlength="4" required></div><div class="form-group col-6"><label>Organización</label><select class="form-control" name="period_type" id="period-type"><option>Bimestre</option><option>Trimestre</option><option>Semestre</option><option>Personalizado</option></select></div></div><div class="form-group"><label>Descripción</label><textarea class="form-control" name="description" id="year-description" rows="2"></textarea></div><div class="form-row"><div class="form-group col-6"><label>Inicio</label><input type="date" class="form-control" name="start_date" id="year-start" required></div><div class="form-group col-6"><label>Fin</label><input type="date" class="form-control" name="end_date" id="year-end" required></div></div><div class="alert alert-light small mb-0">Los cambios se guardan dentro del colegio actual.</div></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></div></div></div>
<div class="modal fade" id="copy-modal"><div class="modal-dialog"><div class="modal-content"><form id="copy-form"><div class="modal-header"><h5 class="modal-title">Copiar configuración</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Año de origen</label><select name="source_year_id" class="form-control" required><option value="">Seleccione</option><?php foreach($years as $y): if($selected && (int)$y['id']===(int)$selected['id']) continue; ?><option value="<?php echo (int)$y['id']; ?>"><?php echo htmlspecialchars($y['year'].' - '.$y['status']); ?></option><?php endforeach; ?></select></div><input type="hidden" name="target_year_id" value="<?php echo (int)($selected['id']??0); ?>"><?php foreach(['copy_areas_courses'=>'Áreas y cursos','copy_assignments'=>'Asignaciones docentes','copy_competencies'=>'Competencias','copy_periods'=>'Periodos'] as $name=>$label): ?><div class="custom-control custom-checkbox mb-2"><input type="checkbox" class="custom-control-input" name="<?php echo $name; ?>" value="1" id="<?php echo $name; ?>" checked><label class="custom-control-label" for="<?php echo $name; ?>"><?php echo $label; ?></label></div><?php endforeach; ?><div class="alert alert-warning small mt-3 mb-0">No se copian estudiantes, evaluaciones ni notas.</div></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal">Cancelar</button><button class="btn btn-info">Copiar</button></div></form></div></div></div>
<div class="modal fade" id="info-modal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="info-title">Información</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="info-body"></div></div></div></div>
<div class="modal fade" id="institutional-lock-modal"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="institutional-lock-title">Bloqueo institucional</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input type="hidden" id="institutional-bimester"><input type="hidden" id="institutional-target"><input type="hidden" id="institutional-force" value="0"><div id="institutional-lock-message" class="alert alert-light border"></div><div class="form-group ay-lock-reason" id="institutional-reason-group"><label class="font-weight-bold">Motivo</label><textarea class="form-control" id="institutional-reason" rows="3" maxlength="500" placeholder="Indique el motivo administrativo..."></textarea><small class="text-muted">Quedará registrado en auditoría.</small></div></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" id="institutional-confirm">Confirmar</button></div></div></div></div>

<script>
(function(){
const csrf=<?php echo json_encode($csrf); ?>,
      manage=<?php echo $manage?'true':'false'; ?>,
      selectedId=<?php echo (int)($selected['id']??0); ?>,
      selectedStatus=<?php echo json_encode($selected['status']??''); ?>,
      selectedType=<?php echo json_encode($selected['period_type']??''); ?>,
      activeYearId=<?php echo (int)($active['id']??0); ?>,
      years=<?php echo json_encode(array_map(fn($y)=>['id'=>(int)$y['id'],'year'=>$y['year'],'start'=>$y['start_date'],'end'=>$y['end_date'],'type'=>$y['period_type'],'status'=>$y['status']],$years),JSON_UNESCAPED_UNICODE); ?>,
      gradeControlApi='academic_year_grade_control_api.php';
let gradeControlData=null, periodsLoaded=false, auditLoaded=false;
function esc(v){return $('<div>').text(v==null?'':v).html();}
function post(action,data){data=data||{};data.csrf_token=csrf;return $.ajax({url:'ajax.php?action='+action,method:'POST',data:data,dataType:'json'});}
function gradePost(action,data){data=data||{};data.action=action;data.csrf_token=csrf;return $.ajax({url:gradeControlApi,method:'POST',data:data,dataType:'json'});}
function gradeGet(action,data){data=data||{};data.action=action;return $.getJSON(gradeControlApi,data);}
function toast(msg,type){if(typeof alert_toast==='function')alert_toast(msg,type||'success');else alert(msg);}
function reloadSoon(){setTimeout(()=>location.reload(),550);}

if(!manage){
 try{$('#years-table').DataTable({order:[],columnDefs:[{orderable:false,targets:[4]}],language:{search:'Buscar:',lengthMenu:'Mostrar _MENU_',info:'_START_–_END_ de _TOTAL_',paginate:{previous:'Anterior',next:'Siguiente'}}});}catch(e){}
 $('#new-year').on('click',function(){$('#year-form')[0].reset();$('#year-id').val('');$('#year-modal .modal-title').text('Preparar año académico');$('#year-modal').modal('show');});
 $('#open-compare').on('click',function(){let opts=years.map(x=>'<option value="'+x.id+'">'+esc(x.year)+'</option>').join('');$('#info-title').text('Comparar años');$('#info-body').html('<div class="form-row"><div class="col"><select id="compare-a" class="form-control">'+opts+'</select></div><div class="col"><select id="compare-b" class="form-control">'+opts+'</select></div><div class="col-auto"><button id="run-compare" class="btn btn-info">Comparar</button></div></div><div id="compare-result" class="mt-3"></div>');$('#info-modal').modal('show');});
 $(document).on('click','#run-compare',function(){let a=$('#compare-a').val(),b=$('#compare-b').val();$.getJSON('ajax.php?action=compare_academic_years',{year_a:a,year_b:b}).done(function(r){if(!r||!r.a)return;let keys=[...new Set(Object.keys(r.a.summary||{}).concat(Object.keys(r.b.summary||{})))],html='<table class="table"><thead><tr><th>Indicador</th><th>'+esc(r.a.year.year)+'</th><th>'+esc(r.b.year.year)+'</th></tr></thead><tbody>';keys.forEach(k=>html+='<tr><td>'+esc(k)+'</td><td>'+(r.a.summary[k]||0)+'</td><td>'+(r.b.summary[k]||0)+'</td></tr>');$('#compare-result').html(html+'</tbody></table>');});});
}

$('#year-form').on('submit',function(e){e.preventDefault();let data=$(this).serializeArray().reduce((o,x)=>(o[x.name]=x.value,o),{});post('save_academic_year',data).done(function(r){if(r&&r.status==1){toast(r.msg||'Año guardado','success');if(manage)reloadSoon();else setTimeout(()=>location.href='index.php?page=academic_year&manage=1&id='+r.id,500);}else toast((r&&r.msg)||'No se pudo guardar','danger');});});

if(!manage)return;

function loadSummary(){
 $.getJSON('ajax.php?action=get_year_summary',{id:selectedId}).done(function(r){if(!r||Number(r.status)!==1){$('#ay-summary-cards').html('<div class="col-12"><div class="alert alert-warning">No se pudo cargar el resumen.</div></div>');return;}let html='';Object.entries(r.summary||{}).forEach(function(x){html+='<div class="col-md-4 col-xl-3 mb-2"><div class="ay-stat"><small class="text-muted">'+esc(x[0])+'</small><br><strong>'+Number(x[1]||0)+'</strong></div></div>';});if(!html)html='<div class="col-12"><div class="alert alert-light border mb-0">Todavía no hay información relacionada con este año.</div></div>';$('#ay-summary-cards').html(html);});
}
$('#edit-selected-year').on('click',function(){post('get_academic_year',{id:selectedId}).done(function(y){if(!y)return;$('#year-id').val(y.id);$('#year-name').val(y.year);$('#year-description').val(y.description);$('#year-start').val(y.start_date);$('#year-end').val(y.end_date);$('#period-type').val(y.period_type);$('#year-modal .modal-title').text('Editar año académico');$('#year-modal').modal('show');});});
$('#copy-selected-year').on('click',()=>$('#copy-modal').modal('show'));
$('#copy-form').on('submit',function(e){e.preventDefault();let data={};$(this).serializeArray().forEach(x=>data[x.name]=x.value);post('copy_academic_year',data).done(function(r){if(r&&r.status==1){toast(r.msg||'Configuración copiada','success');reloadSoon();}else toast((r&&r.msg)||'No se pudo copiar','danger');});});
$('#activate-selected-year').on('click',function(){if(activeYearId&&activeYearId!==selectedId){toast('Primero cierre institucionalmente el año académico activo antes de activar uno nuevo.','warning');return;}if(confirm('¿Activar este año académico?'))post('activate_academic_year',{id:selectedId}).done(function(r){if(r&&r.status==1){toast(r.msg,'success');reloadSoon();}else toast((r&&r.msg)||'No se pudo activar','danger');});});
$('#delete-selected-year').on('click',function(){if(!confirm('Solo se eliminará si está completamente vacío. ¿Continuar?'))return;post('delete_academic_year',{id:selectedId}).done(function(r){if(r&&r.status==1){toast(r.msg,'success');setTimeout(()=>location.href='index.php?page=academic_year',500);}else{let msg=(r&&r.msg)||'No se pudo eliminar';if(r&&r.dependencies)msg+=' '+Object.entries(r.dependencies).map(x=>x[0]+': '+x[1]).join(', ');toast(msg,'danger');}});});
$('#reopen-selected-year').on('click',function(){let reason=prompt('Motivo obligatorio de reapertura:');if(reason)post('reopen_academic_year',{id:selectedId,reason:reason}).done(function(r){if(r&&r.status==1){toast(r.msg,'success');reloadSoon();}else toast((r&&r.msg)||'No se pudo reabrir','danger');});});
$('#archive-selected-year').on('click',function(){if(confirm('¿Archivar este año? Su historial se conservará.'))post('archive_academic_year',{id:selectedId}).done(function(r){if(r&&r.status==1){toast(r.msg,'success');reloadSoon();}else toast((r&&r.msg)||'No se pudo archivar','danger');});});

function periodRow(p){let locked=!!(p&&+p.is_locked),readonly=locked||['Cerrado','Archivado'].includes(selectedStatus);let row=$('<div class="ay-period-row" data-locked="'+(locked?1:0)+'"><span class="period-number badge badge-light"></span><input class="form-control period-name" placeholder="Nombre" required><input type="date" class="form-control period-start"><input type="date" class="form-control period-end"><span class="badge '+(locked?'badge-info':'badge-light border')+'">'+(locked?'Bloqueado':'Abierto')+'</span><button type="button" class="btn btn-sm btn-outline-danger remove-period"><i class="fas fa-times"></i></button></div>');row.find('.period-name').val(p&&p.name||'');row.find('.period-start').val(p&&p.start_date||'');row.find('.period-end').val(p&&p.end_date||'');if(readonly)row.find('input,.remove-period').prop('disabled',true);return row;}
function renumber(){$('#period-list .ay-period-row').each(function(i){$(this).find('.period-number').text(i+1);});}
function loadPeriods(){if(periodsLoaded)return;periodsLoaded=true;$.getJSON('ajax.php?action=get_academic_periods',{academic_year_id:selectedId}).done(function(r){$('#period-list').empty();let hasLocked=false;(r.periods||[]).forEach(function(p){if(+p.is_locked)hasLocked=true;$('#period-list').append(periodRow(p));});if(!(r.periods||[]).length){let count=selectedType==='Semestre'?2:selectedType==='Trimestre'?3:selectedType==='Bimestre'?4:1;for(let i=0;i<count;i++)$('#period-list').append(periodRow({name:(selectedType==='Personalizado'?'Periodo':selectedType)+' '+(i+1)}));}if(hasLocked)$('#add-period').prop('disabled',true);renumber();});}
$('#add-period').on('click',function(){$('#period-list').append(periodRow());renumber();});$(document).on('click','.remove-period',function(){$(this).closest('.ay-period-row').remove();renumber();});
$('#save-periods').on('click',function(){let items=[],invalid=false;$('#period-list .ay-period-row').each(function(){let name=$.trim($(this).find('.period-name').val());if(!name)invalid=true;items.push({name:name,start_date:$(this).find('.period-start').val(),end_date:$(this).find('.period-end').val(),is_locked:Number($(this).data('locked')||0)});});if(invalid||!items.length){toast('Todos los periodos deben tener nombre.','warning');return;}post('save_academic_periods',{academic_year_id:selectedId,periods:JSON.stringify(items)}).done(function(r){if(r&&r.status==1){toast(r.msg||'Periodos guardados','success');periodsLoaded=false;loadPeriods();}else toast((r&&r.msg)||'No se pudieron guardar','danger');});});

function stateBadge(state){let map={'Cerrado':'success','Listo':'primary','Incompleto':'warning','Reabierto':'info','Reapertura pendiente':'danger'};return '<span class="badge badge-'+(map[state]||'secondary')+' ay-state-badge">'+esc(state)+'</span>';}
function renderGradeControl(r){gradeControlData=r;let html='<div class="row">';for(let b=1;b<=4;b++){let p=r.periods&&r.periods[b]?r.periods[b]:null,s=p?p.summary:{};s=s||{};let locked=!!s.locked,total=Number(s.total||0),closed=Number(s.closed||0),progress=Number(s.progress||0),pending=Math.max(0,total-closed);html+='<div class="col-xl-3 col-md-6 mb-3"><div class="ay-close-card '+(locked?'locked':'open')+'"><div class="d-flex justify-content-between align-items-start"><div><small class="text-muted">'+b+'° BIMESTRE</small><div class="font-weight-bold text-gray-800">'+closed+' de '+total+' cierres</div></div><span class="badge badge-'+(locked?'info':'warning')+'">'+(locked?'🔒 Bloqueado':'🔓 Abierto')+'</span></div><div class="d-flex justify-content-between small mt-2"><span>Avance docente</span><strong>'+progress.toFixed(1)+'%</strong></div><div class="progress ay-close-progress"><div class="progress-bar '+(progress>=100?'bg-success':'bg-warning')+'" style="width:'+Math.min(100,progress)+'%"></div></div><div class="ay-close-kpis"><div class="ay-close-kpi"><small>Cerrados</small><strong>'+closed+'</strong></div><div class="ay-close-kpi"><small>Listos</small><strong>'+Number(s.ready||0)+'</strong></div><div class="ay-close-kpi"><small>Incompletos</small><strong>'+Number(s.incomplete||0)+'</strong></div><div class="ay-close-kpi"><small>Reabiertos / solicitud</small><strong>'+Number(s.reopened||0)+' / '+Number(s.pending_reopen||0)+'</strong></div></div><div class="ay-close-actions"><button class="btn btn-sm btn-outline-primary ay-grade-detail" data-bim="'+b+'"><i class="fas fa-list mr-1"></i>Ver detalle</button>'+(selectedStatus==='Activo'?'<button class="btn btn-sm '+(locked?'btn-outline-warning':'btn-outline-danger')+' ay-institutional-lock" data-bim="'+b+'" data-target="'+(locked?0:1)+'"><i class="fas '+(locked?'fa-unlock':'fa-lock')+' mr-1"></i>'+(locked?'Desbloquear':'Bloquear')+'</button>':'')+'</div>'+(pending>0&&!locked?'<div class="small text-warning mt-2"><i class="fas fa-exclamation-triangle mr-1"></i>'+pending+' asignación(es) aún no han cerrado.</div>':'')+'</div></div>'; }html+='</div>';$('#ay-grade-control-body').html(html);}
function loadGradeControl(){$('#ay-grade-control-body').html('<div class="text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Consultando cierres...</div>');gradeGet('progress',{academic_year_id:selectedId}).done(function(r){if(r&&Number(r.status)===1)renderGradeControl(r);else $('#ay-grade-control-body').html('<div class="alert alert-warning mb-0">'+esc((r&&r.message)||'No se pudo cargar el control de cierres.')+'</div>');}).fail(function(x){let r=x.responseJSON||{};$('#ay-grade-control-body').html('<div class="alert alert-warning mb-0">'+esc(r.message||'No se pudo cargar el control de cierres.')+'</div>');});}
$('#ay-refresh-grade-control').on('click',loadGradeControl);
$(document).on('click','.ay-grade-detail',function(){if(!gradeControlData)return;let b=Number($(this).data('bim')),p=gradeControlData.periods&&gradeControlData.periods[b],items=p&&p.items?p.items:[];let html='<div class="d-flex justify-content-between mb-2"><div><strong>'+b+'° Bimestre</strong><div class="small text-muted">Detalle por curso y aula</div></div><span class="badge badge-'+(p&&p.summary&&p.summary.locked?'info':'warning')+'">'+(p&&p.summary&&p.summary.locked?'Bloqueo institucional activo':'Bimestre abierto')+'</span></div><div class="table-responsive"><table class="table table-sm table-hover"><thead class="thead-light"><tr><th>Curso</th><th>Aula</th><th>Docente</th><th>Avance</th><th>Estado</th></tr></thead><tbody>';items.forEach(function(x){html+='<tr><td><strong>'+esc(x.course_name)+'</strong><div class="small text-muted">'+esc(x.level)+'</div></td><td>'+esc(x.grado)+'° '+esc(x.seccion)+'</td><td>'+esc(x.teacher_name)+'</td><td>'+Number(x.grade_progress||0).toFixed(1)+'%</td><td>'+stateBadge(x.state)+(x.issues&&x.issues.length?'<div class="small text-muted mt-1">'+esc(x.issues[0])+'</div>':'')+'</td></tr>';});html+='</tbody></table></div>';$('#info-title').text('Control de cierre de notas');$('#info-body').html(html);$('#info-modal').modal('show');});
function openInstitutionalModal(b,target){if(!gradeControlData)return;let p=gradeControlData.periods&&gradeControlData.periods[b],s=p&&p.summary?p.summary:{},pending=Math.max(0,Number(s.total||0)-Number(s.closed||0));$('#institutional-bimester').val(b);$('#institutional-target').val(target);$('#institutional-reason').val('');let force=target===1&&(pending>0||Number(s.total||0)===0);$('#institutional-force').val(force?1:0);let needsReason=force||target===0;$('#institutional-reason-group').toggle(needsReason);if(target===1){$('#institutional-lock-title').text('Bloquear '+b+'° Bimestre');$('#institutional-confirm').attr('class','btn '+(force?'btn-danger':'btn-primary')).html('<i class="fas fa-lock mr-1"></i>Confirmar bloqueo');$('#institutional-lock-message').attr('class','alert '+(force?'alert-warning':'alert-info')).html(force?'<strong>Bloqueo anticipado.</strong><br>Hay '+pending+' asignación(es) sin cierre docente. Debes registrar el motivo.':'Todos los cierres docentes están completos. El bloqueo impedirá nuevas modificaciones.');}else{$('#institutional-lock-title').text('Desbloquear '+b+'° Bimestre');$('#institutional-confirm').attr('class','btn btn-warning').html('<i class="fas fa-unlock mr-1"></i>Confirmar desbloqueo');$('#institutional-lock-message').attr('class','alert alert-warning').html('<strong>Importante:</strong> desbloquear no reabre los cierres individuales ya realizados.');}$('#institutional-lock-modal').modal('show');}
$(document).on('click','.ay-institutional-lock',function(){openInstitutionalModal(Number($(this).data('bim')),Number($(this).data('target')));});
$('#institutional-confirm').on('click',function(){let b=Number($('#institutional-bimester').val()),target=Number($('#institutional-target').val()),force=Number($('#institutional-force').val()),reason=$.trim($('#institutional-reason').val());if((force||target===0)&&reason.length<5){toast('Indique un motivo de al menos 5 caracteres.','warning');return;}let btn=$(this).prop('disabled',true);gradePost('set_lock',{academic_year_id:selectedId,bimester:b,locked:target,force:force,reason:reason}).done(function(r){if(Number(r.status)===1){$('#institutional-lock-modal').modal('hide');toast(r.message,'success');periodsLoaded=false;loadGradeControl();return;}if(Number(r.status)===2){$('#institutional-force').val(1);$('#institutional-reason-group').show();$('#institutional-lock-message').attr('class','alert alert-warning').html(esc(r.message));toast(r.message,'warning');return;}toast(r.message||'No se pudo cambiar el bloqueo.','danger');}).fail(function(x){toast((x.responseJSON||{}).message||'No se pudo cambiar el bloqueo.','danger');}).always(function(){btn.prop('disabled',false);});});

function loadAudit(){auditLoaded=true;$('#audit-body').html('<div class="text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Cargando auditoría...</div>');$.getJSON('ajax.php?action=get_academic_year_audit',{academic_year_id:selectedId}).done(function(r){let items=r.audit||[],html='<div class="ay-audit-list list-group">';items.forEach(function(x){html+='<div class="list-group-item ay-audit-item"><div class="d-flex justify-content-between"><strong>'+esc(x.action)+'</strong><span class="small text-muted">'+esc(x.created_at)+'</span></div><div class="small text-muted">'+esc(x.user_name||'Sistema')+'</div>'+(x.details?'<div class="small mt-1 text-secondary">'+esc(x.details)+'</div>':'')+'</div>';});html+='</div>';if(!items.length)html='<div class="alert alert-light border mb-0">No hay movimientos registrados para este año.</div>';$('#audit-body').html(html);});}
$('#refresh-audit').on('click',loadAudit);

$('#close-selected-year').on('click',function(){gradeGet('annual_checklist',{academic_year_id:selectedId}).done(function(r){if(!r||Number(r.status)!==1){toast((r&&r.message)||'No se pudo obtener el checklist.','danger');return;}let html='<div class="alert '+(r.can_close?'alert-success':'alert-warning')+'"><strong>'+(r.can_close?'Año listo para cierre institucional.':'El año todavía no está listo para cerrar.')+'</strong><div class="small mt-1">Cierres docentes: '+Number((r.closure_summary||{}).closed||0)+' de '+Number((r.closure_summary||{}).total||0)+'.</div></div><ul class="list-group mb-3">';(r.items||[]).forEach(function(x){let badge=x.blocking?'danger':(x.severity==='warning'?'warning':(x.severity==='info'?'info':'success'));html+='<li class="list-group-item d-flex justify-content-between align-items-center"><span>'+esc(x.label)+'</span><span class="badge badge-'+badge+'">'+Number(x.count||0)+'</span></li>';});html+='</ul><div class="form-group"><label>Observación de cierre</label><textarea id="close-notes" class="form-control" rows="3"></textarea></div><button class="btn btn-danger" id="confirm-close-year" '+(r.can_close?'':'disabled')+'><i class="fas fa-lock mr-1"></i>Cerrar año académico</button>';$('#info-title').text('Checklist de cierre anual');$('#info-body').html(html);$('#info-modal').modal('show');});});
$(document).on('click','#confirm-close-year',function(){let notes=$.trim($('#close-notes').val());if(notes.length<5){toast('Indique una observación de al menos 5 caracteres.','warning');return;}let btn=$(this).prop('disabled',true);gradePost('close_year',{academic_year_id:selectedId,notes:notes}).done(function(r){if(r&&Number(r.status)===1){toast(r.message,'success');reloadSoon();}else{toast((r&&r.message)||'No se pudo cerrar el año.','danger');btn.prop('disabled',false);}}).fail(function(x){toast((x.responseJSON||{}).message||'No se pudo cerrar el año.','danger');btn.prop('disabled',false);});});

$('a[href="#ay-periodos"]').on('shown.bs.tab',loadPeriods);
$('a[href="#ay-cierre-notas"]').on('shown.bs.tab',loadGradeControl);
$('a[href="#ay-auditoria"]').on('shown.bs.tab',function(){if(!auditLoaded)loadAudit();});
loadSummary();
})();
</script>
