<?php
include 'db_connect.php';
if(empty($_SESSION['login_id'])||(int)($_SESSION['login_type']??0)!==1){header('location: login.php');exit;}
$school_id=(int)($_SESSION['login_school_id']??0);
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$csrf=$_SESSION['csrf_token'];
// Solo comprobar el esquema. Las migraciones se ejecutan manualmente mediante SQL.
function ayp_col($db,$name){$v=$db->real_escape_string($name);$q=$db->query("SHOW COLUMNS FROM academic_year LIKE '$v'");return $q&&$q->num_rows;}
$migration_ready=true;
foreach(['status','period_type','closed_at','closed_by','close_notes','reopened_at','reopened_by','reopen_reason'] as $column){if(!ayp_col($conn,$column)){$migration_ready=false;break;}}
foreach(['academic_periods','academic_year_audit','bimester_locks'] as $table){$safe=$conn->real_escape_string($table);$q=$conn->query("SHOW TABLES LIKE '$safe'");if(!$q||!$q->num_rows){$migration_ready=false;break;}}
if($migration_ready){$q=$conn->query("SHOW COLUMNS FROM academic_periods LIKE 'start_date'");$start=$q?$q->fetch_assoc():null;$q=$conn->query("SHOW COLUMNS FROM academic_periods LIKE 'end_date'");$end=$q?$q->fetch_assoc():null;if(!$start||!$end||strtoupper($start['Null']??'NO')!=='YES'||strtoupper($end['Null']??'NO')!=='YES')$migration_ready=false;}
if(!$migration_ready):
?>
<div class="container-fluid"><div class="alert alert-warning shadow-sm"><h5><i class="fa fa-database mr-2"></i>Actualización de base de datos pendiente</h5><p class="mb-2">El módulo no modificará automáticamente la estructura de la base de datos.</p><p class="mb-0">Ejecute manualmente <code>sql/academic_year_lifecycle_upgrade.sql</code> y vuelva a cargar esta página.</p></div></div>
<?php return; endif;
$years=[];$s=$conn->prepare("SELECT * FROM academic_year WHERE school_id=? ORDER BY FIELD(status,'Activo','Borrador','Cerrado','Archivado'),start_date DESC");$s->bind_param('i',$school_id);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$years[]=$x;$s->close();
$active=null;foreach($years as $y)if((int)$y['is_active']===1){$active=$y;break;}
function ay_badge($status){return ['Activo'=>'success','Borrador'=>'warning','Cerrado'=>'secondary','Archivado'=>'dark'][$status]??'secondary';}
?>
<style>
.ay-shell{max-width:1500px;margin:auto;padding-top:8px}.ay-hero{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px;padding:0 4px;background:transparent;color:inherit}.ay-heading{display:flex;align-items:center;gap:12px}.ay-hero-icon{width:46px;height:46px;border-radius:12px;background:#eaf2ff;color:#2f6fed;display:flex;align-items:center;justify-content:center;font-size:20px;flex:0 0 46px}.ay-hero h5{margin:0;font-weight:700;color:#233b52}.ay-hero small{display:block;color:#6c757d;margin-top:2px}.ay-stat{background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:16px;height:100%}.ay-stat strong{font-size:1.45rem;color:#172b4d}.ay-actions .btn{margin:2px}.period-row{display:grid;grid-template-columns:45px 1fr 150px 150px 110px 40px;gap:8px;align-items:center;margin-bottom:8px}.compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.audit-list{max-height:390px;overflow:auto}.ay-close-card{border:1px solid #e3e8f0;border-radius:12px;background:#fff;padding:14px;height:100%}.ay-close-card.locked{border-left:4px solid #36b9cc}.ay-close-card.open{border-left:4px solid #f6c23e}.ay-close-progress{height:7px}.ay-close-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:10px 0}.ay-close-kpi{background:#f8f9fc;border:1px solid #edf0f5;border-radius:8px;padding:7px 9px}.ay-close-kpi small{display:block;color:#858796;font-size:.68rem}.ay-close-kpi strong{font-size:1rem;color:#334155}.ay-close-actions{display:flex;gap:6px;flex-wrap:wrap}.ay-grade-detail-table td,.ay-grade-detail-table th{vertical-align:middle}.ay-state-badge{font-size:.7rem}.ay-control-note{border-left:4px solid #4e73df}.ay-lock-status{font-size:.72rem}.ay-lock-reason{display:none}@media(max-width:768px){.ay-hero{align-items:flex-start;flex-direction:column}.period-row{grid-template-columns:35px 1fr 1fr}.period-row .period-name{grid-column:2/4}.compare-grid{grid-template-columns:1fr}.ay-close-kpis{grid-template-columns:1fr 1fr}}
</style>
<div class="container-fluid ay-shell">
 <div class="ay-hero">
  <div class="ay-heading"><div class="ay-hero-icon"><i class="fa fa-calendar-alt"></i></div><div><h5>Años académicos</h5><small>Administra la apertura, los periodos y el cierre de cada año escolar</small></div></div>
  <button class="btn btn-primary" id="new-year"><i class="fa fa-plus mr-1"></i>Nuevo año</button>
 </div>
 <?php if($active): ?>
 <div class="row mb-4">
  <div class="col-md-3 mb-2"><div class="ay-stat"><small class="text-muted">Año operativo</small><br><strong><?php echo htmlspecialchars($active['year']); ?></strong></div></div>
  <div class="col-md-3 mb-2"><div class="ay-stat"><small class="text-muted">Inicio</small><br><strong><?php echo date('d/m/Y',strtotime($active['start_date'])); ?></strong></div></div>
  <div class="col-md-3 mb-2"><div class="ay-stat"><small class="text-muted">Finalización</small><br><strong><?php echo date('d/m/Y',strtotime($active['end_date'])); ?></strong></div></div>
  <div class="col-md-3 mb-2"><div class="ay-stat"><small class="text-muted">Organización</small><br><strong><?php echo htmlspecialchars($active['period_type']); ?></strong></div></div>
 </div>
 <div class="card shadow-sm mb-4" id="ay-grade-control" data-year-id="<?php echo (int)$active['id']; ?>">
  <div class="card-header bg-white d-flex justify-content-between align-items-center flex-wrap">
   <div><strong><i class="fas fa-user-check text-primary mr-2"></i>Control de cierre de notas</strong><div class="small text-muted">Cierre docente → bloqueo institucional → cierre del año.</div></div>
   <button class="btn btn-sm btn-outline-primary mt-2 mt-md-0" id="ay-refresh-grade-control"><i class="fas fa-sync-alt mr-1"></i>Actualizar</button>
  </div>
  <div class="card-body">
   <div class="alert alert-light border ay-control-note small"><strong>Bloqueo institucional:</strong> cuando se activa, ningún docente puede editar ese bimestre, haya realizado o no su cierre individual. Desbloquearlo no reabre los cierres docentes ya realizados.</div>
   <div id="ay-grade-control-body"><div class="text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Consultando cierres docentes...</div></div>
  </div>
 </div>
 <?php else: ?><div class="alert alert-warning"><i class="fa fa-exclamation-triangle mr-1"></i>No hay un año activo. Prepare periodos en un borrador y actívelo.</div><?php endif; ?>

 <div class="card shadow-sm mb-4"><div class="card-header d-flex justify-content-between align-items-center"><strong>Historial y ciclo de vida</strong><div><button class="btn btn-sm btn-outline-info" id="open-compare"><i class="fa fa-balance-scale mr-1"></i>Comparar</button> <button class="btn btn-sm btn-outline-secondary" id="open-audit"><i class="fa fa-history mr-1"></i>Auditoría</button></div></div>
 <div class="card-body table-responsive"><table class="table table-hover" id="years-table"><thead><tr><th>Año</th><th>Fechas</th><th>Periodos</th><th>Estado</th><th class="text-right">Acciones</th></tr></thead><tbody>
 <?php foreach($years as $y): $status=$y['status']?:((int)$y['is_active']?'Activo':'Borrador'); ?>
 <tr data-id="<?php echo (int)$y['id']; ?>" data-status="<?php echo htmlspecialchars($status); ?>"><td><strong><?php echo htmlspecialchars($y['year']); ?></strong><div class="small text-muted"><?php echo htmlspecialchars($y['description']?:'Sin descripción'); ?></div></td><td><?php echo date('d/m/Y',strtotime($y['start_date'])); ?> — <?php echo date('d/m/Y',strtotime($y['end_date'])); ?></td><td><?php echo htmlspecialchars($y['period_type']); ?></td><td><span class="badge badge-<?php echo ay_badge($status); ?>"><?php echo htmlspecialchars($status); ?></span></td><td class="text-right ay-actions">
  <button class="btn btn-sm btn-outline-info summary-year" title="Resumen"><i class="fa fa-chart-bar"></i></button>
  <?php if(!in_array($status,['Cerrado','Archivado'],true)): ?><button class="btn btn-sm btn-outline-primary periods-year" title="Periodos"><i class="fa fa-calendar-check"></i></button><button class="btn btn-sm btn-outline-primary edit-year" title="Editar"><i class="fa fa-edit"></i></button><?php endif; ?>
  <?php if($status==='Borrador'): ?><button class="btn btn-sm btn-outline-info copy-year" title="Copiar configuración"><i class="fa fa-copy"></i></button><button class="btn btn-sm btn-outline-success activate-year" title="Activar"><i class="fa fa-play"></i></button><button class="btn btn-sm btn-outline-danger delete-year" title="Eliminar si está vacío"><i class="fa fa-trash"></i></button><?php endif; ?>
  <?php if($status==='Activo'): ?><button class="btn btn-sm btn-outline-danger close-year" title="Cerrar"><i class="fa fa-lock"></i></button><?php endif; ?>
  <?php if($status==='Cerrado'): ?><button class="btn btn-sm btn-outline-warning reopen-year" title="Reabrir"><i class="fa fa-unlock"></i></button><button class="btn btn-sm btn-outline-dark archive-year" title="Archivar"><i class="fa fa-archive"></i></button><?php endif; ?>
 </td></tr><?php endforeach; ?>
 </tbody></table></div></div>
</div>

<div class="modal fade" id="year-modal"><div class="modal-dialog"><div class="modal-content"><form id="year-form"><div class="modal-header"><h5 class="modal-title">Preparar año académico</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf); ?>"><input type="hidden" name="id" id="year-id"><div id="year-msg"></div><div class="form-row"><div class="form-group col-6"><label>Año</label><input class="form-control" name="year" id="year-name" maxlength="4" required></div><div class="form-group col-6"><label>Organización</label><select class="form-control" name="period_type" id="period-type"><option>Bimestre</option><option>Trimestre</option><option>Semestre</option><option>Personalizado</option></select></div></div><div class="form-group"><label>Descripción</label><textarea class="form-control" name="description" id="year-description" rows="2"></textarea></div><div class="form-row"><div class="form-group col-6"><label>Inicio</label><input type="date" class="form-control" name="start_date" id="year-start" required></div><div class="form-group col-6"><label>Fin</label><input type="date" class="form-control" name="end_date" id="year-end" required></div></div><div class="alert alert-light small mb-0">El año se guarda como <strong>Borrador</strong>. Configure sus periodos antes de activarlo.</div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></div></div></div>

<div class="modal fade" id="period-modal"><div class="modal-dialog modal-lg"><div class="modal-content"><form id="period-form"><div class="modal-header"><h5 class="modal-title">Periodos académicos</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input type="hidden" id="period-year-id"><div class="d-flex justify-content-between mb-2"><small class="text-muted">Las fechas son opcionales. Si las utiliza, complete inicio y fin sin superponer periodos.</small><button type="button" class="btn btn-sm btn-outline-primary" id="add-period"><i class="fa fa-plus"></i> Añadir</button></div><div class="alert alert-info small py-2"><i class="fas fa-lock mr-1"></i>El bloqueo de notas ya no se modifica aquí. Utilice <strong>Control de cierre de notas</strong>.</div><div id="period-list"></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar periodos</button></div></form></div></div></div>

<div class="modal fade" id="copy-modal"><div class="modal-dialog"><div class="modal-content"><form id="copy-form"><div class="modal-header"><h5 class="modal-title">Copiar configuración</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf); ?>"><input type="hidden" name="target_year_id" id="copy-target"><div class="form-group"><label>Año de origen</label><select name="source_year_id" class="form-control" required><option value="">Seleccione</option><?php foreach($years as $y): ?><option value="<?php echo (int)$y['id']; ?>"><?php echo htmlspecialchars($y['year'].' - '.$y['status']); ?></option><?php endforeach; ?></select></div><?php foreach(['copy_areas_courses'=>'Áreas y cursos','copy_assignments'=>'Asignaciones docentes','copy_competencies'=>'Competencias','copy_periods'=>'Periodos (ajustando las fechas)'] as $name=>$label): ?><div class="custom-control custom-checkbox mb-2"><input type="checkbox" class="custom-control-input" name="<?php echo $name; ?>" value="1" id="<?php echo $name; ?>" checked><label class="custom-control-label" for="<?php echo $name; ?>"><?php echo $label; ?></label></div><?php endforeach; ?><div class="alert alert-warning small mt-3 mb-0">No se copian estudiantes, notas ni evaluaciones.</div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-info">Copiar</button></div></form></div></div></div>

<div class="modal fade" id="info-modal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="info-title">Información</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="info-body"></div></div></div></div>

<div class="modal fade" id="institutional-lock-modal"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="institutional-lock-title">Bloqueo institucional</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input type="hidden" id="institutional-bimester"><input type="hidden" id="institutional-target"><input type="hidden" id="institutional-force" value="0"><div id="institutional-lock-message" class="alert alert-light border"></div><div class="form-group ay-lock-reason" id="institutional-reason-group"><label class="font-weight-bold">Motivo</label><textarea class="form-control" id="institutional-reason" rows="3" maxlength="500" placeholder="Indique el motivo administrativo..."></textarea><small class="text-muted">El motivo quedará registrado en auditoría.</small></div></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal">Cancelar</button><button type="button" class="btn btn-primary" id="institutional-confirm">Confirmar</button></div></div></div></div>

<script>
(function(){
const csrf=<?php echo json_encode($csrf); ?>,
      years=<?php echo json_encode(array_map(fn($y)=>['id'=>(int)$y['id'],'year'=>$y['year'],'start'=>$y['start_date'],'end'=>$y['end_date'],'type'=>$y['period_type']],$years),JSON_UNESCAPED_UNICODE); ?>,
      activeYearId=<?php echo (int)($active['id']??0); ?>,
      gradeControlApi='academic_year_grade_control_api.php';
let gradeControlData=null;
function esc(v){return $('<div>').text(v==null?'':v).html();}
function post(action,data){data=data||{};data.csrf_token=csrf;return $.ajax({url:'ajax.php?action='+action,method:'POST',data:data,dataType:'json'});}function done(r){if(r&&r.status==1){alert_toast(r.msg||'Operación completada','success');setTimeout(()=>location.reload(),650);}else alert_toast((r&&r.msg)||'No se pudo completar','error');}
function gradePost(action,data){data=data||{};data.action=action;data.csrf_token=csrf;return $.ajax({url:gradeControlApi,method:'POST',data:data,dataType:'json'});}
function gradeGet(action,data){data=data||{};data.action=action;return $.getJSON(gradeControlApi,data);}
function stateBadge(state){let map={'Cerrado':'success','Listo':'primary','Incompleto':'warning','Reabierto':'info','Reapertura pendiente':'danger'};return '<span class="badge badge-'+(map[state]||'secondary')+' ay-state-badge">'+esc(state)+'</span>';}
function renderGradeControl(r){
 gradeControlData=r;
 let html='<div class="row">';
 for(let b=1;b<=4;b++){
  let p=r.periods&&r.periods[b]?r.periods[b]:null,s=p?p.summary:{};s=s||{};
  let locked=!!s.locked,total=Number(s.total||0),closed=Number(s.closed||0),progress=Number(s.progress||0),pending=Math.max(0,total-closed);
  html+='<div class="col-xl-3 col-md-6 mb-3"><div class="ay-close-card '+(locked?'locked':'open')+'">'+
   '<div class="d-flex justify-content-between align-items-start"><div><small class="text-muted">'+b+'° BIMESTRE</small><div class="font-weight-bold text-gray-800">'+closed+' de '+total+' cierres</div></div><span class="badge badge-'+(locked?'info':'warning')+' ay-lock-status">'+(locked?'🔒 Bloqueado':'🔓 Abierto')+'</span></div>'+
   '<div class="d-flex justify-content-between small mt-2"><span>Avance docente</span><strong>'+progress.toFixed(1)+'%</strong></div><div class="progress ay-close-progress"><div class="progress-bar '+(progress>=100?'bg-success':'bg-warning')+'" style="width:'+Math.min(100,progress)+'%"></div></div>'+
   '<div class="ay-close-kpis"><div class="ay-close-kpi"><small>Cerrados</small><strong>'+closed+'</strong></div><div class="ay-close-kpi"><small>Listos</small><strong>'+Number(s.ready||0)+'</strong></div><div class="ay-close-kpi"><small>Incompletos</small><strong>'+Number(s.incomplete||0)+'</strong></div><div class="ay-close-kpi"><small>Reabiertos / solicitud</small><strong>'+Number(s.reopened||0)+' / '+Number(s.pending_reopen||0)+'</strong></div></div>'+
   '<div class="ay-close-actions"><button class="btn btn-sm btn-outline-primary ay-grade-detail" data-bim="'+b+'"><i class="fas fa-list mr-1"></i>Ver detalle</button><button class="btn btn-sm '+(locked?'btn-outline-warning':'btn-outline-danger')+' ay-institutional-lock" data-bim="'+b+'" data-target="'+(locked?0:1)+'"><i class="fas '+(locked?'fa-unlock':'fa-lock')+' mr-1"></i>'+(locked?'Desbloquear':'Bloquear')+'</button></div>'+
   (pending>0&&!locked?'<div class="small text-warning mt-2"><i class="fas fa-exclamation-triangle mr-1"></i>'+pending+' asignación(es) aún no han cerrado.</div>':'')+
  '</div></div>';
 }
 html+='</div>';
 $('#ay-grade-control-body').html(html);
}
function loadGradeControl(){
 if(!activeYearId||!$('#ay-grade-control').length)return;
 $('#ay-grade-control-body').html('<div class="text-center text-muted py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Consultando cierres docentes...</div>');
 gradeGet('progress',{academic_year_id:activeYearId}).done(function(r){if(r&&Number(r.status)===1)renderGradeControl(r);else $('#ay-grade-control-body').html('<div class="alert alert-warning mb-0">'+esc((r&&r.message)||'No se pudo cargar el control de cierres.')+'</div>');}).fail(function(x){let r=x.responseJSON||{};$('#ay-grade-control-body').html('<div class="alert alert-warning mb-0"><i class="fas fa-database mr-1"></i>'+esc(r.message||'No se pudo cargar el control de cierres.')+'</div>');});
}
$('#ay-refresh-grade-control').on('click',loadGradeControl);
$(document).on('click','.ay-grade-detail',function(){
 if(!gradeControlData)return;let b=Number($(this).data('bim')),p=gradeControlData.periods&&gradeControlData.periods[b],items=p&&p.items?p.items:[];
 let html='<div class="d-flex justify-content-between mb-2"><div><strong>'+b+'° Bimestre</strong><div class="small text-muted">Detalle por curso y aula</div></div><span class="badge badge-'+(p&&p.summary&&p.summary.locked?'info':'warning')+'">'+(p&&p.summary&&p.summary.locked?'Bloqueo institucional activo':'Bimestre abierto')+'</span></div><div class="table-responsive"><table class="table table-sm table-hover ay-grade-detail-table"><thead class="thead-light"><tr><th>Curso</th><th>Aula</th><th>Docente</th><th>Avance</th><th>Estado</th></tr></thead><tbody>';
 items.forEach(function(x){html+='<tr><td><strong>'+esc(x.course_name)+'</strong><div class="small text-muted">'+esc(x.level)+'</div></td><td>'+esc(x.grado)+'° '+esc(x.seccion)+'</td><td>'+esc(x.teacher_name)+'</td><td>'+Number(x.grade_progress||0).toFixed(1)+'%</td><td>'+stateBadge(x.state)+(x.issues&&x.issues.length?'<div class="small text-muted mt-1">'+esc(x.issues[0])+'</div>':'')+'</td></tr>';});
 html+='</tbody></table></div>';$('#info-title').text('Control de cierre de notas');$('#info-body').html(html);$('#info-modal').modal('show');
});
function openInstitutionalModal(b,target){
 if(!gradeControlData)return;let p=gradeControlData.periods&&gradeControlData.periods[b],s=p&&p.summary?p.summary:{},pending=Math.max(0,Number(s.total||0)-Number(s.closed||0));
 $('#institutional-bimester').val(b);$('#institutional-target').val(target);$('#institutional-reason').val('');
 let force=target===1&&(pending>0||Number(s.total||0)===0);$('#institutional-force').val(force?1:0);
 let needsReason=force||target===0;$('#institutional-reason-group').toggle(needsReason);
 if(target===1){$('#institutional-lock-title').text('Bloquear '+b+'° Bimestre');$('#institutional-confirm').removeClass('btn-warning').addClass(force?'btn-danger':'btn-primary').html('<i class="fas fa-lock mr-1"></i>Confirmar bloqueo');$('#institutional-lock-message').attr('class','alert '+(force?'alert-warning':'alert-info')).html(force?'<strong>Bloqueo anticipado.</strong><br>Hay '+pending+' asignación(es) sin cierre docente. Al continuar se bloqueará la edición para todos los docentes.':'Todos los cierres docentes están completos. El bloqueo institucional impedirá nuevas modificaciones en este bimestre.');}
 else{$('#institutional-lock-title').text('Desbloquear '+b+'° Bimestre');$('#institutional-confirm').removeClass('btn-danger btn-primary').addClass('btn-warning').html('<i class="fas fa-unlock mr-1"></i>Confirmar desbloqueo');$('#institutional-lock-message').attr('class','alert alert-warning').html('<strong>Importante:</strong> desbloquear el bimestre no reabre los cierres individuales de los docentes. Quienes ya cerraron deberán solicitar reapertura.');}
 $('#institutional-lock-modal').modal('show');
}
$(document).on('click','.ay-institutional-lock',function(){openInstitutionalModal(Number($(this).data('bim')),Number($(this).data('target')));});
$('#institutional-confirm').on('click',function(){
 let b=Number($('#institutional-bimester').val()),target=Number($('#institutional-target').val()),force=Number($('#institutional-force').val()),reason=$.trim($('#institutional-reason').val());
 if((force||target===0)&&reason.length<5){alert_toast('Indique un motivo de al menos 5 caracteres.','warning');return;}
 let btn=$(this).prop('disabled',true);gradePost('set_lock',{academic_year_id:activeYearId,bimester:b,locked:target,force:force,reason:reason}).done(function(r){if(Number(r.status)===1){$('#institutional-lock-modal').modal('hide');alert_toast(r.message,'success');loadGradeControl();return;}if(Number(r.status)===2){$('#institutional-force').val(1);$('#institutional-reason-group').show();$('#institutional-lock-message').attr('class','alert alert-warning').html('<strong>Confirmación adicional requerida.</strong><br>'+esc(r.message));alert_toast(r.message,'warning');return;}alert_toast(r.message||'No se pudo cambiar el bloqueo.','danger');}).fail(function(x){alert_toast((x.responseJSON||{}).message||'No se pudo cambiar el bloqueo.','danger');}).always(function(){btn.prop('disabled',false);});
});
$('#new-year').on('click',function(){$('#year-form')[0].reset();$('#year-id').val('');$('#year-modal').modal('show');});
$(document).on('click','.edit-year',function(){post('get_academic_year',{id:$(this).closest('tr').data('id')}).done(function(y){if(!y)return;$('#year-id').val(y.id);$('#year-name').val(y.year);$('#year-description').val(y.description);$('#year-start').val(y.start_date);$('#year-end').val(y.end_date);$('#period-type').val(y.period_type);$('#year-modal').modal('show');});});
$('#year-form').on('submit',function(e){e.preventDefault();post('save_academic_year',$(this).serialize()).done(done);});
function periodRow(p){let locked=!!(p&&+p.is_locked);return $('<div class="period-row" data-locked="'+(locked?1:0)+'"><span class="period-number badge badge-light"></span><input class="form-control period-name" placeholder="Nombre" required><input type="date" class="form-control period-start" title="Inicio opcional"><input type="date" class="form-control period-end" title="Fin opcional"><span class="badge '+(locked?'badge-info':'badge-light border')+'">'+(locked?'Bloqueado':'Abierto')+'</span><button type="button" class="btn btn-sm btn-outline-danger remove-period">&times;</button></div>').each(function(){$(this).find('.period-name').val(p&&p.name||'');$(this).find('.period-start').val(p&&p.start_date||'');$(this).find('.period-end').val(p&&p.end_date||'');});}
function renumber(){$('#period-list .period-row').each(function(i){$(this).find('.period-number').text(i+1);});}
$(document).on('click','.periods-year',function(){let id=$(this).closest('tr').data('id');$('#period-year-id').val(id);$.getJSON('ajax.php?action=get_academic_periods',{academic_year_id:id}).done(function(r){$('#period-list').empty();let hasLocked=false;(r.periods||[]).forEach(function(p){if(+p.is_locked)hasLocked=true;$('#period-list').append(periodRow(p));});if(!r.periods||!r.periods.length){let y=years.find(x=>x.id==id),count=y.type==='Semestre'?2:y.type==='Trimestre'?3:y.type==='Bimestre'?4:1;for(let i=0;i<count;i++)$('#period-list').append(periodRow({name:(y.type==='Personalizado'?'Periodo':y.type)+' '+(i+1)}));}$('#add-period').prop('disabled',hasLocked);$('#period-list .remove-period').prop('disabled',hasLocked);renumber();$('#period-modal').modal('show');});});
$('#add-period').on('click',()=>{$('#period-list').append(periodRow());renumber();});$(document).on('click','.remove-period',function(){$(this).closest('.period-row').remove();renumber();});
$('#period-form').on('submit',function(e){e.preventDefault();let items=[];$('#period-list .period-row').each(function(){items.push({name:$(this).find('.period-name').val(),start_date:$(this).find('.period-start').val(),end_date:$(this).find('.period-end').val(),is_locked:Number($(this).data('locked')||0)});});post('save_academic_periods',{academic_year_id:$('#period-year-id').val(),periods:JSON.stringify(items)}).done(done);});
$(document).on('click','.copy-year',function(){$('#copy-target').val($(this).closest('tr').data('id'));$('#copy-modal').modal('show');});$('#copy-form').on('submit',function(e){e.preventDefault();post('copy_academic_year',$(this).serialize()).done(done);});
$(document).on('click','.activate-year',function(){let target=Number($(this).closest('tr').data('id'));if(activeYearId&&activeYearId!==target){alert_toast('Primero cierre institucionalmente el año académico activo desde su checklist.','warning');return;}if(confirm('¿Activar este año académico?'))post('activate_academic_year',{id:target}).done(done);});
$(document).on('click','.archive-year',function(){if(confirm('¿Archivar este año? Su historial se conservará.'))post('archive_academic_year',{id:$(this).closest('tr').data('id')}).done(done);});
$(document).on('click','.delete-year',function(){if(confirm('Solo se eliminará si está completamente vacío. ¿Continuar?'))post('delete_academic_year',{id:$(this).closest('tr').data('id')}).done(function(r){if(r.status!=1&&r.dependencies)r.msg+=' '+Object.entries(r.dependencies).map(x=>x[0]+': '+x[1]).join(', ');done(r);});});
$(document).on('click','.reopen-year',function(){let reason=prompt('Motivo obligatorio de reapertura:');if(reason)post('reopen_academic_year',{id:$(this).closest('tr').data('id'),reason:reason}).done(done);});
$(document).on('click','.close-year',function(){let id=$(this).closest('tr').data('id');gradeGet('annual_checklist',{academic_year_id:id}).done(function(r){if(!r||Number(r.status)!==1){alert_toast((r&&r.message)||'No se pudo obtener el checklist.','danger');return;}let html='<div class="alert '+(r.can_close?'alert-success':'alert-warning')+'"><strong>'+(r.can_close?'Año listo para cierre institucional.':'El año todavía no está listo para cerrar.')+'</strong><div class="small mt-1">Cierres docentes: '+Number((r.closure_summary||{}).closed||0)+' de '+Number((r.closure_summary||{}).total||0)+'.</div></div><ul class="list-group mb-3">';(r.items||[]).forEach(function(x){let badge=x.blocking?'danger':(x.severity==='warning'?'warning':(x.severity==='info'?'info':'success'));html+='<li class="list-group-item d-flex justify-content-between align-items-center"><span>'+esc(x.label)+'</span><span class="badge badge-'+badge+'">'+Number(x.count||0)+'</span></li>';});html+='</ul><div class="form-group"><label>Observación de cierre</label><textarea id="close-notes" class="form-control" rows="3" placeholder="Motivo u observación final..."></textarea></div><button class="btn btn-danger" id="confirm-close" data-id="'+id+'" '+(r.can_close?'':'disabled')+'><i class="fas fa-lock mr-1"></i>Cerrar año académico</button>';if(!r.can_close)html+='<div class="small text-muted mt-2">Primero complete los elementos marcados como bloqueantes. Los cierres docentes pendientes pueden existir únicamente si el bimestre fue bloqueado anticipadamente con motivo registrado.</div>';$('#info-title').text('Checklist de cierre anual');$('#info-body').html(html);$('#info-modal').modal('show');}).fail(function(x){alert_toast((x.responseJSON||{}).message||'No se pudo obtener el checklist.','danger');});});
$(document).on('click','#confirm-close',function(){let id=Number($(this).data('id')),notes=$.trim($('#close-notes').val());if(notes.length<5){alert_toast('Indique una observación de al menos 5 caracteres.','warning');return;}let btn=$(this).prop('disabled',true).html('<i class="fas fa-spinner fa-spin mr-1"></i>Cerrando...');gradePost('close_year',{academic_year_id:id,notes:notes}).done(function(r){if(Number(r.status)===1){alert_toast(r.message,'success');setTimeout(()=>location.reload(),650);}else{alert_toast(r.message||'No se pudo cerrar el año.','danger');btn.prop('disabled',false).html('<i class="fas fa-lock mr-1"></i>Cerrar año académico');}}).fail(function(x){alert_toast((x.responseJSON||{}).message||'No se pudo cerrar el año.','danger');btn.prop('disabled',false).html('<i class="fas fa-lock mr-1"></i>Cerrar año académico');});});
$(document).on('click','.summary-year',function(){let id=$(this).closest('tr').data('id');$.getJSON('ajax.php?action=get_year_summary',{id:id}).done(function(r){let html='<div class="row">';Object.entries(r.summary||{}).forEach(x=>html+='<div class="col-md-4 mb-2"><div class="ay-stat"><small>'+esc(x[0])+'</small><br><strong>'+esc(x[1])+'</strong></div></div>');html+='</div>';$('#info-title').text('Resumen '+r.year.year);$('#info-body').html(html);$('#info-modal').modal('show');});});
$('#open-audit').on('click',function(){$.getJSON('ajax.php?action=get_academic_year_audit').done(function(r){let html='<div class="audit-list list-group">';(r.audit||[]).forEach(x=>html+='<div class="list-group-item"><strong>'+esc(x.action)+'</strong><span class="float-right small">'+esc(x.created_at)+'</span><div class="small text-muted">'+esc(x.user_name)+'</div></div>');$('#info-title').text('Auditoría de años académicos');$('#info-body').html(html||'Sin movimientos');$('#info-modal').modal('show');});});
$('#open-compare').on('click',function(){let opts=years.map(x=>'<option value="'+x.id+'">'+esc(x.year)+'</option>').join('');$('#info-title').text('Comparar años');$('#info-body').html('<div class="form-row"><div class="col"><select id="compare-a" class="form-control">'+opts+'</select></div><div class="col"><select id="compare-b" class="form-control">'+opts+'</select></div><div class="col-auto"><button id="run-compare" class="btn btn-info">Comparar</button></div></div><div id="compare-result" class="mt-3"></div>');$('#info-modal').modal('show');});
$(document).on('click','#run-compare',function(){let a=$('#compare-a').val(),b=$('#compare-b').val();$.getJSON('ajax.php?action=compare_academic_years',{year_a:a,year_b:b}).done(function(r){let keys=[...new Set(Object.keys(r.a.summary).concat(Object.keys(r.b.summary)))],html='<div class="text-right mb-2"><a class="btn btn-sm btn-outline-success" href="export_academic_year_comparison.php?year_a='+a+'&year_b='+b+'"><i class="fa fa-file-excel mr-1"></i>Exportar CSV</a></div><table class="table"><thead><tr><th>Indicador</th><th>'+esc(r.a.year.year)+'</th><th>'+esc(r.b.year.year)+'</th></tr></thead><tbody>';keys.forEach(k=>html+='<tr><td>'+esc(k)+'</td><td>'+esc(r.a.summary[k]||0)+'</td><td>'+esc(r.b.summary[k]||0)+'</td></tr>');$('#compare-result').html(html+'</tbody></table>');});});
try{$('#years-table').DataTable({order:[],columnDefs:[{orderable:false,targets:[4]}],language:{search:'Buscar:',lengthMenu:'Mostrar _MENU_',info:'_START_–_END_ de _TOTAL_',paginate:{previous:'Anterior',next:'Siguiente'}}});}catch(e){}
loadGradeControl();
})();
</script>
