<?php
ob_start();
date_default_timezone_set('America/Lima');
include_once __DIR__.'/includes/session_check.php';
require_login_modal();
include __DIR__.'/db_connect.php';
$conn->query("SET time_zone = '-05:00'");
header('Content-Type: application/json; charset=utf-8');
function ao($data,$code=200){if(ob_get_length())ob_clean();http_response_code($code);echo json_encode($data,JSON_UNESCAPED_UNICODE);exit;}
function atable($db,$name){$safe=$db->real_escape_string($name);$q=$db->query("SHOW TABLES LIKE '$safe'");return $q&&$q->num_rows>0;}
function acol($db,$table,$column){$t=$db->real_escape_string($table);$c=$db->real_escape_string($column);$q=$db->query("SHOW COLUMNS FROM `$t` LIKE '$c'");return $q&&$q->num_rows>0;}
function auditAttendance($db,$school,$attendance,$student,$action,$details=[]){$user=(int)($_SESSION['login_id']??0);$ip=$_SERVER['REMOTE_ADDR']??null;$json=json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$s=$db->prepare('INSERT INTO attendance_audit_log(school_id,attendance_id,student_id,user_id,action,details,ip_address) VALUES(?,NULLIF(?,0),NULLIF(?,0),NULLIF(?,0),?,?,?)');if($s){$s->bind_param('iiiisss',$school,$attendance,$student,$user,$action,$json,$ip);$s->execute();$s->close();}}
function activeYear($db,$school,$date){$s=$db->prepare('SELECT id,year FROM academic_year WHERE school_id=? AND ? BETWEEN start_date AND end_date ORDER BY is_active DESC,id DESC LIMIT 1');$s->bind_param('is',$school,$date);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return $r?:null;}
function createAttendanceRequest($db,$school,$attendance,$user,$type,$payload,$reason=''){$json=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if($attendance>0){$duplicate=$db->prepare("SELECT id FROM attendance_change_requests WHERE school_id=? AND attendance_id=? AND requested_by=? AND request_type=? AND status='Pendiente' LIMIT 1");$duplicate->bind_param('iiis',$school,$attendance,$user,$type);$duplicate->execute();$row=$duplicate->get_result()->fetch_assoc();$duplicate->close();if($row)return (int)$row['id'];}$s=$db->prepare("INSERT INTO attendance_change_requests(school_id,attendance_id,requested_by,request_type,request_payload,reason,status) VALUES(?,NULLIF(?,0),?,?,?,?, 'Pendiente')");$s->bind_param('iiisss',$school,$attendance,$user,$type,$json,$reason);if(!$s->execute())throw new Exception($s->error);$id=(int)$s->insert_id;$s->close();return $id;}
$school=(int)($_SESSION['login_school_id']??0);$user=(int)($_SESSION['login_id']??0);$type=(int)($_SESSION['login_type']??0);$director=(int)($_SESSION['login_is_director']??0);$action=$_GET['action']??'meta';
$roleStmt=$conn->prepare('SELECT type,is_director FROM users WHERE id=? AND school_id=? LIMIT 1');if($roleStmt){$roleStmt->bind_param('ii',$user,$school);$roleStmt->execute();$dbRole=$roleStmt->get_result()->fetch_assoc();$roleStmt->close();if($dbRole){$type=(int)$dbRole['type'];$director=(int)$dbRole['is_director'];}}
$isApprover=$type===1;$isAuxiliary=$type===3;
if(!$school||!$user||(!$isApprover&&!$isAuxiliary))ao(['status'=>0,'message'=>'No tiene permisos para gestionar asistencia.'],403);
$ready=acol($conn,'asistencia','school_id')&&atable($conn,'attendance_day_closures')&&atable($conn,'attendance_audit_log')&&atable($conn,'attendance_change_requests');
if(!$ready)ao(['status'=>0,'migration_required'=>true,'message'=>'Ejecute manualmente sql/attendance_module_upgrade.sql.'],409);
$writes=['save_roster','scan','save_single','close_day','reopen_day','justify','cancel','save_rules','save_calendar','delete_calendar','review_request'];
if(in_array($action,$writes,true)){if(!hash_equals((string)($_SESSION['csrf_token']??''),(string)($_POST['csrf_token']??'')))ao(['status'=>0,'message'=>'La sesión de seguridad venció. Recargue la página.'],403);}
if(in_array($action,['save_rules','save_calendar','delete_calendar'],true)&&!$isApprover)ao(['status'=>0,'message'=>'Solo administración puede modificar las reglas de asistencia.'],403);
if($action==='meta'){
 $years=[];$q=$conn->query("SELECT id,year,is_active FROM academic_year WHERE school_id=$school ORDER BY year DESC");while($q&&($r=$q->fetch_assoc()))$years[]=$r;
 $levels=[];$q=$conn->query("SELECT DISTINCT nivel FROM student WHERE school_id=$school AND status='Activo' AND nivel<>'' ORDER BY FIELD(nivel,'Inicial','Primaria','Secundaria'),nivel");while($q&&($r=$q->fetch_assoc()))$levels[]=$r['nivel'];
 $settings=[];$q=$conn->query("SELECT setting_key,setting_value FROM attendance_settings WHERE school_id=$school OR school_id IS NULL ORDER BY school_id DESC");while($q&&($r=$q->fetch_assoc()))if(!isset($settings[$r['setting_key']]))$settings[$r['setting_key']]=$r['setting_value'];
 ao(['status'=>1,'years'=>$years,'levels'=>$levels,'settings'=>$settings]);
}
if($action==='class_options'){
 $level=trim($_GET['nivel']??'');$grade=trim($_GET['grado']??'');$data=[];
 if($level===''){$sql="SELECT DISTINCT nivel value FROM student WHERE school_id=? AND status='Activo' AND nivel<>'' ORDER BY FIELD(nivel,'Inicial','Primaria','Secundaria'),nivel";$s=$conn->prepare($sql);$s->bind_param('i',$school);}
 elseif($grade===''){$sql="SELECT DISTINCT grado value FROM student WHERE school_id=? AND status='Activo' AND nivel=? AND grado<>'' ORDER BY grado";$s=$conn->prepare($sql);$s->bind_param('is',$school,$level);}
 else{$sql="SELECT DISTINCT seccion value FROM student WHERE school_id=? AND status='Activo' AND nivel=? AND grado=? AND seccion<>'' ORDER BY seccion";$s=$conn->prepare($sql);$s->bind_param('iss',$school,$level,$grade);}
 $s->execute();$q=$s->get_result();while($r=$q->fetch_assoc())$data[]=$r['value'];$s->close();ao(['status'=>1,'data'=>$data]);
}
if($action==='roster'){
 $date=trim($_GET['date']??date('Y-m-d'));$level=trim($_GET['nivel']??'');$grade=trim($_GET['grado']??'');$section=trim($_GET['seccion']??'');
 if(!$level||!$grade||!$section)ao(['status'=>0,'message'=>'Seleccione nivel, grado y sección.']);
 $holiday=null;$h=$conn->prepare('SELECT name,day_type FROM attendance_calendar WHERE school_id=? AND calendar_date=? LIMIT 1');$h->bind_param('is',$school,$date);$h->execute();$holiday=$h->get_result()->fetch_assoc();$h->close();
 $closed=false;$c=$conn->prepare("SELECT id FROM attendance_day_closures WHERE school_id=? AND attendance_date=? AND nivel=? AND grado=? AND seccion=? AND status='Cerrada' LIMIT 1");$c->bind_param('issss',$school,$date,$level,$grade,$section);$c->execute();$closed=(bool)$c->get_result()->fetch_assoc();$c->close();
 $s=$conn->prepare("SELECT st.id,st.id_no,st.name,st.nivel,st.grado,st.seccion,a.id attendance_id,a.hora,a.estado,a.source,a.notes,a.justification_status,a.justification_reason FROM student st LEFT JOIN asistencia a ON a.student_id=st.id AND a.school_id=? AND a.fecha=? AND a.tipo='Entrada' AND a.is_cancelled=0 WHERE st.school_id=? AND st.status='Activo' AND st.nivel=? AND st.grado=? AND st.seccion=? ORDER BY st.name");
 $s->bind_param('isisss',$school,$date,$school,$level,$grade,$section);$s->execute();$q=$s->get_result();$rows=[];$summary=['expected'=>0,'present'=>0,'late'=>0,'absent'=>0,'justified'=>0,'unmarked'=>0];while($r=$q->fetch_assoc()){$e=(string)($r['estado']??'');if(in_array($e,['Normal','Temprano'],true)){$e='Presente';$r['estado']=$e;}$rows[]=$r;$summary['expected']++;if($e==='')$summary['unmarked']++;elseif($e==='Tarde')$summary['late']++;elseif(stripos($e,'Ausente Justificada')===0)$summary['justified']++;elseif(stripos($e,'Ausente')===0)$summary['absent']++;else$summary['present']++;}$s->close();ao(['status'=>1,'rows'=>$rows,'summary'=>$summary,'closed'=>$closed,'holiday'=>$holiday]);
}
if($action==='save_roster'&&$isAuxiliary){
 $date=trim($_POST['date']??'');$level=trim($_POST['nivel']??'');$grade=trim($_POST['grado']??'');$section=trim($_POST['seccion']??'');$rows=json_decode($_POST['rows']??'[]',true);
 if(!$date||!$level||!$grade||!$section||!is_array($rows))ao(['status'=>0,'message'=>'La nómina enviada no es válida.']);
 $cl=$conn->prepare("SELECT id FROM attendance_day_closures WHERE school_id=? AND attendance_date=? AND nivel=? AND grado=? AND seccion=? AND status='Cerrada'");$cl->bind_param('issss',$school,$date,$level,$grade,$section);$cl->execute();if($cl->get_result()->fetch_assoc())ao(['status'=>0,'message'=>'La asistencia de esta aula ya está cerrada.']);$cl->close();
 $year=activeYear($conn,$school,$date);$yearId=(int)($year['id']??0);$created=0;$requested=0;$unchanged=0;$changeItems=[];
 $conn->begin_transaction();
 try{
  foreach($rows as $row){
   $student=(int)($row['student_id']??0);$status=trim($row['status']??'');$time=trim($row['time']??'');$notes=trim($row['notes']??'');
   if(!$student||$status==='')continue;
   if(!in_array($status,['Presente','Tarde','Ausente','Ausente Justificada','Permiso'],true))throw new Exception('Se recibió un estado inválido.');
   $valid=$conn->prepare("SELECT id,name,id_no FROM student WHERE id=? AND school_id=? AND status='Activo' AND nivel=? AND grado=? AND seccion=?");$valid->bind_param('iisss',$student,$school,$level,$grade,$section);$valid->execute();$ok=$valid->get_result()->fetch_assoc();$valid->close();if(!$ok)continue;
   if(in_array($status,['Ausente','Ausente Justificada','Permiso'],true))$time='00:00:00';elseif(!$time)$time=date('H:i:s');
   $existing=$conn->prepare("SELECT id,hora,estado,notes,justification_status FROM asistencia WHERE student_id=? AND school_id=? AND fecha=? AND tipo='Entrada' AND is_cancelled=0 LIMIT 1 FOR UPDATE");$existing->bind_param('iis',$student,$school,$date);$existing->execute();$record=$existing->get_result()->fetch_assoc();$existing->close();$just=$status==='Ausente Justificada'?'Aprobada':null;
   if($record){
    $currentState=in_array($record['estado'],['Normal','Temprano'],true)?'Presente':$record['estado'];
    $changed=$currentState!==$status||substr((string)$record['hora'],0,8)!==substr($time,0,8)||(string)($record['notes']??'')!==$notes;
    if(!$changed){$unchanged++;continue;}
    $changeItems[]=['attendance_id'=>(int)$record['id'],'student_id'=>$student,'student_name'=>$ok['name'],'student_code'=>$ok['id_no'],'previous'=>['status'=>$currentState,'time'=>$record['hora'],'notes'=>$record['notes']],'requested'=>['status'=>$status,'time'=>$time,'notes'=>$notes,'justification_status'=>$just]];
   }else{
    $i=$conn->prepare("INSERT INTO asistencia(school_id,academic_year_id,student_id,fecha,tipo,hora,estado,source,notes,justification_status,created_by,updated_by) VALUES(?,NULLIF(?,0),?,?,'Entrada',?,?,'Aula',?,?,?,?)");$i->bind_param('iiisssssii',$school,$yearId,$student,$date,$time,$status,$notes,$just,$user,$user);if(!$i->execute())throw new Exception($i->error);$id=(int)$i->insert_id;$i->close();auditAttendance($conn,$school,$id,$student,'attendance_created',['status'=>$status,'date'=>$date]);$created++;
   }
  }
  if($changeItems){$requested=count($changeItems);$requestId=createAttendanceRequest($conn,$school,0,$user,'Editar nómina',['date'=>$date,'nivel'=>$level,'grado'=>$grade,'seccion'=>$section,'changes'=>$changeItems],"$requested cambios solicitados desde la nómina");foreach($changeItems as $item)auditAttendance($conn,$school,(int)$item['attendance_id'],(int)$item['student_id'],'attendance_change_requested',['request_id'=>$requestId,'status'=>$item['requested']['status'],'time'=>$item['requested']['time']]);}
  $conn->commit();$message="$created registros nuevos guardados.".($requested?" Una solicitud con $requested cambios fue enviada para autorización.":'').($unchanged?" $unchanged sin cambios.":'');ao(['status'=>1,'message'=>$message,'saved'=>$created,'requested'=>$requested]);
 }catch(Throwable $e){$conn->rollback();ao(['status'=>0,'message'=>$e->getMessage()]);}
}
if($action==='save_roster'){
 $date=trim($_POST['date']??'');$level=trim($_POST['nivel']??'');$grade=trim($_POST['grado']??'');$section=trim($_POST['seccion']??'');$rows=json_decode($_POST['rows']??'[]',true);if(!$date||!$level||!$grade||!$section||!is_array($rows))ao(['status'=>0,'message'=>'La nómina enviada no es válida.']);
 $cl=$conn->prepare("SELECT id FROM attendance_day_closures WHERE school_id=? AND attendance_date=? AND nivel=? AND grado=? AND seccion=? AND status='Cerrada'");$cl->bind_param('issss',$school,$date,$level,$grade,$section);$cl->execute();if($cl->get_result()->fetch_assoc())ao(['status'=>0,'message'=>'La asistencia de esta aula ya está cerrada.']);$cl->close();$year=activeYear($conn,$school,$date);$yearId=(int)($year['id']??0);$saved=0;
 $conn->begin_transaction();try{foreach($rows as $row){$student=(int)($row['student_id']??0);$status=trim($row['status']??'');$time=trim($row['time']??'');$notes=trim($row['notes']??'');if(!$student||$status==='')continue;if(!in_array($status,['Presente','Tarde','Ausente','Ausente Justificada','Permiso'],true))throw new Exception('Se recibió un estado inválido.');$valid=$conn->prepare("SELECT id FROM student WHERE id=? AND school_id=? AND status='Activo' AND nivel=? AND grado=? AND seccion=?");$valid->bind_param('iisss',$student,$school,$level,$grade,$section);$valid->execute();$ok=$valid->get_result()->fetch_assoc();$valid->close();if(!$ok)continue;if(in_array($status,['Ausente','Ausente Justificada','Permiso'],true))$time='00:00:00';elseif(!$time)$time=date('H:i:s');$existing=$conn->prepare("SELECT id FROM asistencia WHERE student_id=? AND school_id=? AND fecha=? AND tipo='Entrada' AND is_cancelled=0 LIMIT 1 FOR UPDATE");$existing->bind_param('iis',$student,$school,$date);$existing->execute();$record=$existing->get_result()->fetch_assoc();$existing->close();$just=$status==='Ausente Justificada'?'Aprobada':null;if($record){$id=(int)$record['id'];$u=$conn->prepare("UPDATE asistencia SET academic_year_id=NULLIF(?,0),hora=?,estado=?,source='Aula',notes=?,justification_status=?,updated_by=? WHERE id=? AND school_id=?");$u->bind_param('issssiii',$yearId,$time,$status,$notes,$just,$user,$id,$school);if(!$u->execute())throw new Exception($u->error);$u->close();auditAttendance($conn,$school,$id,$student,'attendance_updated',['status'=>$status,'date'=>$date]);}else{$i=$conn->prepare("INSERT INTO asistencia(school_id,academic_year_id,student_id,fecha,tipo,hora,estado,source,notes,justification_status,created_by,updated_by) VALUES(?,NULLIF(?,0),?,?,'Entrada',?,?,'Aula',?,?,?,?)");$i->bind_param('iiisssssii',$school,$yearId,$student,$date,$time,$status,$notes,$just,$user,$user);if(!$i->execute())throw new Exception($i->error);$id=(int)$i->insert_id;$i->close();auditAttendance($conn,$school,$id,$student,'attendance_created',['status'=>$status,'date'=>$date]);}$saved++;}$conn->commit();ao(['status'=>1,'message'=>"Se guardaron $saved registros de asistencia.",'saved'=>$saved]);}catch(Throwable $e){$conn->rollback();ao(['status'=>0,'message'=>$e->getMessage()]);}
}
if($action==='scan'){
 $dni=trim($_POST['dni']??'');$date=trim($_POST['date']??date('Y-m-d'));$kind=($_POST['tipo']??'Entrada')==='Salida'?'Salida':'Entrada';$time=date('H:i:s');$s=$conn->prepare("SELECT id,name FROM student WHERE school_id=? AND id_no=? AND status='Activo' LIMIT 1");$s->bind_param('is',$school,$dni);$s->execute();$student=$s->get_result()->fetch_assoc();$s->close();if(!$student)ao(['status'=>0,'message'=>'No se encontró un estudiante activo con ese DNI.']);$sid=(int)$student['id'];$dup=$conn->prepare('SELECT id FROM asistencia WHERE school_id=? AND student_id=? AND fecha=? AND tipo=? AND is_cancelled=0 LIMIT 1');$dup->bind_param('iiss',$school,$sid,$date,$kind);$dup->execute();if($dup->get_result()->fetch_assoc())ao(['status'=>0,'message'=>"Ya existe una marcación de $kind para este estudiante."]);$dup->close();require_once __DIR__.'/attendance_state_helper.php';$status=calcular_estado_asistencia($time,$date,$kind,$conn,$school);$year=activeYear($conn,$school,$date);$yearId=(int)($year['id']??0);$i=$conn->prepare("INSERT INTO asistencia(school_id,academic_year_id,student_id,fecha,tipo,hora,estado,source,created_by,updated_by) VALUES(?,NULLIF(?,0),?,?,?,?,?,'Escáner',?,?)");$i->bind_param('iiissssii',$school,$yearId,$sid,$date,$kind,$time,$status,$user,$user);if(!$i->execute())ao(['status'=>0,'message'=>$i->error]);$id=(int)$i->insert_id;$i->close();auditAttendance($conn,$school,$id,$sid,'attendance_scanned',['type'=>$kind,'status'=>$status]);ao(['status'=>1,'message'=>$student['name'].': '.$kind.' registrada ('.$status.').']);
}
if($action==='reopen_day'&&$isAuxiliary){
 $date=trim($_POST['date']??'');$level=trim($_POST['nivel']??'');$grade=trim($_POST['grado']??'');$section=trim($_POST['seccion']??'');$reason=trim($_POST['reason']??'');
 if(!$date||!$level||!$grade||!$section||strlen($reason)<3)ao(['status'=>0,'message'=>'Seleccione el aula e indique el motivo de reapertura.']);
 $c=$conn->prepare("SELECT id FROM attendance_day_closures WHERE school_id=? AND attendance_date=? AND nivel=? AND grado=? AND seccion=? AND status='Cerrada' LIMIT 1");$c->bind_param('issss',$school,$date,$level,$grade,$section);$c->execute();$closure=$c->get_result()->fetch_assoc();$c->close();if(!$closure)ao(['status'=>0,'message'=>'La asistencia no está cerrada.']);
 $requestId=createAttendanceRequest($conn,$school,0,$user,'Reabrir día',['closure_id'=>(int)$closure['id'],'date'=>$date,'nivel'=>$level,'grado'=>$grade,'seccion'=>$section],$reason);auditAttendance($conn,$school,0,0,'attendance_reopen_requested',['request_id'=>$requestId,'date'=>$date]);ao(['status'=>1,'approval_pending'=>true,'message'=>'Solicitud de reapertura enviada al administrador.']);
}
if($action==='close_day'||$action==='reopen_day'){
 $date=trim($_POST['date']??'');$level=trim($_POST['nivel']??'');$grade=trim($_POST['grado']??'');$section=trim($_POST['seccion']??'');if(!$date||!$level||!$grade||!$section)ao(['status'=>0,'message'=>'Seleccione el aula y la fecha.']);
 if($action==='close_day'){$missing=(int)$conn->query("SELECT COUNT(*) n FROM student st LEFT JOIN asistencia a ON a.student_id=st.id AND a.school_id=$school AND a.fecha='".$conn->real_escape_string($date)."' AND a.tipo='Entrada' AND a.is_cancelled=0 WHERE st.school_id=$school AND st.status='Activo' AND st.nivel='".$conn->real_escape_string($level)."' AND st.grado='".$conn->real_escape_string($grade)."' AND st.seccion='".$conn->real_escape_string($section)."' AND a.id IS NULL")->fetch_assoc()['n'];if($missing)ao(['status'=>0,'message'=>"Faltan $missing estudiantes por marcar."]);$year=activeYear($conn,$school,$date);$yearId=(int)($year['id']??0);$s=$conn->prepare("INSERT INTO attendance_day_closures(school_id,academic_year_id,attendance_date,nivel,grado,seccion,status,closed_at,closed_by) VALUES(?,NULLIF(?,0),?,?,?,?,'Cerrada',NOW(),?) ON DUPLICATE KEY UPDATE status='Cerrada',closed_at=NOW(),closed_by=VALUES(closed_by),reopened_at=NULL,reopened_by=NULL,reopen_reason=NULL");$s->bind_param('iissssi',$school,$yearId,$date,$level,$grade,$section,$user);$s->execute();$s->close();ao(['status'=>1,'message'=>'Asistencia cerrada correctamente.']);}
 $reason=trim($_POST['reason']??'');if(strlen($reason)<3)ao(['status'=>0,'message'=>'Indique el motivo de reapertura.']);$s=$conn->prepare("UPDATE attendance_day_closures SET status='Reabierta',reopened_at=NOW(),reopened_by=?,reopen_reason=? WHERE school_id=? AND attendance_date=? AND nivel=? AND grado=? AND seccion=? AND status='Cerrada'");$s->bind_param('isissss',$user,$reason,$school,$date,$level,$grade,$section);$s->execute();$changed=$s->affected_rows;$s->close();ao(['status'=>$changed?1:0,'message'=>$changed?'Asistencia reabierta.':'La asistencia no estaba cerrada.']);
}
if($action==='justify'&&$isAuxiliary){$id=(int)($_POST['id']??0);$status=trim($_POST['status']??'Pendiente');$reason=trim($_POST['reason']??'');if(!$id||!in_array($status,['Pendiente','Aprobada','Rechazada'],true)||strlen($reason)<3)ao(['status'=>0,'message'=>'Complete la justificación.']);$newState=$status==='Aprobada'?'Ausente Justificada':'Ausente';$requestId=createAttendanceRequest($conn,$school,$id,$user,'Justificar ausencia',['attendance_id'=>$id,'status'=>$status,'new_state'=>$newState],$reason);auditAttendance($conn,$school,$id,0,'attendance_justification_requested',['request_id'=>$requestId,'status'=>$status]);ao(['status'=>1,'approval_pending'=>true,'message'=>'Justificación enviada para autorización.']);}
if($action==='justify'){$id=(int)($_POST['id']??0);$status=trim($_POST['status']??'Pendiente');$reason=trim($_POST['reason']??'');if(!$id||!in_array($status,['Pendiente','Aprobada','Rechazada'],true)||strlen($reason)<3)ao(['status'=>0,'message'=>'Complete la justificación.']);$newState=$status==='Aprobada'?'Ausente Justificada':'Ausente';$s=$conn->prepare('UPDATE asistencia SET estado=?,justification_status=?,justification_reason=?,justified_at=NOW(),justified_by=?,updated_by=? WHERE id=? AND school_id=? AND is_cancelled=0');$s->bind_param('sssiiii',$newState,$status,$reason,$user,$user,$id,$school);$s->execute();$changed=$s->affected_rows;$s->close();auditAttendance($conn,$school,$id,0,'attendance_justified',['status'=>$status,'reason'=>$reason]);ao(['status'=>$changed?1:0,'message'=>$changed?'Justificación actualizada.':'No se encontró el registro.']);}
if($action==='cancel'&&$isAuxiliary){$id=(int)($_POST['id']??0);$reason=trim($_POST['reason']??'');if(!$id||strlen($reason)<3)ao(['status'=>0,'message'=>'Indique el motivo de anulación.']);$requestId=createAttendanceRequest($conn,$school,$id,$user,'Anular registro',['attendance_id'=>$id],$reason);auditAttendance($conn,$school,$id,0,'attendance_cancellation_requested',['request_id'=>$requestId]);ao(['status'=>1,'approval_pending'=>true,'message'=>'Anulación enviada para autorización.']);}
if($action==='cancel'){$id=(int)($_POST['id']??0);$reason=trim($_POST['reason']??'');if(!$id||strlen($reason)<3)ao(['status'=>0,'message'=>'Indique el motivo de anulación.']);$s=$conn->prepare('UPDATE asistencia SET is_cancelled=1,cancelled_at=NOW(),cancelled_by=?,cancellation_reason=?,updated_by=? WHERE id=? AND school_id=? AND is_cancelled=0');$s->bind_param('isiii',$user,$reason,$user,$id,$school);$s->execute();$changed=$s->affected_rows;$s->close();auditAttendance($conn,$school,$id,0,'attendance_cancelled',['reason'=>$reason]);ao(['status'=>$changed?1:0,'message'=>$changed?'Marcación anulada.':'No se encontró la marcación.']);}
if($action==='requests'){
 if(!$isApprover)ao(['status'=>0,'message'=>'Solo administración puede revisar solicitudes.'],403);
 $rows=[];$s=$conn->prepare("SELECT r.id,r.attendance_id,r.request_type,r.request_payload,r.reason,r.status,r.created_at,u.name requester,st.name student_name FROM attendance_change_requests r INNER JOIN users u ON u.id=r.requested_by LEFT JOIN asistencia a ON a.id=r.attendance_id LEFT JOIN student st ON st.id=a.student_id WHERE r.school_id=? AND r.status='Pendiente' ORDER BY r.created_at ASC LIMIT 100");$s->bind_param('i',$school);$s->execute();$q=$s->get_result();while($r=$q->fetch_assoc()){$r['payload']=json_decode($r['request_payload'],true)?:[];unset($r['request_payload']);$rows[]=$r;}$s->close();ao(['status'=>1,'rows'=>$rows]);
}
if($action==='review_request'){
 if(!$isApprover)ao(['status'=>0,'message'=>'Solo administración puede autorizar solicitudes.'],403);
 $id=(int)($_POST['id']??0);$decision=trim($_POST['decision']??'');$notes=trim($_POST['notes']??'');if(!$id||!in_array($decision,['Aprobada','Rechazada'],true))ao(['status'=>0,'message'=>'La decisión no es válida.']);
 $conn->begin_transaction();try{$s=$conn->prepare("SELECT * FROM attendance_change_requests WHERE id=? AND school_id=? AND status='Pendiente' LIMIT 1 FOR UPDATE");$s->bind_param('ii',$id,$school);$s->execute();$request=$s->get_result()->fetch_assoc();$s->close();if(!$request)throw new Exception('La solicitud ya fue revisada o no existe.');$payload=json_decode($request['request_payload'],true)?:[];$attendance=(int)($request['attendance_id']??0);
  if($decision==='Aprobada'){
   if($request['request_type']==='Editar nómina'){foreach(($payload['changes']??[]) as $change){$attendanceId=(int)($change['attendance_id']??0);$wanted=$change['requested']??[];$status=trim($wanted['status']??'');$time=trim($wanted['time']??'00:00:00');$recordNotes=trim($wanted['notes']??'');$just=$wanted['justification_status']??null;if(!$attendanceId||!in_array($status,['Presente','Tarde','Ausente','Ausente Justificada','Permiso'],true))throw new Exception('La solicitud contiene un cambio inválido.');$u=$conn->prepare("UPDATE asistencia SET hora=?,estado=?,notes=?,justification_status=?,updated_by=? WHERE id=? AND school_id=? AND is_cancelled=0");$u->bind_param('ssssiii',$time,$status,$recordNotes,$just,$user,$attendanceId,$school);if(!$u->execute())throw new Exception($u->error);$u->close();auditAttendance($conn,$school,$attendanceId,(int)($change['student_id']??0),'attendance_batch_change_applied',['request_id'=>$id,'status'=>$status,'time'=>$time]);}}
   elseif($request['request_type']==='Editar registro'){$wanted=$payload['requested']??[];$status=trim($wanted['status']??'');$time=trim($wanted['time']??'00:00:00');$recordNotes=trim($wanted['notes']??'');$just=$wanted['justification_status']??null;$u=$conn->prepare("UPDATE asistencia SET hora=?,estado=?,notes=?,justification_status=?,updated_by=? WHERE id=? AND school_id=? AND is_cancelled=0");$u->bind_param('ssssiii',$time,$status,$recordNotes,$just,$user,$attendance,$school);if(!$u->execute())throw new Exception($u->error);$u->close();}
   elseif($request['request_type']==='Reabrir día'){$closure=(int)($payload['closure_id']??0);$reason=$request['reason'];$u=$conn->prepare("UPDATE attendance_day_closures SET status='Reabierta',reopened_at=NOW(),reopened_by=?,reopen_reason=? WHERE id=? AND school_id=? AND status='Cerrada'");$u->bind_param('isii',$user,$reason,$closure,$school);if(!$u->execute())throw new Exception($u->error);$u->close();}
   elseif($request['request_type']==='Justificar ausencia'){$status=$payload['status']??'Pendiente';$state=$payload['new_state']??'Ausente';$reason=$request['reason'];$u=$conn->prepare('UPDATE asistencia SET estado=?,justification_status=?,justification_reason=?,justified_at=NOW(),justified_by=?,updated_by=? WHERE id=? AND school_id=? AND is_cancelled=0');$u->bind_param('sssiiii',$state,$status,$reason,$user,$user,$attendance,$school);if(!$u->execute())throw new Exception($u->error);$u->close();}
   elseif($request['request_type']==='Anular registro'){$reason=$request['reason'];$u=$conn->prepare('UPDATE asistencia SET is_cancelled=1,cancelled_at=NOW(),cancelled_by=?,cancellation_reason=?,updated_by=? WHERE id=? AND school_id=? AND is_cancelled=0');$u->bind_param('isiii',$user,$reason,$user,$attendance,$school);if(!$u->execute())throw new Exception($u->error);$u->close();}
  }
  $u=$conn->prepare('UPDATE attendance_change_requests SET status=?,reviewed_by=?,reviewed_at=NOW(),review_notes=? WHERE id=? AND school_id=?');$u->bind_param('sisii',$decision,$user,$notes,$id,$school);if(!$u->execute())throw new Exception($u->error);$u->close();auditAttendance($conn,$school,$attendance,0,$decision==='Aprobada'?'attendance_request_approved':'attendance_request_rejected',['request_id'=>$id,'type'=>$request['request_type'],'notes'=>$notes]);
  if(atable($conn,'notification_events')){$recipient=(int)$request['requested_by'];$eventType='Resultado de asistencia';$priority=$decision==='Aprobada'?'Normal':'Alta';$title=$decision==='Aprobada'?'Solicitud de asistencia aprobada':'Solicitud de asistencia rechazada';$message=$request['request_type'].($notes!==''?' · '.$notes:'');$sourceType='attendance_request_result';$event=$conn->prepare('INSERT INTO notification_events(school_id,recipient_user_id,notification_type,priority,title,message,source_type,source_id,created_by) VALUES(?,?,?,?,?,?,?,?,?)');$event->bind_param('iisssssii',$school,$recipient,$eventType,$priority,$title,$message,$sourceType,$id,$user);if(!$event->execute())throw new Exception($event->error);$event->close();}
  if(atable($conn,'notification_user_state')){$notificationKey='attendance_request:'.$id;$state=$conn->prepare('INSERT INTO notification_user_state(school_id,user_id,notification_key,is_read,read_at) VALUES(?,?,?,1,NOW()) ON DUPLICATE KEY UPDATE is_read=1,read_at=NOW()');$state->bind_param('iis',$school,$user,$notificationKey);if(!$state->execute())throw new Exception($state->error);$state->close();}
  $conn->commit();ao(['status'=>1,'message'=>$decision==='Aprobada'?'Solicitud aprobada y aplicada.':'Solicitud rechazada.']);
 }catch(Throwable $e){$conn->rollback();ao(['status'=>0,'message'=>$e->getMessage()]);}
}
if($action==='rules'){
 $rules=[];$q=$conn->query("SELECT * FROM attendance_rules WHERE school_id=$school OR school_id IS NULL ORDER BY FIELD(day_of_week,'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'),school_id DESC");
 if(!$q)ao(['status'=>0,'message'=>'No se pudieron consultar las reglas. Detalle: '.$conn->error],500);
 $seen=[];while($r=$q->fetch_assoc())if(!isset($seen[$r['day_of_week']])){$seen[$r['day_of_week']]=1;$rules[]=$r;}
 $calendar=[];$q=$conn->query("SELECT * FROM attendance_calendar WHERE school_id=$school ORDER BY calendar_date DESC LIMIT 100");
 if(!$q)ao(['status'=>0,'message'=>'No se pudo consultar el calendario. Detalle: '.$conn->error],500);
 while($r=$q->fetch_assoc())$calendar[]=$r;ao(['status'=>1,'rules'=>$rules,'calendar'=>$calendar]);
}
if($action==='save_rules'){$rows=json_decode($_POST['rules']??'[]',true);if(!is_array($rows))ao(['status'=>0,'message'=>'Las reglas no son válidas.']);$days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];$conn->begin_transaction();try{foreach($rows as $r){$day=$r['day']??'';if(!in_array($day,$days,true))continue;$active=!empty($r['active'])?1:0;$entry=$r['entry']??'07:30';$tol=max(0,min(180,(int)($r['tolerance']??0)));$exit=$r['exit']??'15:00';$earlyExit=$r['early_exit']??$exit;$late=date('H:i:s',strtotime($entry)+$tol*60);$entry.=':'.(strlen($entry)===5?'00':'');$exit.=':'.(strlen($exit)===5?'00':'');$earlyExit.=':'.(strlen($earlyExit)===5?'00':'');$name=['Monday'=>'Lunes','Tuesday'=>'Martes','Wednesday'=>'Miércoles','Thursday'=>'Jueves','Friday'=>'Viernes','Saturday'=>'Sábado','Sunday'=>'Domingo'][$day];$s=$conn->prepare("INSERT INTO attendance_rules(school_id,day_of_week,early_time,late_time,day_name_es,entry_time,tolerance_minutes,exit_time,early_exit_limit,is_active) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE early_time=VALUES(early_time),late_time=VALUES(late_time),day_name_es=VALUES(day_name_es),entry_time=VALUES(entry_time),tolerance_minutes=VALUES(tolerance_minutes),exit_time=VALUES(exit_time),early_exit_limit=VALUES(early_exit_limit),is_active=VALUES(is_active)");$s->bind_param('isssssissi',$school,$day,$entry,$late,$name,$entry,$tol,$exit,$earlyExit,$active);if(!$s->execute())throw new Exception($s->error);$s->close();}$conn->commit();ao(['status'=>1,'message'=>'Reglas guardadas correctamente.']);}catch(Throwable $e){$conn->rollback();ao(['status'=>0,'message'=>$e->getMessage()]);}}
if($action==='save_calendar'){$date=trim($_POST['date']??'');$name=trim($_POST['name']??'');$dayType=trim($_POST['day_type']??'No laborable');$notes=trim($_POST['notes']??'');if(!$date||!$name)ao(['status'=>0,'message'=>'Complete fecha y nombre.']);$year=activeYear($conn,$school,$date);$yearId=(int)($year['id']??0);$s=$conn->prepare('INSERT INTO attendance_calendar(school_id,academic_year_id,calendar_date,name,day_type,notes,created_by) VALUES(?,NULLIF(?,0),?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),day_type=VALUES(day_type),notes=VALUES(notes)');$s->bind_param('iissssi',$school,$yearId,$date,$name,$dayType,$notes,$user);$ok=$s->execute();$s->close();ao(['status'=>$ok?1:0,'message'=>$ok?'Calendario actualizado.':'No se pudo guardar.']);}
if($action==='delete_calendar'){$id=(int)($_POST['id']??0);$s=$conn->prepare('DELETE FROM attendance_calendar WHERE id=? AND school_id=?');$s->bind_param('ii',$id,$school);$s->execute();$n=$s->affected_rows;$s->close();ao(['status'=>$n?1:0,'message'=>$n?'Fecha eliminada.':'No se encontró la fecha.']);}
ao(['status'=>0,'message'=>'Acción no válida.'],404);
