<?php
date_default_timezone_set('America/Lima');
include_once __DIR__.'/includes/session_check.php';require_login_modal();include __DIR__.'/db_connect.php';
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$csrf=$_SESSION['csrf_token'];
$ready=false;$q=$conn->query("SHOW COLUMNS FROM attendance_rules LIKE 'entry_time'");if($q&&$q->num_rows){$q=$conn->query("SHOW TABLES LIKE 'attendance_calendar'");$ready=$q&&$q->num_rows>0;}
?>
<style>
.ar-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.ar-head h1{font-size:1.35rem;font-weight:700;color:#344054;margin:0}.ar-sub{font-size:.84rem;color:#667085}.ar-table th{font-size:.76rem;text-transform:uppercase;color:#475467;background:#f8fafc}.ar-table td{vertical-align:middle}.ar-help{background:#f5f8ff;border-left:4px solid #2f6fed;padding:11px 13px}.ar-calendar-row td{font-size:.9rem}@media(max-width:768px){.ar-head{display:block}.ar-head .btn{margin-top:10px}}
</style>
<div class="container-fluid py-4">
 <div class="ar-head"><div><h1><i class="fas fa-clock text-primary mr-2"></i>Reglas de asistencia</h1><div class="ar-sub">Defina horarios semanales y excepciones del calendario escolar.</div></div><a href="index.php?page=asistencia" class="btn btn-outline-primary btn-sm"><i class="fas fa-arrow-left mr-1"></i>Volver a asistencia</a></div>
 <?php if(!$ready):?><div class="alert alert-warning">Ejecute manualmente <code>sql/attendance_module_upgrade.sql</code> para habilitar esta configuración.</div><?php else:?>
 <div id="ar-message"></div><div class="ar-help mb-3"><strong>Cómo se calcula:</strong> hasta la hora oficial se considera puntual; después se usa la tolerancia y, superado ese límite, se registra tardanza.</div>
 <div class="card shadow-sm mb-4"><div class="card-header bg-white d-flex justify-content-between align-items-center"><div><strong>Horario semanal</strong><div class="small text-muted">Desactive los días sin clases regulares.</div></div><button id="save-rules" class="btn btn-primary btn-sm"><i class="fas fa-save mr-1"></i>Guardar reglas</button></div><div class="table-responsive"><table class="table ar-table mb-0"><thead><tr><th>Día</th><th class="text-center">Laborable</th><th>Entrada oficial</th><th>Tolerancia</th><th>Salida oficial</th><th>Salida anticipada antes de</th></tr></thead><tbody id="rules-body"><tr><td colspan="6" class="text-center py-4">Cargando reglas...</td></tr></tbody></table></div></div>
 <div class="row"><div class="col-lg-5 mb-4"><div class="card shadow-sm h-100"><div class="card-header bg-white"><strong>Agregar fecha especial</strong></div><div class="card-body"><form id="calendar-form"><div class="form-group"><label>Fecha</label><input id="cal-date" type="date" class="form-control" required></div><div class="form-group"><label>Nombre</label><input id="cal-name" class="form-control" maxlength="120" placeholder="Ej.: Día del maestro" required></div><div class="form-group"><label>Tipo</label><select id="cal-type" class="form-control"><option>No laborable</option><option>Horario especial</option><option>Actividad institucional</option></select></div><div class="form-group"><label>Observación</label><textarea id="cal-notes" class="form-control" maxlength="255"></textarea></div><button class="btn btn-primary"><i class="fas fa-plus mr-1"></i>Guardar fecha</button></form></div></div></div>
 <div class="col-lg-7 mb-4"><div class="card shadow-sm h-100"><div class="card-header bg-white"><strong>Calendario escolar</strong></div><div class="table-responsive"><table class="table mb-0"><thead class="thead-light"><tr><th>Fecha</th><th>Descripción</th><th>Tipo</th><th></th></tr></thead><tbody id="calendar-body"><tr><td colspan="4" class="text-center py-4">Sin fechas configuradas.</td></tr></tbody></table></div></div></div></div>
 <?php endif;?>
</div>
<?php if($ready):?><script>
(function($){const api='attendance_api.php',csrf=<?=json_encode($csrf)?>,dayNames={Monday:'Lunes',Tuesday:'Martes',Wednesday:'Miércoles',Thursday:'Jueves',Friday:'Viernes',Saturday:'Sábado',Sunday:'Domingo'},esc=v=>$('<div>').text(v==null?'':v).html(),post=(a,d)=>$.post(api+'?action='+a,$.extend({csrf_token:csrf},d||{}),null,'json');
function load(){
 $('#rules-body').html('<tr><td colspan="6" class="text-center py-4"><i class="fas fa-spinner fa-spin mr-2"></i>Cargando reglas...</td></tr>');
 $.ajax({url:api,data:{action:'rules'},dataType:'json',cache:false}).done(r=>{
  if(!r||Number(r.status)!==1){showLoadError((r&&r.message)||'No se pudieron consultar las reglas.');return}
  let h='';(r.rules||[]).forEach(x=>{let entry=(x.entry_time||x.early_time||'07:30').substring(0,5),exit=(x.exit_time||'15:00').substring(0,5),early=(x.early_exit_limit||exit).substring(0,5);h+='<tr data-day="'+x.day_of_week+'"><td><strong>'+esc(dayNames[x.day_of_week]||x.day_name_es)+'</strong></td><td class="text-center"><input type="checkbox" class="rule-active" '+(Number(x.is_active)?'checked':'')+'></td><td><input type="time" class="form-control form-control-sm rule-entry" value="'+entry+'"></td><td><div class="input-group input-group-sm"><input type="number" min="0" max="180" class="form-control rule-tolerance" value="'+Number(x.tolerance_minutes||0)+'"><div class="input-group-append"><span class="input-group-text">min</span></div></div></td><td><input type="time" class="form-control form-control-sm rule-exit" value="'+exit+'"></td><td><input type="time" class="form-control form-control-sm rule-early-exit" value="'+early+'"></td></tr>'});let present=(r.rules||[]).map(x=>x.day_of_week);Object.keys(dayNames).filter(d=>!present.includes(d)).forEach(d=>h+='<tr data-day="'+d+'"><td><strong>'+dayNames[d]+'</strong></td><td class="text-center"><input type="checkbox" class="rule-active"></td><td><input type="time" class="form-control form-control-sm rule-entry" value="07:30"></td><td><input type="number" min="0" max="180" class="form-control form-control-sm rule-tolerance" value="10"></td><td><input type="time" class="form-control form-control-sm rule-exit" value="15:00"></td><td><input type="time" class="form-control form-control-sm rule-early-exit" value="14:45"></td></tr>');$('#rules-body').html(h);let c='';(r.calendar||[]).forEach(x=>c+='<tr class="ar-calendar-row"><td>'+esc(x.calendar_date)+'</td><td><strong>'+esc(x.name)+'</strong><div class="small text-muted">'+esc(x.notes||'')+'</div></td><td>'+esc(x.day_type)+'</td><td><button class="btn btn-sm btn-link text-danger delete-calendar" data-id="'+x.id+'"><i class="fas fa-trash"></i></button></td></tr>');$('#calendar-body').html(c||'<tr><td colspan="4" class="text-center py-4">Sin fechas configuradas.</td></tr>')
 }).fail(xhr=>{let message='No se pudieron cargar las reglas';try{let r=JSON.parse(xhr.responseText);if(r.message)message=r.message}catch(e){if(xhr.status)message+=' (HTTP '+xhr.status+')'}showLoadError(message)});
}
function showLoadError(message){$('#rules-body').html('<tr><td colspan="6" class="text-center py-4 text-danger"><i class="fas fa-exclamation-triangle mr-2"></i>'+esc(message)+'<br><button type="button" id="retry-rules" class="btn btn-sm btn-outline-primary mt-3">Reintentar</button></td></tr>');$('#ar-message').html('<div class="alert alert-danger">'+esc(message)+'</div>')}
$(document).on('click','#retry-rules',load);
$('#save-rules').click(function(){let rows=[];$('#rules-body tr[data-day]').each(function(){rows.push({day:$(this).data('day'),active:$(this).find('.rule-active').is(':checked')?1:0,entry:$(this).find('.rule-entry').val(),tolerance:$(this).find('.rule-tolerance').val(),exit:$(this).find('.rule-exit').val(),early_exit:$(this).find('.rule-early-exit').val()})});start_load();post('save_rules',{rules:JSON.stringify(rows)}).done(r=>alert_toast(r.message,r.status?'success':'danger')).always(end_load)});
$('#calendar-form').submit(function(e){e.preventDefault();const form=this;start_load();post('save_calendar',{date:$('#cal-date').val(),name:$('#cal-name').val(),day_type:$('#cal-type').val(),notes:$('#cal-notes').val()}).done(function(r){alert_toast(r.message,r.status?'success':'danger');if(r.status){form.reset();load()}}).always(end_load)});
$(document).on('click','.delete-calendar',function(){if(!confirm('¿Eliminar esta fecha especial?'))return;post('delete_calendar',{id:$(this).data('id')}).done(r=>{alert_toast(r.message,r.status?'success':'danger');if(r.status)load()})});load();
})(jQuery);
</script><?php endif;?>
