<?php
ob_start();date_default_timezone_set('America/Lima');include_once __DIR__.'/includes/session_check.php';require_login_modal();include __DIR__.'/db_connect.php';include_once __DIR__.'/includes/attendance_report_queries.php';
header('Content-Type: application/json; charset=utf-8');
function aro($x,$code=200){while(ob_get_level())ob_end_clean();http_response_code($code);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
$school=(int)($_SESSION['login_school_id']??0);$user=(int)($_SESSION['login_id']??0);$type=(int)($_SESSION['login_type']??0);if(!$school||!$user||!in_array($type,[1,2,3],true))aro(['status'=>0,'message'=>'No autorizado.'],403);
$ready=$conn->query("SHOW COLUMNS FROM asistencia LIKE 'school_id'");if(!$ready||!$ready->num_rows)aro(['status'=>0,'migration_required'=>true,'message'=>'Ejecute sql/attendance_module_upgrade.sql.'],409);
$action=$_GET['action']??'list';
if($action==='meta'){$years=[];$q=$conn->query("SELECT id,year,start_date,end_date,is_active FROM academic_year WHERE school_id=$school ORDER BY year DESC");while($q&&($r=$q->fetch_assoc()))$years[]=$r;$levels=[];$q=$conn->query("SELECT DISTINCT nivel FROM student WHERE school_id=$school AND status='Activo' AND nivel<>'' ORDER BY FIELD(nivel,'Inicial','Primaria','Secundaria'),nivel");while($q&&($r=$q->fetch_assoc()))$levels[]=$r['nivel'];aro(['status'=>1,'years'=>$years,'levels'=>$levels]);}
if($action==='options'){$level=arq_escape($conn,$_GET['nivel']??'');$grade=arq_escape($conn,$_GET['grado']??'');$section=arq_escape($conn,$_GET['seccion']??'');$where="school_id=$school AND status='Activo'";if($level!=='')$where.=" AND nivel='$level'";if($grade!=='')$where.=" AND grado='$grade'";if($section!=='')$where.=" AND seccion='$section'";$grades=[];$q=$conn->query("SELECT DISTINCT grado FROM student WHERE $where AND grado<>'' ORDER BY grado");while($q&&($r=$q->fetch_assoc()))$grades[]=$r['grado'];$sections=[];$q=$conn->query("SELECT DISTINCT seccion FROM student WHERE $where AND seccion<>'' ORDER BY seccion");while($q&&($r=$q->fetch_assoc()))$sections[]=$r['seccion'];$students=[];$q=$conn->query("SELECT id,id_no,name,nivel,grado,seccion FROM student WHERE $where ORDER BY name LIMIT 1000");while($q&&($r=$q->fetch_assoc()))$students[]=$r;aro(['status'=>1,'grades'=>$grades,'sections'=>$sections,'students'=>$students]);}
if($action==='detail'){$id=(int)($_GET['id']??0);$s=$conn->prepare("SELECT a.*,s.id_no,s.name student_name,s.nivel,s.grado,s.seccion,uc.name created_name,uu.name updated_name FROM asistencia a INNER JOIN student s ON s.id=a.student_id LEFT JOIN users uc ON uc.id=a.created_by LEFT JOIN users uu ON uu.id=a.updated_by WHERE a.id=? AND a.school_id=? LIMIT 1");$s->bind_param('ii',$id,$school);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();if(!$row)aro(['status'=>0,'message'=>'Registro no encontrado.'],404);$audit=[];$q=$conn->query("SELECT al.action,al.details,al.created_at,u.name user_name FROM attendance_audit_log al LEFT JOIN users u ON u.id=al.user_id WHERE al.school_id=$school AND al.attendance_id=$id ORDER BY al.id DESC LIMIT 50");while($q&&($r=$q->fetch_assoc()))$audit[]=$r;aro(['status'=>1,'record'=>$row,'audit'=>$audit]);}
$draw=(int)($_GET['draw']??1);$start=max(0,(int)($_GET['start']??0));$length=min(100,max(10,(int)($_GET['length']??25)));$view=$_GET['view']??'detail';$filters=arq_filters($conn,$school,$_GET);$result=arq_rows($conn,$school,$filters,$view,$start,$length);aro(['draw'=>$draw,'recordsTotal'=>$result['total'],'recordsFiltered'=>$result['total'],'data'=>$result['rows'],'summary'=>arq_summary($conn,$school,$filters)]);
