<?php
include_once __DIR__.'/includes/session_check.php';require_login_modal();include __DIR__.'/db_connect.php';
if(empty($_SESSION['login_id'])||(int)($_SESSION['login_type']??0)!==1){header('location:login.php');exit;}
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$csrf=$_SESSION['csrf_token'];$school=(int)($_SESSION['login_school_id']??0);$years=[];$selected=0;$s=$conn->prepare('SELECT id,year,is_active FROM academic_year WHERE school_id=? ORDER BY year DESC');$s->bind_param('i',$school);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc()){$years[]=$x;if($x['is_active'])$selected=(int)$x['id'];}$s->close();if(!$selected&&$years)$selected=(int)$years[0]['id'];
?>
<style>
.cp{padding:8px 4px}.cp-head,.cp-heading,.cp-panel-head{display:flex;align-items:center}.cp-head,.cp-panel-head{justify-content:space-between;gap:12px}.cp-head{margin-bottom:14px}.cp-heading{gap:12px}.cp-icon{width:46px;height:46px;border-radius:12px;background:#eaf2ff;color:#2f6fed;display:flex;align-items:center;justify-content:center;font-size:20px}.cp-heading h5{margin:0;font-weight:700;color:#233b52}.cp-heading small{color:#6c757d}.cp-toolbar{display:grid;grid-template-columns:1.1fr 1fr 1fr 1.4fr auto;gap:12px;background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:14px;margin-bottom:14px}.cp-field label{display:block;font-size:.78rem;font-weight:700;color:#526274;margin-bottom:5px}.cp-field .form-control{height:38px;border-radius:8px}.cp-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:14px}.cp-stat{background:#fff;border:1px solid #e3e8f0;border-radius:12px;padding:13px;display:flex;gap:11px;align-items:center}.cp-stat i{width:38px;height:38px;border-radius:10px;background:#edf3ff;color:#2f6fed;display:flex;align-items:center;justify-content:center}.cp-stat strong{display:block;font-size:1.13rem;color:#233b52}.cp-stat span{font-size:.74rem;color:#6c757d}.cp-panel{background:#fff;border:1px solid #e3e8f0;border-radius:12px;overflow:hidden}.cp-panel-head{padding:12px 14px;border-bottom:1px solid #e9edf4}.cp-body{padding:14px}.cp-bulk{display:none;background:#f3f7ff;border:1px solid #dce7ff;border-radius:9px;padding:10px;margin-bottom:12px;align-items:center;gap:8px}.cp-bulk.show{display:flex}.cp-empty{text-align:center;padding:45px;color:#7a8794}.table td,.table th{vertical-align:middle!important}@media(max-width:1050px){.cp-toolbar{grid-template-columns:repeat(3,1fr)}.cp-stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.cp-head,.cp-panel-head{align-items:flex-start;flex-direction:column}.cp-toolbar,.cp-stats{grid-template-columns:1fr 1fr}}
</style>
<div class="container-fluid cp">
 <div class="cp-head"><div class="cp-heading"><div class="cp-icon"><i class="fa fa-file-invoice-dollar"></i></div><div><h5>Conceptos de pago</h5><small>Catálogo, asignación y seguimiento financiero por año académico</small></div></div><button class="btn btn-primary" id="new-concept"><i class="fa fa-plus mr-1"></i>Nuevo concepto</button></div>
 <div id="cp-migration" class="alert alert-warning d-none"><strong>Migración pendiente:</strong> ejecuta <code>sql/concepts_module_upgrade.sql</code>.</div>
 <div class="cp-toolbar"><div class="cp-field"><label>Año académico</label><select id="cp-year" class="form-control"><?php foreach($years as $y): ?><option value="<?php echo (int)$y['id']; ?>" <?php echo $selected===(int)$y['id']?'selected':''; ?>><?php echo htmlspecialchars($y['year'].($y['is_active']?' (Activo)':'')); ?></option><?php endforeach; ?></select></div><div class="cp-field"><label>Nivel</label><select id="cp-level" class="form-control"><option value="">Todos</option><option>Inicial</option><option>Primaria</option><option>Secundaria</option></select></div><div class="cp-field"><label>Estado</label><select id="cp-status" class="form-control"><option value="">Todos</option><option>Activo</option><option>Suspendido</option><option>Archivado</option></select></div><div class="cp-field"><label>Buscar</label><input id="cp-search" class="form-control" placeholder="Nombre o descripción"></div><div class="cp-field"><label>&nbsp;</label><button id="cp-reset" class="btn btn-outline-secondary"><i class="fa fa-undo"></i></button></div></div>
 <div class="cp-stats"><div class="cp-stat"><i class="fa fa-list"></i><div><strong id="st-concepts">0</strong><span>Conceptos visibles</span></div></div><div class="cp-stat"><i class="fa fa-check-circle"></i><div><strong id="st-active">0</strong><span>Activos</span></div></div><div class="cp-stat"><i class="fa fa-file-invoice"></i><div><strong id="st-assigned">S/ 0.00</strong><span>Total asignado</span></div></div><div class="cp-stat"><i class="fa fa-hand-holding-usd"></i><div><strong id="st-collected">S/ 0.00</strong><span>Total cobrado</span></div></div><div class="cp-stat"><i class="fa fa-wallet"></i><div><strong id="st-balance">S/ 0.00</strong><span>Saldo pendiente</span></div></div></div>
 <div class="cp-panel"><div class="cp-panel-head"><strong><i class="fa fa-table text-primary mr-2"></i>Catálogo de conceptos</strong><div><button id="cp-export" class="btn btn-sm btn-outline-success"><i class="fa fa-file-excel mr-1"></i>Exportar</button> <button id="cp-audit" class="btn btn-sm btn-outline-secondary"><i class="fa fa-history mr-1"></i>Auditoría</button> <button id="cp-refresh" class="btn btn-sm btn-outline-primary"><i class="fa fa-sync-alt"></i></button></div></div><div class="cp-body"><div class="cp-bulk" id="cp-bulk"><strong><span id="cp-selected">0</span> seleccionados</strong><select id="cp-bulk-status" class="form-control form-control-sm" style="max-width:190px"><option value="">Cambiar estado...</option><option>Activo</option><option>Suspendido</option><option>Archivado</option></select><button id="cp-apply" class="btn btn-sm btn-primary">Aplicar</button><button id="cp-clear" class="btn btn-sm btn-link">Cancelar</button></div><div id="cp-loading" class="text-center py-5"><i class="fa fa-spinner fa-spin fa-2x text-primary"></i></div><div id="cp-results"></div></div></div>
</div>
<div class="modal fade" id="conceptAudit"><div class="modal-dialog modal-xl"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fa fa-history mr-2"></i>Auditoría de conceptos</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Fecha</th><th>Usuario</th><th>Concepto</th><th>Acción</th><th>Detalle</th></tr></thead><tbody id="cp-audit-body"></tbody></table></div></div></div></div>
<script>(function($){const api='concepts_api.php',csrf=<?php echo json_encode($csrf); ?>;let rows=[],selected={},timer,dataTable=null;
function e(v){return $('<div>').text(v==null?'':v).html()}function money(v){return 'S/ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}function bulk(){let n=Object.keys(selected).length;$('#cp-selected').text(n);$('#cp-bulk').toggleClass('show',n>0)}
function load(){$('#cp-loading').show();$('#cp-results').empty();$.getJSON(api,{action:'list',academic_year_id:$('#cp-year').val(),level:$('#cp-level').val(),status:$('#cp-status').val(),search:$('#cp-search').val()}).done(function(r){rows=r.concepts||[];let s=r.stats||{};$('#st-concepts').text(s.concepts||0);$('#st-active').text(s.active||0);$('#st-assigned').text(money(s.assigned));$('#st-collected').text(money(s.collected));$('#st-balance').text(money(s.balance));render()}).fail(function(x){let r=x.responseJSON||{};if(r.migration_required){$('#cp-migration').removeClass('d-none');$('#new-concept,#cp-apply').prop('disabled',true)}$('#cp-results').html('<div class="cp-empty">'+e(r.message||'No se pudieron cargar los conceptos.')+'</div>')}).always(()=>$('#cp-loading').hide())}
function destroyTable(){if(dataTable){dataTable.destroy();dataTable=null}}
function render(){destroyTable();if(!rows.length){$('#cp-results').html('<div class="cp-empty"><i class="fa fa-folder-open fa-3x mb-2"></i><h6>No hay conceptos para estos filtros</h6></div>');return}let h='<div class="table-responsive"><table class="table table-hover" id="cp-table"><thead><tr><th><input type="checkbox" id="cp-all"></th><th>Concepto</th><th>Nivel y grados</th><th>Monto base</th><th>Asignado</th><th>Cobrado</th><th>Saldo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>';rows.forEach(c=>{let badge=c.concept_status==='Activo'?'success':(c.concept_status==='Suspendido'?'warning':'secondary'),locked=['Cerrado','Archivado'].includes(c.year_status);h+='<tr><td><input class="cp-check" type="checkbox" value="'+c.id+'" '+(selected[c.id]?'checked':'')+' '+(locked?'disabled':'')+'></td><td><strong>'+e(c.course)+'</strong><div class="small text-muted">'+e(c.description||'Sin descripción')+' · '+e(c.year)+'</div></td><td>'+e(c.level)+'<div class="small text-muted">'+e(c.grades||'—')+'</div></td><td>'+money(c.total_amount)+'</td><td>'+money(c.assigned_total)+'<div class="small text-muted">'+c.assignment_count+' asignaciones</div></td><td class="text-success">'+money(c.collected_total)+'</td><td class="font-weight-bold">'+money(c.balance)+'</td><td><span class="badge badge-'+badge+'">'+e(c.concept_status)+'</span></td><td><div class="btn-group"><button class="btn btn-sm btn-outline-primary cp-edit" data-id="'+c.id+'" '+(locked?'disabled':'')+'><i class="fa fa-edit"></i></button><button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown"></button><div class="dropdown-menu dropdown-menu-right"><a href="#" class="dropdown-item cp-state" data-id="'+c.id+'" data-state="Activo">Activar</a><a href="#" class="dropdown-item cp-state" data-id="'+c.id+'" data-state="Suspendido">Suspender</a><a href="#" class="dropdown-item cp-state" data-id="'+c.id+'" data-state="Archivado">Archivar</a><div class="dropdown-divider"></div><a href="#" class="dropdown-item text-danger cp-delete" data-id="'+c.id+'">Eliminar si está vacío</a></div></div></td></tr>'});$('#cp-results').html(h+'</tbody></table></div>');if($.fn.DataTable){dataTable=$('#cp-table').DataTable({pageLength:15,lengthMenu:[[15,25,50,100],[15,25,50,100]],order:[[1,'asc']],columnDefs:[{orderable:false,targets:[0,8]}],dom:'lrtip',language:{lengthMenu:'Mostrar _MENU_ registros',zeroRecords:'No se encontraron conceptos',info:'Mostrando _START_ a _END_ de _TOTAL_',infoEmpty:'Mostrando 0 registros',infoFiltered:'(filtrado de _MAX_)',paginate:{previous:'Anterior',next:'Siguiente'}}})}bulk()}
$(document).on('change','.cp-check',function(){this.checked?selected[this.value]=1:delete selected[this.value];bulk()});$(document).on('change','#cp-all',function(){rows.forEach(c=>this.checked?selected[c.id]=1:delete selected[c.id]);render()});$('#cp-clear').click(function(){selected={};render()});$('#cp-year,#cp-level,#cp-status').change(function(){selected={};load()});$('#cp-search').on('input',function(){clearTimeout(timer);timer=setTimeout(load,300)});$('#cp-reset').click(function(){$('#cp-level,#cp-status,#cp-search').val('');selected={};load()});$('#cp-refresh').click(load);
$('#new-concept').click(()=>uni_modal('Nuevo concepto de pago','manage_concept.php','large'));$(document).on('click','.cp-edit',function(){uni_modal('Editar concepto de pago','manage_concept.php?id='+$(this).data('id'),'large')});$(document).on('concepts:changed',load);
function post(action,data){data.csrf_token=csrf;return $.post(api+'?action='+action,data,null,'json')}$(document).on('click','.cp-state',function(x){x.preventDefault();let id=$(this).data('id'),state=$(this).data('state');if(confirm('¿Cambiar el concepto a '+state+'?'))post('change_status',{id:id,concept_status:state}).done(r=>{alert_toast(r.message,r.status==1?'success':'danger');if(r.status==1)load()})});$(document).on('click','.cp-delete',function(x){x.preventDefault();let id=$(this).data('id');if(confirm('Solo se eliminará si no tiene historial. De lo contrario será archivado. ¿Continuar?'))post('delete',{id:id}).done(r=>{alert_toast(r.message,r.status==1?'success':'danger');if(r.status==1)load()})});
$('#cp-apply').click(function(){let state=$('#cp-bulk-status').val(),ids=Object.keys(selected);if(!state)return alert_toast('Seleccione un estado.','warning');if(confirm('¿Cambiar '+ids.length+' conceptos a '+state+'?'))post('bulk',{ids:JSON.stringify(ids),concept_status:state,academic_year_id:$('#cp-year').val()}).done(r=>{alert_toast(r.message,r.status==1?'success':'danger');if(r.status==1){selected={};load()}})});
$('#cp-export').click(function(){let ids=Object.keys(selected);location='export_concepts.php?'+$.param({academic_year_id:$('#cp-year').val(),level:$('#cp-level').val(),status:$('#cp-status').val(),search:$('#cp-search').val(),ids:ids.join(',')})});$('#cp-audit').click(function(){$('#cp-audit-body').html('<tr><td colspan="5" class="text-center"><i class="fa fa-spinner fa-spin"></i></td></tr>');$('#conceptAudit').modal('show');$.getJSON(api,{action:'audit',academic_year_id:$('#cp-year').val()}).done(function(r){let h='';(r.audit||[]).forEach(x=>h+='<tr><td>'+e(x.created_at)+'</td><td>'+e(x.user_name)+'</td><td>'+e(x.concept_name)+'</td><td>'+e(x.action)+'</td><td><small>'+e(x.details||'')+'</small></td></tr>');$('#cp-audit-body').html(h||'<tr><td colspan="5" class="text-center text-muted">Sin movimientos.</td></tr>')})});load();})(jQuery);</script>
