<?php
ob_start();
include_once __DIR__.'/includes/session_check.php';
require_login_modal();
include __DIR__.'/db_connect.php';
header('Content-Type: application/json; charset=utf-8');

function cpResponse($data,$code=200){http_response_code($code);echo json_encode($data,JSON_UNESCAPED_UNICODE);exit;}
function cpHasTable($db,$table){$v=$db->real_escape_string($table);$q=$db->query("SHOW TABLES LIKE '$v'");return $q&&$q->num_rows>0;}
function cpHasColumn($db,$table,$column){$v=$db->real_escape_string($column);$q=$db->query("SHOW COLUMNS FROM `$table` LIKE '$v'");return $q&&$q->num_rows>0;}
function cpReady($db){return cpHasColumn($db,'courses','concept_status')&&cpHasTable($db,'course_grades')&&cpHasTable($db,'concept_audit_log')&&cpHasColumn($db,'academic_year','status');}
function cpBind($stmt,$types,&$params){$args=[$types];foreach($params as &$value)$args[]=&$value;call_user_func_array([$stmt,'bind_param'],$args);}
function cpAudit($db,$school,$year,$course,$action,$details=[]){$user=(int)($_SESSION['login_id']??0);$ip=$_SERVER['REMOTE_ADDR']??null;$json=json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$s=$db->prepare('INSERT INTO concept_audit_log(school_id,academic_year_id,course_id,user_id,action,details,ip_address) VALUES(?,NULLIF(?,0),NULLIF(?,0),NULLIF(?,0),?,?,?)');if($s){$s->bind_param('iiiisss',$school,$year,$course,$user,$action,$json,$ip);$s->execute();$s->close();}}
function cpCourse($db,$id,$school){$s=$db->prepare('SELECT c.*,ay.year,ay.status year_status FROM courses c INNER JOIN academic_year ay ON ay.id=c.academic_year_id WHERE c.id=? AND ay.school_id=? LIMIT 1');$s->bind_param('ii',$id,$school);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return $r?:null;}
function cpNormalizeGrades($level,$grades){$allowed=['Inicial'=>['3°','4°','5°'],'Primaria'=>['1°','2°','3°','4°','5°','6°'],'Secundaria'=>['1°','2°','3°','4°','5°']];if(!isset($allowed[$level]))return [];$grades=is_array($grades)?$grades:explode(',',(string)$grades);$out=[];foreach($grades as $g){$g=trim($g);if($level==='Inicial'&&in_array($g,['3 años','4 años','5 años'],true))$g=explode(' ',$g)[0].'°';if(in_array($g,$allowed[$level],true))$out[]=$g;}return array_values(array_unique($out));}
function cpDependencyCounts($db,$course){$out=['deudas'=>0,'pagos'=>0,'tarifas'=>0];if(cpHasTable($db,'student_ef_list')){$q=$db->query('SELECT COUNT(*) total FROM student_ef_list WHERE course_id='.(int)$course);if($q)$out['deudas']=(int)$q->fetch_assoc()['total'];if(cpHasTable($db,'payments')){$q=$db->query('SELECT COUNT(*) total FROM payments p INNER JOIN student_ef_list ef ON ef.id=p.ef_id WHERE ef.course_id='.(int)$course);if($q)$out['pagos']=(int)$q->fetch_assoc()['total'];}}if(cpHasTable($db,'fees')){$q=$db->query('SELECT COUNT(*) total FROM fees WHERE course_id='.(int)$course);if($q)$out['tarifas']=(int)$q->fetch_assoc()['total'];}return $out;}

$school=(int)($_SESSION['login_school_id']??0);$user=(int)($_SESSION['login_id']??0);$action=$_GET['action']??'';
if(!$school||!$user||(int)($_SESSION['login_type']??0)!==1)cpResponse(['status'=>0,'message'=>'No tiene permisos para gestionar conceptos.'],403);
if(!cpReady($conn))cpResponse(['status'=>0,'migration_required'=>true,'message'=>'Ejecute sql/concepts_module_upgrade.sql antes de utilizar el módulo.'],409);
$write=['save','change_status','delete','bulk'];if(in_array($action,$write,true)){$sent=(string)($_POST['csrf_token']??'');$saved=(string)($_SESSION['csrf_token']??'');if(!$sent||!$saved||!hash_equals($saved,$sent))cpResponse(['status'=>0,'message'=>'La sesión de seguridad venció. Recargue la página.'],403);}

if($action==='bootstrap'){
    $years=[];$s=$conn->prepare("SELECT id,year,is_active,status FROM academic_year WHERE school_id=? AND status<>'Archivado' ORDER BY year DESC");$s->bind_param('i',$school);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$years[]=$x;$s->close();cpResponse(['status'=>1,'years'=>$years]);
}
if($action==='list'){
    $year=(int)($_GET['academic_year_id']??0);$level=trim($_GET['level']??'');$status=trim($_GET['status']??'');$search=trim($_GET['search']??'');$where=['ay.school_id=?'];$types='i';$params=[$school];
    if($year){$where[]='c.academic_year_id=?';$types.='i';$params[]=$year;}if($level){$where[]='c.level=?';$types.='s';$params[]=$level;}if($status){$where[]='c.concept_status=?';$types.='s';$params[]=$status;}if($search){$where[]='(c.course LIKE ? OR c.description LIKE ?)';$types.='ss';$like='%'.$search.'%';$params[]=$like;$params[]=$like;}
    $sql="SELECT c.id,c.course,c.description,c.level,c.grades,c.total_amount,c.academic_year_id,c.concept_status,ay.year,ay.status year_status,
        (SELECT COUNT(*) FROM student_ef_list ef WHERE ef.course_id=c.id) assignment_count,
        (SELECT COALESCE(SUM(COALESCE(ef.discounted_amount,ef.total_fee)),0) FROM student_ef_list ef WHERE ef.course_id=c.id) assigned_total,
        (SELECT COALESCE(SUM(p.amount),0) FROM payments p INNER JOIN student_ef_list ef ON ef.id=p.ef_id WHERE ef.course_id=c.id AND p.payment_status='Confirmado') collected_total
        FROM courses c INNER JOIN academic_year ay ON ay.id=c.academic_year_id WHERE ".implode(' AND ',$where)." ORDER BY ay.year DESC,c.course,c.level";
    $s=$conn->prepare($sql);cpBind($s,$types,$params);$s->execute();$items=[];$r=$s->get_result();while($x=$r->fetch_assoc()){$x['balance']=(float)$x['assigned_total']-(float)$x['collected_total'];$items[]=$x;}$s->close();
    $stats=['active'=>0,'concepts'=>count($items),'assigned'=>0,'collected'=>0,'balance'=>0,'without_assignments'=>0];foreach($items as $x){if($x['concept_status']==='Activo')$stats['active']++;$stats['assigned']+=(float)$x['assigned_total'];$stats['collected']+=(float)$x['collected_total'];$stats['balance']+=(float)$x['balance'];if(!(int)$x['assignment_count'])$stats['without_assignments']++;}cpResponse(['status'=>1,'concepts'=>$items,'stats'=>$stats]);
}
if($action==='get'){
    $id=(int)($_GET['id']??0);$course=cpCourse($conn,$id,$school);if(!$course)cpResponse(['status'=>0,'message'=>'Concepto no encontrado.'],404);$grades=[];$s=$conn->prepare('SELECT grade FROM course_grades WHERE course_id=? ORDER BY id');$s->bind_param('i',$id);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$grades[]=$x['grade'];$s->close();$course['normalized_grades']=$grades;$course['dependencies']=cpDependencyCounts($conn,$id);cpResponse(['status'=>1,'concept'=>$course]);
}
if($action==='save'){
    $id=(int)($_POST['id']??0);$name=trim($_POST['course']??'');$description=trim($_POST['description']??'');$level=trim($_POST['level']??'');$year=(int)($_POST['academic_year_id']??0);$amount=(float)($_POST['total_amount']??0);$grades=cpNormalizeGrades($level,$_POST['grades']??[]);
    if(!$name||!in_array($level,['Inicial','Primaria','Secundaria'],true)||!$year||$amount<0||!$grades)cpResponse(['status'=>0,'message'=>'Complete correctamente nombre, nivel, grados, año y monto.']);
    $ys=$conn->prepare('SELECT status FROM academic_year WHERE id=? AND school_id=? LIMIT 1');$ys->bind_param('ii',$year,$school);$ys->execute();$yr=$ys->get_result()->fetch_assoc();$ys->close();if(!$yr||in_array($yr['status'],['Cerrado','Archivado'],true))cpResponse(['status'=>0,'message'=>'El año está cerrado o no pertenece a la institución.']);
    $current=$id?cpCourse($conn,$id,$school):null;if($id&&!$current)cpResponse(['status'=>0,'message'=>'Concepto no encontrado.']);if($current&&in_array($current['year_status'],['Cerrado','Archivado'],true))cpResponse(['status'=>0,'message'=>'No puede editar un concepto de un año cerrado.']);
    if($current){$deps=cpDependencyCounts($conn,$id);$oldGrades=cpNormalizeGrades($current['level'],$current['grades']??'');$newGrades=$grades;sort($oldGrades);sort($newGrades);if($deps['deudas']>0&&((int)$current['academic_year_id']!==$year||$current['level']!==$level||$oldGrades!==$newGrades))cpResponse(['status'=>0,'message'=>'El concepto ya tiene deudas. Para conservar su historial no puede cambiar de año, nivel ni grados; archívelo y cree uno nuevo.']);}
    $dup=$conn->prepare('SELECT id FROM courses WHERE academic_year_id=? AND level=? AND course=? AND id<>? LIMIT 1');$dup->bind_param('issi',$year,$level,$name,$id);$dup->execute();if($dup->get_result()->fetch_assoc()){ $dup->close();cpResponse(['status'=>0,'message'=>'Ya existe un concepto con ese nombre, nivel y año.']);}$dup->close();$legacy=implode(',',$grades);
    $conn->begin_transaction();try{if($id){$s=$conn->prepare('UPDATE courses SET course=?,description=?,level=?,grades=?,academic_year_id=?,total_amount=? WHERE id=?');$s->bind_param('ssssidi',$name,$description,$level,$legacy,$year,$amount,$id);}else{$s=$conn->prepare("INSERT INTO courses(course,description,level,grades,academic_year_id,total_amount,concept_status) VALUES(?,?,?,?,?,?,'Activo')");$s->bind_param('ssssid',$name,$description,$level,$legacy,$year,$amount);}if(!$s->execute())throw new Exception($s->error);if(!$id)$id=$s->insert_id;$s->close();$d=$conn->prepare('DELETE FROM course_grades WHERE course_id=?');$d->bind_param('i',$id);if(!$d->execute())throw new Exception($d->error);$d->close();$g=$conn->prepare('INSERT INTO course_grades(course_id,grade) VALUES(?,?)');foreach($grades as $grade){$g->bind_param('is',$id,$grade);if(!$g->execute())throw new Exception($g->error);}$g->close();$conn->commit();}catch(Throwable $e){$conn->rollback();error_log('[concepts] save: '.$e->getMessage());cpResponse(['status'=>0,'message'=>'No se pudo guardar el concepto.']);}
    cpAudit($conn,$school,$year,$id,$current?'concept_updated':'concept_created',['name'=>$name,'amount'=>$amount,'grades'=>$grades]);cpResponse(['status'=>1,'message'=>$current?'Concepto actualizado.':'Concepto creado.']);
}
if($action==='change_status'){
    $id=(int)($_POST['id']??0);$status=trim($_POST['concept_status']??'');if(!in_array($status,['Activo','Suspendido','Archivado'],true))cpResponse(['status'=>0,'message'=>'Estado inválido.']);$course=cpCourse($conn,$id,$school);if(!$course||in_array($course['year_status'],['Cerrado','Archivado'],true))cpResponse(['status'=>0,'message'=>'El concepto no puede modificarse.']);$s=$conn->prepare('UPDATE courses SET concept_status=? WHERE id=?');$s->bind_param('si',$status,$id);$ok=$s->execute();$s->close();if(!$ok)cpResponse(['status'=>0,'message'=>'No se pudo actualizar el estado.']);cpAudit($conn,$school,(int)$course['academic_year_id'],$id,'concept_status_changed',['from'=>$course['concept_status'],'to'=>$status]);cpResponse(['status'=>1,'message'=>'Estado actualizado.']);
}
if($action==='delete'){
    $id=(int)($_POST['id']??0);$course=cpCourse($conn,$id,$school);if(!$course||in_array($course['year_status'],['Cerrado','Archivado'],true))cpResponse(['status'=>0,'message'=>'El concepto no puede eliminarse.']);$deps=cpDependencyCounts($conn,$id);if(array_sum($deps)>0){$s=$conn->prepare("UPDATE courses SET concept_status='Archivado' WHERE id=?");$s->bind_param('i',$id);$s->execute();$s->close();cpAudit($conn,$school,(int)$course['academic_year_id'],$id,'concept_archived_due_to_history',$deps);cpResponse(['status'=>1,'archived'=>true,'message'=>'El concepto tiene historial y fue archivado en lugar de eliminarse.']);}$conn->begin_transaction();try{$s=$conn->prepare('DELETE FROM course_grades WHERE course_id=?');$s->bind_param('i',$id);$s->execute();$s->close();$s=$conn->prepare('DELETE FROM courses WHERE id=?');$s->bind_param('i',$id);if(!$s->execute()||$s->affected_rows<1)throw new Exception($s->error);$s->close();$conn->commit();}catch(Throwable $e){$conn->rollback();cpResponse(['status'=>0,'message'=>'No se pudo eliminar el concepto.']);}cpAudit($conn,$school,(int)$course['academic_year_id'],0,'empty_concept_deleted',['id'=>$id,'name'=>$course['course']]);cpResponse(['status'=>1,'message'=>'Concepto vacío eliminado.']);
}
if($action==='bulk'){
    $ids=json_decode($_POST['ids']??'[]',true);$ids=array_values(array_unique(array_filter(array_map('intval',is_array($ids)?$ids:[]))));$status=trim($_POST['concept_status']??'');$year=(int)($_POST['academic_year_id']??0);if(!$ids||count($ids)>200||!in_array($status,['Activo','Suspendido','Archivado'],true)||!$year)cpResponse(['status'=>0,'message'=>'Acción masiva inválida.']);$ys=$conn->prepare('SELECT status FROM academic_year WHERE id=? AND school_id=?');$ys->bind_param('ii',$year,$school);$ys->execute();$yr=$ys->get_result()->fetch_assoc();$ys->close();if(!$yr||in_array($yr['status'],['Cerrado','Archivado'],true))cpResponse(['status'=>0,'message'=>'El año seleccionado está bloqueado.']);$list=implode(',',$ids);$s=$conn->prepare("UPDATE courses c INNER JOIN academic_year ay ON ay.id=c.academic_year_id SET c.concept_status=? WHERE c.id IN ($list) AND c.academic_year_id=? AND ay.school_id=?");$s->bind_param('sii',$status,$year,$school);$s->execute();$count=$s->affected_rows;$s->close();foreach($ids as $id)cpAudit($conn,$school,$year,$id,'concept_bulk_status',['to'=>$status]);cpResponse(['status'=>1,'message'=>"Se actualizaron $count conceptos.",'updated'=>$count]);
}
if($action==='audit'){
    $year=(int)($_GET['academic_year_id']??0);$s=$conn->prepare("SELECT l.*,COALESCE(u.name,'Sistema') user_name,COALESCE(c.course,'Concepto eliminado') concept_name FROM concept_audit_log l LEFT JOIN users u ON u.id=l.user_id LEFT JOIN courses c ON c.id=l.course_id WHERE l.school_id=? AND(l.academic_year_id=? OR ?=0) ORDER BY l.created_at DESC LIMIT 150");$s->bind_param('iii',$school,$year,$year);$s->execute();$items=[];$r=$s->get_result();while($x=$r->fetch_assoc())$items[]=$x;$s->close();cpResponse(['status'=>1,'audit'=>$items]);
}
cpResponse(['status'=>0,'message'=>'Acción no reconocida.'],404);
