<?php
include_once __DIR__.'/includes/session_check.php';require_login_modal();include __DIR__.'/db_connect.php';
if(empty($_SESSION['login_id'])||(int)($_SESSION['login_type']??0)!==1)die('No autorizado');
$school=(int)($_SESSION['login_school_id']??0);$year=(int)($_GET['academic_year_id']??0);$level=trim($_GET['level']??'');$status=trim($_GET['status']??'');$search=trim($_GET['search']??'');$ids=array_values(array_unique(array_filter(array_map('intval',explode(',',(string)($_GET['ids']??''))))));$where=['ay.school_id=?'];$types='i';$params=[$school];
if(count($ids)>200)die('Solo puede exportar hasta 200 conceptos seleccionados.');
if($ids)$where[]='c.id IN ('.implode(',',$ids).')';
if($year){$where[]='c.academic_year_id=?';$types.='i';$params[]=$year;}if($level){$where[]='c.level=?';$types.='s';$params[]=$level;}if($status){$where[]='c.concept_status=?';$types.='s';$params[]=$status;}if($search){$where[]='(c.course LIKE ? OR c.description LIKE ?)';$types.='ss';$like='%'.$search.'%';$params[]=$like;$params[]=$like;}
$sql="SELECT ay.year,c.course,c.description,c.level,c.grades,c.total_amount,c.concept_status,(SELECT COUNT(*) FROM student_ef_list ef WHERE ef.course_id=c.id) assignments,(SELECT COALESCE(SUM(COALESCE(ef.discounted_amount,ef.total_fee)),0) FROM student_ef_list ef WHERE ef.course_id=c.id) assigned,(SELECT COALESCE(SUM(p.amount),0) FROM payments p INNER JOIN student_ef_list ef ON ef.id=p.ef_id WHERE ef.course_id=c.id AND p.payment_status='Confirmado') collected FROM courses c INNER JOIN academic_year ay ON ay.id=c.academic_year_id WHERE ".implode(' AND ',$where)." ORDER BY ay.year DESC,c.course";
$s=$conn->prepare($sql);$args=[$types];foreach($params as &$v)$args[]=&$v;call_user_func_array([$s,'bind_param'],$args);$s->execute();$r=$s->get_result();$rows=[];while($x=$r->fetch_assoc()){$rows[]=[$x['year'],$x['course'],$x['description'],$x['level'],$x['grades'],(float)$x['total_amount'],(int)$x['assignments'],(float)$x['assigned'],(float)$x['collected'],(float)$x['assigned']-(float)$x['collected'],$x['concept_status']];}$s->close();
$autoload=__DIR__.'/vendor/autoload.php';if(!file_exists($autoload))die('No se encontró PhpSpreadsheet para generar el archivo Excel.');require_once $autoload;
$book=new PhpOffice\PhpSpreadsheet\Spreadsheet();$sheet=$book->getActiveSheet();$sheet->setTitle('Conceptos de pago');$headers=['Año','Concepto','Descripción','Nivel','Grados','Monto base','Asignaciones','Total asignado','Total cobrado','Saldo','Estado'];$sheet->fromArray($headers,null,'A1');if($rows)$sheet->fromArray($rows,null,'A2');$last=max(1,count($rows)+1);$sheet->getStyle('A1:K1')->getFont()->setBold(true)->getColor()->setARGB('FFFFFFFF');$sheet->getStyle('A1:K1')->getFill()->setFillType(PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)->getStartColor()->setARGB('FF2F6FED');$sheet->freezePane('A2');$sheet->setAutoFilter("A1:K$last");foreach(range('A','K') as $column)$sheet->getColumnDimension($column)->setAutoSize(true);$sheet->getStyle("F2:F$last")->getNumberFormat()->setFormatCode('S/ #,##0.00');$sheet->getStyle("H2:J$last")->getNumberFormat()->setFormatCode('S/ #,##0.00');
while(ob_get_level())ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="conceptos_pago_'.date('Ymd_His').'.xlsx"');header('Cache-Control:max-age=0');(new PhpOffice\PhpSpreadsheet\Writer\Xlsx($book))->save('php://output');exit;
