<?php
include_once __DIR__.'/includes/session_check.php';require_login_modal();include __DIR__.'/db_connect.php';
$school=(int)($_SESSION['login_school_id']??0);$type=(int)($_SESSION['login_type']??0);if(!$school||$type!==1)die('No autorizado.');$autoload=__DIR__.'/vendor/autoload.php';if(!file_exists($autoload))die('PhpSpreadsheet no está instalado.');require_once $autoload;
use PhpOffice\PhpSpreadsheet\Spreadsheet;use PhpOffice\PhpSpreadsheet\Writer\Xlsx;use PhpOffice\PhpSpreadsheet\Style\Fill;
$year=(int)($_GET['year_id']??0);$status=trim($_GET['status']??'');$origin=trim($_GET['origin']??'');$adminIds=array_values(array_unique(array_filter(array_map('intval',explode(',',(string)($_GET['admin_ids']??''))))));if(count($adminIds)>200)$adminIds=array_slice($adminIds,0,200);
$union="SELECT db.id record_id,'Administración' origin,db.academic_year_id,ay.year,s.id_no,s.name,c.course,db.benefit_type,db.calculation_type,db.value,db.previous_effective_amount,db.final_effective_amount,db.discount_amount,db.valid_from,db.valid_until,db.reason,db.status,u.name created_by,db.created_at,NULL receipt FROM discount_benefits db INNER JOIN student s ON s.id=db.student_id LEFT JOIN courses c ON c.id=db.course_id LEFT JOIN academic_year ay ON ay.id=db.academic_year_id LEFT JOIN users u ON u.id=db.created_by WHERE db.school_id=? UNION ALL SELECT dd.id,'Durante el pago',c.academic_year_id,ay.year,s.id_no,s.name,c.course,'Descuento en pago',IF(dd.discount_type='percentage','Porcentaje','Monto descontado'),dd.discount_value,dd.previous_effective_amount,dd.final_effective_amount,dd.discount_amount,NULL,NULL,dd.reason,IF(dd.status='Aplicado','Aplicado','Revertido'),u.name,dd.created_at,po.receipt_full FROM debt_discounts dd INNER JOIN student_ef_list ef ON ef.id=dd.debt_id INNER JOIN student s ON s.id=ef.student_id LEFT JOIN courses c ON c.id=ef.course_id LEFT JOIN academic_year ay ON ay.id=c.academic_year_id LEFT JOIN users u ON u.id=dd.authorized_by LEFT JOIN payment_operations po ON po.id=dd.payment_operation_id WHERE dd.school_id=?";
$where='1=1';$types='ii';$params=[$school,$school];if($adminIds){$where.=" AND x.origin='Administración' AND x.record_id IN(".implode(',',$adminIds).')';}else{if($year){$where.=' AND x.academic_year_id=?';$types.='i';$params[]=$year;}if($status!==''){$where.=' AND x.status=?';$types.='s';$params[]=$status;}if($origin!==''){$where.=' AND x.origin=?';$types.='s';$params[]=$origin;}}
$stmt=$conn->prepare("SELECT year,id_no,name,course,origin,benefit_type,calculation_type,value,previous_effective_amount,final_effective_amount,discount_amount,valid_from,valid_until,reason,status,created_by,created_at,receipt FROM ($union) x WHERE $where ORDER BY created_at DESC");$stmt->bind_param($types,...$params);$stmt->execute();$result=$stmt->get_result();
$book=new Spreadsheet();$sheet=$book->getActiveSheet();$sheet->setTitle('Descuentos');$headers=['Año','DNI','Estudiante','Concepto','Origen','Beneficio','Cálculo','Valor','Monto anterior','Monto final','Descuento','Válido desde','Válido hasta','Motivo','Estado','Registrado por','Fecha','Recibo'];$sheet->fromArray($headers,null,'A1');$sheet->getStyle('A1:R1')->getFont()->setBold(true)->getColor()->setARGB('FFFFFFFF');$sheet->getStyle('A1:R1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF2F6FED');$row=2;while($item=$result->fetch_assoc())$sheet->fromArray(array_values($item),null,'A'.$row++);foreach(range('A','R')as$column)$sheet->getColumnDimension($column)->setAutoSize(true);$sheet->freezePane('A2');$sheet->setAutoFilter('A1:R'.max(1,$row-1));while(ob_get_level())ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="descuentos_'.date('Ymd_His').'.xlsx"');header('Cache-Control: max-age=0');(new Xlsx($book))->save('php://output');exit;
