<?php
ob_start();
include_once __DIR__ . '/includes/session_check.php';
require_login_modal();
include __DIR__ . '/db_connect.php';
header('Content-Type: application/json; charset=utf-8');

function dfResponse($data, $code = 200) { if (ob_get_length()) ob_clean(); http_response_code($code); echo json_encode($data, JSON_UNESCAPED_UNICODE); exit; }
function dfColumn($db, $table, $column) { $column = $db->real_escape_string($column); $q = $db->query("SHOW COLUMNS FROM `$table` LIKE '$column'"); return $q && $q->num_rows > 0; }
function dfTable($db, $table) { $table = $db->real_escape_string($table); $q = $db->query("SHOW TABLES LIKE '$table'"); return $q && $q->num_rows > 0; }
function dfReady($db) { return dfColumn($db, 'student_ef_list', 'debt_status') && dfColumn($db, 'student_ef_list', 'due_date') && dfTable($db, 'debt_audit_log'); }
function dfBind($stmt, $types, &$params) { $args = [$types]; foreach ($params as &$value) $args[] = &$value; call_user_func_array([$stmt, 'bind_param'], $args); }
function dfAudit($db, $school, $debt, $student, $course, $year, $action, $details = []) { $user=(int)($_SESSION['login_id']??0); $ip=$_SERVER['REMOTE_ADDR']??null; $json=json_encode($details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); $s=$db->prepare('INSERT INTO debt_audit_log(school_id,academic_year_id,debt_id,student_id,course_id,user_id,action,details,ip_address) VALUES(?,NULLIF(?,0),NULLIF(?,0),NULLIF(?,0),NULLIF(?,0),NULLIF(?,0),?,?,?)'); if($s){$s->bind_param('iiiiiisss',$school,$year,$debt,$student,$course,$user,$action,$json,$ip);$s->execute();$s->close();} }
function dfDebt($db,$id,$school){$s=$db->prepare('SELECT ef.*,s.school_id,c.academic_year_id,ay.status year_status,(SELECT COALESCE(SUM(p.amount),0) FROM payments p WHERE p.ef_id=ef.id) paid FROM student_ef_list ef INNER JOIN student s ON s.id=ef.student_id INNER JOIN courses c ON c.id=ef.course_id INNER JOIN academic_year ay ON ay.id=c.academic_year_id WHERE ef.id=? AND s.school_id=? LIMIT 1');$s->bind_param('ii',$id,$school);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return $r?:null;}

$school=(int)($_SESSION['login_school_id']??0); $user=(int)($_SESSION['login_id']??0); $type=(int)($_SESSION['login_type']??0); $action=$_GET['action']??'';
if(!$school||!$user||$type!==1) dfResponse(['status'=>0,'message'=>'No tiene permisos para gestionar deudas.'],403);
if(!dfReady($conn)) dfResponse(['status'=>0,'migration_required'=>true,'message'=>'Ejecute sql/fees_module_upgrade.sql antes de utilizar el módulo.'],409);
$writes=['save','bulk_assign','bulk_action']; if(in_array($action,$writes,true)){ $sent=(string)($_POST['csrf_token']??'');$saved=(string)($_SESSION['csrf_token']??'');if(!$sent||!$saved||!hash_equals($saved,$sent))dfResponse(['status'=>0,'message'=>'La sesión de seguridad venció. Recargue la página.'],403); }

if($action==='save'){
    $id=(int)($_POST['id']??0);$isEdit=$id>0;$student=(int)($_POST['student_id']??0);$course=(int)($_POST['course_id']??0);$due=trim($_POST['due_date']??'');
    $s=$conn->prepare("SELECT s.nivel,s.grado,s.status student_status,c.total_amount,c.level,c.grades,c.concept_status,c.academic_year_id,ay.status year_status FROM student s INNER JOIN courses c ON c.id=? INNER JOIN academic_year ay ON ay.id=c.academic_year_id WHERE s.id=? AND s.school_id=? AND ay.school_id=? LIMIT 1");$s->bind_param('iiii',$course,$student,$school,$school);$s->execute();$ctx=$s->get_result()->fetch_assoc();$s->close();
    if(!$ctx)dfResponse(['status'=>0,'message'=>'El estudiante o concepto no pertenece a la institución.']);if($ctx['student_status']!=='Activo')dfResponse(['status'=>0,'message'=>'Solo se pueden asignar deudas a estudiantes activos.']);if($ctx['concept_status']!=='Activo')dfResponse(['status'=>0,'message'=>'El concepto está suspendido o archivado.']);if($ctx['year_status']!=='Activo')dfResponse(['status'=>0,'message'=>'Solo se pueden modificar deudas del año académico activo.']);
    $grades=array_filter(array_map('trim',explode(',',(string)$ctx['grades'])));if($ctx['level']!==$ctx['nivel']||($grades&&!in_array($ctx['grado'],$grades,true)))dfResponse(['status'=>0,'message'=>'El concepto no corresponde al nivel y grado del estudiante.']);
    $dup=$conn->prepare('SELECT id FROM student_ef_list WHERE student_id=? AND course_id=? AND id<>? AND debt_status<>\'Anulada\' LIMIT 1');$dup->bind_param('iii',$student,$course,$id);$dup->execute();$duplicate=$dup->get_result()->fetch_assoc();$dup->close();if($duplicate)dfResponse(['status'=>2,'message'=>'El estudiante ya tiene este concepto asignado.']);
    $amount=(float)$ctx['total_amount'];$year=(int)$ctx['academic_year_id'];$issue=date('Y-m-d');$due=$due?:null;
    if($id){$old=dfDebt($conn,$id,$school);if(!$old)dfResponse(['status'=>0,'message'=>'Deuda no encontrada.'],404);if((float)$old['paid']>0||!empty($old['comprobante_id']))dfResponse(['status'=>0,'message'=>'Una deuda con pagos o comprobante no puede cambiar de estudiante o concepto.']);$s=$conn->prepare('UPDATE student_ef_list SET student_id=?,course_id=?,total_fee=?,due_date=? WHERE id=?');$s->bind_param('iidsi',$student,$course,$amount,$due,$id);$ok=$s->execute();$s->close();}
    else{$s=$conn->prepare("INSERT INTO student_ef_list(student_id,course_id,total_fee,debt_status,issue_date,due_date) VALUES(?,?,?,'Activa',?,?)");$s->bind_param('iidss',$student,$course,$amount,$issue,$due);$ok=$s->execute();$id=$s->insert_id;$s->close();}
    if(!$ok)dfResponse(['status'=>0,'message'=>'No se pudo guardar la deuda.']);dfAudit($conn,$school,$id,$student,$course,$year,$isEdit?'debt_updated':'debt_created',['amount'=>$amount,'due_date'=>$due]);dfResponse(['status'=>1,'message'=>'Deuda guardada correctamente.']);
}
if($action==='bulk_assign'){
    $students=$_POST['students']??[];$courses=$_POST['concepts']??[];$students=array_values(array_unique(array_filter(array_map('intval',is_array($students)?$students:[]))));$courses=array_values(array_unique(array_filter(array_map('intval',is_array($courses)?$courses:[]))));$due=trim($_POST['due_date']??'');$period=trim($_POST['billing_period']??'');
    if(!$students||!$courses||count($students)*count($courses)>1000)dfResponse(['status'=>0,'message'=>'Seleccione estudiantes y conceptos (máximo 1000 combinaciones).']);
    $inserted=0;$duplicates=0;$incompatible=0;$conn->begin_transaction();try{
        $studentStmt=$conn->prepare("SELECT nivel,grado,status FROM student WHERE id=? AND school_id=? LIMIT 1");$courseStmt=$conn->prepare("SELECT c.total_amount,c.level,c.grades,c.concept_status,c.academic_year_id,ay.status year_status FROM courses c INNER JOIN academic_year ay ON ay.id=c.academic_year_id WHERE c.id=? AND ay.school_id=? LIMIT 1");$dupStmt=$conn->prepare("SELECT id FROM student_ef_list WHERE student_id=? AND course_id=? AND debt_status<>'Anulada' LIMIT 1");$ins=$conn->prepare("INSERT INTO student_ef_list(student_id,course_id,total_fee,debt_status,issue_date,due_date,billing_period) VALUES(?,?,?,'Activa',CURDATE(),?,?)");
        foreach($students as $student){$studentStmt->bind_param('ii',$student,$school);$studentStmt->execute();$st=$studentStmt->get_result()->fetch_assoc();if(!$st||$st['status']!=='Activo'){$incompatible+=count($courses);continue;}foreach($courses as $course){$courseStmt->bind_param('ii',$course,$school);$courseStmt->execute();$co=$courseStmt->get_result()->fetch_assoc();$grades=$co?array_filter(array_map('trim',explode(',',(string)$co['grades']))):[];if(!$co||$co['concept_status']!=='Activo'||$co['year_status']!=='Activo'||$co['level']!==$st['nivel']||($grades&&!in_array($st['grado'],$grades,true))){$incompatible++;continue;}$dupStmt->bind_param('ii',$student,$course);$dupStmt->execute();if($dupStmt->get_result()->fetch_assoc()){$duplicates++;continue;}$amount=(float)$co['total_amount'];$dueVal=$due?:null;$periodVal=$period?:null;$ins->bind_param('iidss',$student,$course,$amount,$dueVal,$periodVal);if(!$ins->execute())throw new Exception($ins->error);$debt=$ins->insert_id;$inserted++;dfAudit($conn,$school,$debt,$student,$course,(int)$co['academic_year_id'],'debt_bulk_created',['amount'=>$amount,'due_date'=>$dueVal,'period'=>$periodVal]);}}
        $studentStmt->close();$courseStmt->close();$dupStmt->close();$ins->close();$conn->commit();
    }catch(Throwable $e){$conn->rollback();error_log('[fees] bulk assign: '.$e->getMessage());dfResponse(['status'=>0,'message'=>'No se pudo completar la asignación masiva.']);}
    dfResponse(['status'=>$inserted?1:0,'inserted'=>$inserted,'duplicates'=>$duplicates,'incompatible'=>$incompatible,'message'=>"Se crearon $inserted deudas. $duplicates duplicadas y $incompatible incompatibles fueron omitidas."]);
}
if($action==='bulk_action'){
    $ids=json_decode($_POST['ids']??'[]',true);$ids=array_values(array_unique(array_filter(array_map('intval',is_array($ids)?$ids:[]))));$operation=trim($_POST['operation']??'');$reason=trim($_POST['reason']??'');$due=trim($_POST['due_date']??'');
    if(!$ids||count($ids)>200||!in_array($operation,['suspend','activate','cancel','due_date','delete'],true))dfResponse(['status'=>0,'message'=>'Acción masiva inválida.']);if($operation==='cancel'&&strlen($reason)<3)dfResponse(['status'=>0,'message'=>'Indique el motivo de anulación.']);if($operation==='due_date'&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$due))dfResponse(['status'=>0,'message'=>'Indique una fecha de vencimiento válida.']);
    $processed=0;$skipped=0;$errors=[];$conn->begin_transaction();try{foreach($ids as $id){$d=dfDebt($conn,$id,$school);if(!$d||$d['year_status']!=='Activo'){$skipped++;continue;}$paid=(float)$d['paid'];$hasHistory=$paid>0||!empty($d['comprobante_id'])||!empty($d['discounted_amount']);
        if($operation==='delete'){if($hasHistory){$skipped++;continue;}$s=$conn->prepare('DELETE FROM student_ef_list WHERE id=?');$s->bind_param('i',$id);}
        elseif($operation==='cancel'){$s=$conn->prepare("UPDATE student_ef_list SET debt_status='Anulada',cancelled_at=NOW(),cancelled_by=?,cancellation_reason=? WHERE id=?");$s->bind_param('isi',$user,$reason,$id);}
        elseif($operation==='suspend'){$s=$conn->prepare("UPDATE student_ef_list SET debt_status='Suspendida' WHERE id=? AND debt_status='Activa'");$s->bind_param('i',$id);}
        elseif($operation==='activate'){$s=$conn->prepare("UPDATE student_ef_list SET debt_status='Activa',cancelled_at=NULL,cancelled_by=NULL,cancellation_reason=NULL WHERE id=? AND debt_status IN('Suspendida','Anulada')");$s->bind_param('i',$id);}
        else{$s=$conn->prepare('UPDATE student_ef_list SET due_date=? WHERE id=?');$s->bind_param('si',$due,$id);}if(!$s->execute())throw new Exception($s->error);if($s->affected_rows)$processed++;else$skipped++;$s->close();dfAudit($conn,$school,$id,(int)$d['student_id'],(int)$d['course_id'],(int)$d['academic_year_id'],'debt_'.$operation,['reason'=>$reason,'due_date'=>$due]);} $conn->commit();}catch(Throwable $e){$conn->rollback();error_log('[fees] bulk: '.$e->getMessage());dfResponse(['status'=>0,'message'=>'No se pudo completar la acción masiva.']);}dfResponse(['status'=>1,'processed'=>$processed,'skipped'=>$skipped,'message'=>"Se procesaron $processed deudas.".($skipped?" $skipped fueron omitidas por seguridad.":'')]);
}
if($action==='audit'){$year=(int)($_GET['academic_year_id']??0);$s=$conn->prepare("SELECT l.*,COALESCE(u.name,'Sistema') user_name,COALESCE(st.name,'Estudiante eliminado') student_name,COALESCE(c.course,'Concepto eliminado') concept_name FROM debt_audit_log l LEFT JOIN users u ON u.id=l.user_id LEFT JOIN student st ON st.id=l.student_id LEFT JOIN courses c ON c.id=l.course_id WHERE l.school_id=? AND(l.academic_year_id=? OR ?=0) ORDER BY l.created_at DESC LIMIT 150");$s->bind_param('iii',$school,$year,$year);$s->execute();$items=[];$r=$s->get_result();while($x=$r->fetch_assoc())$items[]=$x;$s->close();dfResponse(['status'=>1,'audit'=>$items]);}
dfResponse(['status'=>0,'message'=>'Acción no reconocida.'],404);
