<?php
ob_start(); date_default_timezone_set('America/Lima');
include_once __DIR__.'/includes/session_check.php'; require_login_modal(); include __DIR__.'/db_connect.php';
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('Pragma: no-cache');
function ho($d,$c=200){while(ob_get_level())ob_end_clean();http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function ht($db,$t){$t=$db->real_escape_string($t);$q=$db->query("SHOW TABLES LIKE '$t'");return $q&&$q->num_rows;}
function hv($db,$sql,$f='total'){try{$q=$db->query($sql);$r=$q?$q->fetch_assoc():[];return(float)($r[$f]??0);}catch(Throwable $e){return 0;}}
function hr($db,$sql){$a=[];try{$q=$db->query($sql);while($q&&($r=$q->fetch_assoc()))$a[]=$r;}catch(Throwable $e){}return $a;}
function hm($n){return'S/ '.number_format((float)$n,2,'.',',');}
$school=(int)($_SESSION['login_school_id']??0);$uid=(int)($_SESSION['login_id']??0);if(!$school)ho(['status'=>0,'message'=>'No existe un colegio activo en la sesión.'],403);
$role=null;$studentId=0;if(!empty($_SESSION['student_logged_in'])){$studentId=(int)($_SESSION['student_id']??$uid);$s=$conn->prepare('SELECT id,name FROM student WHERE id=? AND school_id=? LIMIT 1');$s->bind_param('ii',$studentId,$school);$s->execute();$st=$s->get_result()->fetch_assoc();$s->close();if($st)$role=['type'=>4,'is_director'=>0,'teacher_id'=>0,'name'=>$st['name']];}elseif($uid){$s=$conn->prepare('SELECT type,is_director,teacher_id,name FROM users WHERE id=? AND school_id=? LIMIT 1');if($s){$s->bind_param('ii',$uid,$school);$s->execute();$role=$s->get_result()->fetch_assoc();$s->close();}}
if(!$role)ho(['status'=>0,'message'=>'El usuario no pertenece al colegio activo.'],403);
$type=(int)$role['type'];$director=(int)$role['is_director']===1;$admin=$type===1;$teacher=(int)($role['teacher_id']??0);
$sc=hr($conn,"SELECT id,name,address,contact_number,email,logo_path FROM schools WHERE id=$school LIMIT 1");if(!$sc)ho(['status'=>0,'message'=>'El colegio no existe.'],403);$yr=hr($conn,"SELECT id,year,status,start_date,end_date FROM academic_year WHERE school_id=$school AND is_active=1 ORDER BY id DESC LIMIT 1");$year=$yr?$yr[0]:null;$yearId=(int)($year['id']??0);
$metrics=[];$pending=[];$activity=[];$charts=[];$actions=[];$analysis=[];$metric=function($l,$v,$i,$t,$u)use(&$metrics){$metrics[]=['label'=>$l,'value'=>$v,'icon'=>$i,'tone'=>$t,'url'=>$u];};$pend=function($t,$d,$c,$tone,$u)use(&$pending){if((float)$c>0)$pending[]=compact('t','d','c','tone','u');};
$payFilter="WHERE COALESCE(payment_status,'Confirmado')<>'Anulado' GROUP BY ef_id";$debtBase="SELECT COALESCE(SUM(GREATEST(0,(CASE WHEN ef.discounted_amount IS NOT NULL THEN ef.discounted_amount ELSE ef.total_fee END)-COALESCE(pp.paid,0))),0) total FROM student_ef_list ef INNER JOIN student s ON s.id=ef.student_id LEFT JOIN (SELECT ef_id,SUM(amount) paid FROM payments $payFilter) pp ON pp.ef_id=ef.id WHERE s.school_id=$school AND COALESCE(ef.debt_status,'Activa') NOT IN ('Anulada','Cancelada')";
if($director){$actions=$teacher>0?[['Mis cursos','fa-book','my_courses'],['Registrar notas','fa-clipboard-list','grades'],['Competencias','fa-star-half-alt','competencias'],['Reporte de notas','fa-chart-line','grades_report']]:[];
}elseif($admin){
 $students=(int)hv($conn,"SELECT COUNT(*) total FROM student WHERE school_id=$school AND status='Activo'");$teachers=(int)hv($conn,"SELECT COUNT(*) total FROM teacher WHERE school_id=$school AND status='Activo'");
 $today=ht($conn,'payment_operations')?hv($conn,"SELECT COALESCE(SUM(total_amount),0) total FROM payment_operations WHERE school_id=$school AND status='Confirmado' AND DATE(payment_date)=CURDATE()"):0;$month=ht($conn,'payment_operations')?hv($conn,"SELECT COALESCE(SUM(total_amount),0) total FROM payment_operations WHERE school_id=$school AND status='Confirmado' AND YEAR(payment_date)=YEAR(CURDATE()) AND MONTH(payment_date)=MONTH(CURDATE())"):0;$debt=hv($conn,$debtBase);$overdue=hv($conn,$debtBase." AND ef.due_date IS NOT NULL AND ef.due_date<CURDATE()");
 $a=hr($conn,"SELECT SUM(estado='Presente') present,SUM(estado='Tarde') late,SUM(estado LIKE 'Ausente%') absent FROM asistencia WHERE school_id=$school AND fecha=CURDATE() AND COALESCE(is_cancelled,0)=0");$a=$a?$a[0]:[];$requests=ht($conn,'attendance_change_requests')?(int)hv($conn,"SELECT COUNT(*) total FROM attendance_change_requests WHERE school_id=$school AND status='Pendiente'"):0;
 $metric('Estudiantes activos',number_format($students),'fa-user-graduate','primary','index.php?page=students');$metric('Docentes activos',number_format($teachers),'fa-chalkboard-teacher','primary','index.php?page=teachers');$metric('Recaudado hoy',hm($today),'fa-cash-register','success','index.php?page=payments');$metric('Recaudado este mes',hm($month),'fa-chart-line','primary','index.php?page=payments_report');$metric('Saldo pendiente',hm($debt),'fa-file-invoice-dollar','warning','index.php?page=debt_reports');$metric('Deuda vencida',hm($overdue),'fa-exclamation-circle','danger','index.php?page=debt_reports');$metric('Presentes hoy',number_format((int)($a['present']??0)),'fa-user-check','success','index.php?page=attendance_report');$metric('Tardanzas / ausencias',number_format((int)($a['late']??0)+(int)($a['absent']??0)),'fa-clock','warning','index.php?page=attendance_report');
 $pend('Solicitudes de asistencia','Cambios que requieren autorización',$requests,'warning','index.php?page=notifications');$pend('Deudas vencidas','Saldo vencido pendiente de cobro',$overdue,'danger','index.php?page=debt_reports');$incomplete=(int)hv($conn,"SELECT COUNT(*) total FROM student WHERE school_id=$school AND status='Activo' AND (COALESCE(grado,'')='' OR COALESCE(seccion,'')='')");$unassigned=$yearId?(int)hv($conn,"SELECT COUNT(*) total FROM teacher t WHERE t.school_id=$school AND t.status='Activo' AND NOT EXISTS(SELECT 1 FROM teacher_courses tc WHERE tc.teacher_id=t.id AND tc.school_id=$school AND tc.academic_year_id=$yearId)"):0;$pend('Estudiantes incompletos','Activos sin grado o sección',$incomplete,'warning','index.php?page=students');$pend('Docentes sin asignación','Sin cursos en el año activo',$unassigned,'primary','index.php?page=teacher_courses');
 if(ht($conn,'payment_operations'))$activity=array_merge($activity,hr($conn,"SELECT payment_date event_date,CONCAT('Pago ',receipt_full) title,CONCAT(s.name,' · S/ ',FORMAT(total_amount,2)) detail,'payment' kind FROM payment_operations po INNER JOIN student s ON s.id=po.student_id AND s.school_id=po.school_id WHERE po.school_id=$school ORDER BY payment_date DESC LIMIT 5"));if(ht($conn,'attendance_change_requests'))$activity=array_merge($activity,hr($conn,"SELECT COALESCE(reviewed_at,r.created_at) event_date,CONCAT('Solicitud de asistencia ',LOWER(status)) title,CONCAT(request_type,' · ',u.name) detail,'attendance' kind FROM attendance_change_requests r INNER JOIN users u ON u.id=r.requested_by AND u.school_id=r.school_id WHERE r.school_id=$school ORDER BY COALESCE(reviewed_at,r.created_at) DESC LIMIT 5"));
 $series=[];$monthBase=date('Y-m-01');for($i=5;$i>=0;$i--){$k=date('Y-m',strtotime($monthBase." -$i months"));$series[$k]=['label'=>date('M',strtotime($k.'-01')),'value'=>0];}if(ht($conn,'payment_operations'))foreach(hr($conn,"SELECT DATE_FORMAT(payment_date,'%Y-%m') ym,SUM(total_amount) total FROM payment_operations WHERE school_id=$school AND status='Confirmado' AND payment_date>=DATE_SUB(DATE_FORMAT(CURDATE(),'%Y-%m-01'),INTERVAL 5 MONTH) GROUP BY ym")as$r)if(isset($series[$r['ym']]))$series[$r['ym']]['value']=(float)$r['total'];$charts=['payments'=>array_values($series)];
 $analysis['enrollment']=['levels'=>hr($conn,"SELECT nivel label,COUNT(*) value FROM student WHERE school_id=$school AND status='Activo' GROUP BY nivel ORDER BY FIELD(nivel,'Inicial','Primaria','Secundaria')"),'classrooms'=>hr($conn,"SELECT nivel,grado,seccion,COUNT(*) students FROM student WHERE school_id=$school AND status='Activo' GROUP BY nivel,grado,seccion ORDER BY FIELD(nivel,'Inicial','Primaria','Secundaria'),grado,seccion")];
 $analysis['teachers']=['summary'=>[['label'=>'Activos','value'=>$teachers],['label'=>'Sin asignación','value'=>$unassigned]],'loads'=>$yearId?hr($conn,"SELECT t.name,COUNT(tc.id) assignments FROM teacher t LEFT JOIN teacher_courses tc ON tc.teacher_id=t.id AND tc.school_id=$school AND tc.academic_year_id=$yearId WHERE t.school_id=$school AND t.status='Activo' GROUP BY t.id,t.name ORDER BY assignments DESC,t.name LIMIT 30"):[]];
 $analysis['attendance']=hr($conn,"SELECT fecha label,SUM(estado='Presente') present,SUM(estado='Tarde') late,SUM(estado LIKE 'Ausente%') absent FROM asistencia WHERE school_id=$school AND fecha>=DATE_SUB(CURDATE(),INTERVAL 6 DAY) AND COALESCE(is_cancelled,0)=0 GROUP BY fecha ORDER BY fecha");
 $analysis['academic']=['courses'=>$yearId?(int)hv($conn,"SELECT COUNT(*) total FROM teacher_courses WHERE school_id=$school AND academic_year_id=$yearId"):0,'evaluations'=>$yearId?(int)hv($conn,"SELECT COUNT(*) total FROM evaluations e INNER JOIN teacher_courses tc ON tc.id=e.teacher_course_id WHERE tc.school_id=$school AND e.academic_year_id=$yearId"):0,'alerts'=>ht($conn,'low_grade_notifications')?(int)hv($conn,"SELECT COUNT(*) total FROM low_grade_notifications l INNER JOIN student s ON s.id=l.student_id WHERE s.school_id=$school"):0];
 $analysis['finance']=['month'=>$month,'pending'=>$debt,'overdue'=>$overdue,'methods'=>(ht($conn,'payment_operation_methods')?hr($conn,"SELECT pm.name label,SUM(pom.amount) value FROM payment_operation_methods pom INNER JOIN payment_operations po ON po.id=pom.operation_id INNER JOIN payment_methods pm ON pm.id=pom.payment_method_id WHERE po.school_id=$school AND po.status='Confirmado' AND YEAR(po.payment_date)=YEAR(CURDATE()) AND MONTH(po.payment_date)=MONTH(CURDATE()) GROUP BY pm.id,pm.name ORDER BY value DESC"):[])];
 $actions=[['Registrar pago','fa-plus','payments'],['Asignar deuda','fa-file-invoice','fees'],['Nuevo estudiante','fa-user-plus','students'],['Tomar asistencia','fa-calendar-check','asistencia'],['Reporte de caja','fa-cash-register','payments'],['Ver reportes','fa-chart-bar','fichas_reportes']];
}elseif($type===2){$courses=$yearId?(int)hv($conn,"SELECT COUNT(*) total FROM teacher_courses WHERE school_id=$school AND teacher_id=$teacher AND academic_year_id=$yearId"):0;$evaluations=$yearId?(int)hv($conn,"SELECT COUNT(*) total FROM evaluations WHERE teacher_id=$teacher AND academic_year_id=$yearId"):0;$alerts=ht($conn,'low_grade_notifications')?(int)hv($conn,"SELECT COUNT(*) total FROM low_grade_notifications l JOIN student s ON s.id=l.student_id WHERE s.school_id=$school AND l.teacher_id=$teacher"):0;$metric('Mis cursos',$courses,'fa-book','primary','index.php?page=my_courses');$metric('Evaluaciones',$evaluations,'fa-clipboard-list','primary','index.php?page=grades');$metric('Alertas académicas',$alerts,'fa-exclamation-triangle','warning','index.php?page=notifications');$pend('Alertas académicas','Estudiantes que requieren seguimiento',$alerts,'warning','index.php?page=notifications');$actions=[['Mis cursos','fa-book','my_courses'],['Registrar notas','fa-clipboard-list','grades'],['Competencias','fa-star-half-alt','competencias'],['Reporte de notas','fa-chart-line','grades_report']];
}elseif($type===3){$a=hr($conn,"SELECT COUNT(*) total,SUM(estado='Presente') present,SUM(estado='Tarde') late,SUM(estado LIKE 'Ausente%') absent FROM asistencia WHERE school_id=$school AND fecha=CURDATE() AND COALESCE(is_cancelled,0)=0");$a=$a?$a[0]:[];$own=ht($conn,'attendance_change_requests')?(int)hv($conn,"SELECT COUNT(*) total FROM attendance_change_requests WHERE school_id=$school AND requested_by=$uid AND status='Pendiente'"):0;foreach([['Registros de hoy',$a['total']??0,'fa-calendar-check','primary'],['Presentes',$a['present']??0,'fa-user-check','success'],['Tardanzas',$a['late']??0,'fa-clock','warning'],['Ausencias',$a['absent']??0,'fa-user-times','danger']]as$m)$metric($m[0],$m[1],$m[2],$m[3],'index.php?page=attendance_report');$metric('Mis solicitudes',$own,'fa-hourglass-half','warning','index.php?page=notifications');$pend('Solicitudes pendientes','Esperan decisión de administración',$own,'warning','index.php?page=notifications');$actions=[['Tomar asistencia','fa-calendar-check','asistencia'],['Reglas','fa-cogs','attendance_rules_page'],['Reporte','fa-chart-bar','attendance_report'],['Notificaciones','fa-bell','notifications']];
}else{$studentId=$studentId?:$uid;$st=hr($conn,"SELECT id FROM student WHERE id=$studentId AND school_id=$school LIMIT 1");if(!$st)ho(['status'=>0,'message'=>'No se encontró el estudiante.'],403);$debt=hv($conn,str_replace("INNER JOIN student s ON s.id=ef.student_id","INNER JOIN student s ON s.id=ef.student_id AND s.id=$studentId",$debtBase));$overdue=hv($conn,str_replace("INNER JOIN student s ON s.id=ef.student_id","INNER JOIN student s ON s.id=ef.student_id AND s.id=$studentId",$debtBase)." AND ef.due_date<CURDATE()");$att=(int)hv($conn,"SELECT COUNT(*) total FROM asistencia WHERE school_id=$school AND student_id=$studentId AND YEAR(fecha)=YEAR(CURDATE()) AND MONTH(fecha)=MONTH(CURDATE()) AND COALESCE(is_cancelled,0)=0");$abs=(int)hv($conn,"SELECT COUNT(*) total FROM asistencia WHERE school_id=$school AND student_id=$studentId AND YEAR(fecha)=YEAR(CURDATE()) AND MONTH(fecha)=MONTH(CURDATE()) AND estado LIKE 'Ausente%' AND COALESCE(is_cancelled,0)=0");$metric('Deuda pendiente',hm($debt),'fa-file-invoice-dollar','warning','index.php?page=student_debts');$metric('Deuda vencida',hm($overdue),'fa-exclamation-circle','danger','index.php?page=student_debts');$metric('Asistencias del mes',$att,'fa-calendar-check','primary','index.php?page=student_attendances');$metric('Ausencias del mes',$abs,'fa-user-times','warning','index.php?page=student_attendances');$pend('Deuda vencida','Importe que requiere regularización',$overdue,'danger','index.php?page=student_debts');$actions=[['Mis notas','fa-clipboard-list','student_grades'],['Mi asistencia','fa-calendar-check','student_attendances'],['Mis pagos','fa-receipt','student_payments'],['Mis deudas','fa-file-invoice-dollar','student_debts']];}
foreach($actions as&$a)$a=['label'=>$a[0],'icon'=>$a[1],'url'=>'index.php?page='.$a[2]];unset($a);usort($activity,fn($a,$b)=>strcmp($b['event_date']??'',$a['event_date']??''));$activity=array_slice($activity,0,7);$roleName=$director?'Director':($admin?'Administrador':($type===2?'Docente':($type===3?'Auxiliar':'Estudiante')));
ho(['status'=>1,'school'=>$sc[0],'user'=>['name'=>$role['name'],'role'=>$roleName],'year'=>$year,'metrics'=>$metrics,'pending'=>$pending,'activity'=>$activity,'charts'=>$charts,'analysis'=>$analysis,'actions'=>$actions,'updated_at'=>date('d/m/Y H:i')]);
