<?php
include_once __DIR__.'/includes/session_check.php'; require_login_modal(); include __DIR__.'/db_connect.php';
$schoolId=(int)($_SESSION['login_school_id']??0);$id=(int)($_GET['id']??0);$data=[];
if($id){$stmt=$conn->prepare('SELECT * FROM academic_courses WHERE id=? AND school_id=?');$stmt->bind_param('ii',$id,$schoolId);$stmt->execute();$data=$stmt->get_result()->fetch_assoc()?:[];$stmt->close();}
$yearId=(int)($data['academic_year_id']??($_GET['academic_year_id']??0));if(!$yearId){$q=$conn->query("SELECT id FROM academic_year WHERE school_id=$schoolId AND is_active=1 LIMIT 1");if($q&&$q->num_rows)$yearId=(int)$q->fetch_assoc()['id'];}
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$selectedGrades=array_values(array_filter(array_map('trim',explode(',',$data['grades']??''))));
?>
<style>.mc-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.mc-grid .wide{grid-column:1/-1}.form-group label{font-weight:600;color:#34495e}.mc-note{background:#f3f7ff;border-left:4px solid #4285f4;padding:10px 12px;border-radius:6px}@media(max-width:700px){.mc-grid{grid-template-columns:1fr}.mc-grid .wide{grid-column:auto}}</style>
<div class="container-fluid"><form id="manage-course"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="academic_year_id" value="<?=$yearId?>"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($_SESSION['csrf_token'])?>"><div id="course-msg"></div><div class="mc-grid">
<div class="form-group"><label>Nombre <span class="text-danger">*</span></label><input name="name" class="form-control" required value="<?=htmlspecialchars($data['name']??'')?>"></div>
<div class="form-group"><label>Código interno</label><input name="course_code" maxlength="30" class="form-control" value="<?=htmlspecialchars($data['course_code']??'')?>" placeholder="Ej. MAT-PRI"></div>
<div class="form-group"><label>Área <span class="text-danger">*</span></label><select name="area_id" class="form-control" required><option value="">Selecciona un área</option><?php $q=$conn->query("SELECT id,name FROM areas WHERE school_id=$schoolId AND is_active=1 AND (academic_year_id=$yearId OR academic_year_id IS NULL) ORDER BY name");while($q&&($a=$q->fetch_assoc())):?><option value="<?=$a['id']?>" <?=(int)($data['area_id']??0)===(int)$a['id']?'selected':''?>><?=htmlspecialchars($a['name'])?></option><?php endwhile?></select></div>
<div class="form-group"><label>Nivel <span class="text-danger">*</span></label><select id="mc-level" name="level" class="form-control" required><option value="">Selecciona</option><?php foreach(['Inicial','Primaria','Secundaria'] as $v):?><option <?=($data['level']??'')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></div>
<div class="form-group"><label>Grados</label><select id="mc-grades" name="grades[]" class="form-control" multiple size="5"></select><small class="text-muted">Ctrl/Cmd para seleccionar varios.</small></div>
<div><div class="form-group"><label>Horas semanales</label><input name="weekly_hours" type="number" min="0" step="0.5" class="form-control" value="<?=htmlspecialchars($data['weekly_hours']??'0')?>"></div><div class="form-group"><label>Orden</label><input name="display_order" type="number" min="0" class="form-control" value="<?=(int)($data['display_order']??0)?>"></div></div>
<div class="form-group"><label>Tipo</label><select name="course_type" class="form-control"><?php foreach(['Curso','Taller','Tutoría','Actividad'] as $v):?><option <?=($data['course_type']??'Curso')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></div>
<div class="form-group"><label>Estado</label><select name="course_status" class="form-control"><option value="Activo" <?=($data['course_status']??'Activo')==='Activo'?'selected':''?>>Activo — disponible para nuevas asignaciones</option><option value="Suspendido" <?=($data['course_status']??'')==='Suspendido'?'selected':''?>>Suspendido — pausa temporal</option><option value="Inactivo" <?=($data['course_status']??'')==='Inactivo'?'selected':''?>>Inactivo — solo historial</option></select></div>
<div class="form-group wide"><label>Descripción</label><textarea name="description" rows="3" class="form-control"><?=htmlspecialchars($data['description']??'')?></textarea></div>
<div class="wide mc-note"><i class="fa fa-info-circle mr-1"></i>El curso quedará asociado al año académico seleccionado y conservará su historial en años posteriores.</div></div>
<div class="text-right mt-3"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button> <button class="btn btn-primary" type="submit"><i class="fa fa-save mr-1"></i>Guardar</button></div></form></div>
<script>(function($){var selected=<?=json_encode($selectedGrades,JSON_UNESCAPED_UNICODE)?>;function fill(reset){var m={Inicial:['3 años','4 años','5 años'],Primaria:['1°','2°','3°','4°','5°','6°'],Secundaria:['1°','2°','3°','4°','5°']},a=m[$('#mc-level').val()]||[];if(reset)selected=[];$('#mc-grades').html(a.map(function(g){return '<option value="'+g+'">'+g+'</option>'}).join('')).val(selected)}$('#mc-level').change(function(){fill(true)});fill(false);$('#manage-course').submit(function(e){e.preventDefault();start_load();$.ajax({url:'academic_management_api.php?action=save_course',method:'POST',data:$(this).serialize(),dataType:'json'}).done(function(r){if(r.status==1){alert_toast(r.message,'success');$(document).trigger('academic:changed');$('#uni_modal').modal('hide')}else $('#course-msg').html('<div class="alert alert-danger">'+(r.message||'No se pudo guardar.')+'</div>')}).fail(function(x){$('#course-msg').html('<div class="alert alert-danger">'+((x.responseJSON||{}).message||'Error del servidor.')+'</div>')}).always(end_load)})})(jQuery);</script>
