<?php
include_once __DIR__.'/includes/session_check.php';require_login_modal();include __DIR__.'/db_connect.php';
if(empty($_SESSION['login_id'])||(int)($_SESSION['login_type']??0)!==1){echo '<div class="alert alert-danger m-3">No autorizado.</div>';exit;}
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$school=(int)($_SESSION['login_school_id']??0);$id=(int)($_GET['id']??0);$years=[];$s=$conn->prepare("SELECT id,year,is_active,status FROM academic_year WHERE school_id=? AND status IN('Borrador','Activo') ORDER BY is_active DESC,year DESC");$s->bind_param('i',$school);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$years[]=$x;$s->close();
?>
<style>.mc-section{border:1px solid #e3e8f0;border-radius:10px;padding:14px;margin-bottom:14px}.mc-section-title{font-weight:700;color:#29445d;margin-bottom:12px}.mc-grades{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mc-grade{border:1px solid #e1e7ef;border-radius:8px;padding:8px 10px;background:#f8fafc}@media(max-width:575px){.mc-grades{grid-template-columns:repeat(2,1fr)}}</style>
<form id="concept-form" class="p-3"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['csrf_token'],ENT_QUOTES,'UTF-8'); ?>"><input type="hidden" name="id" value="<?php echo $id; ?>"><div id="concept-msg"></div>
 <div class="mc-section"><div class="mc-section-title"><i class="fa fa-file-invoice-dollar text-primary mr-2"></i>Información del concepto</div><div class="form-group"><label>Nombre <span class="text-danger">*</span></label><input class="form-control" name="course" id="mc-name" maxlength="150" placeholder="Ej. Pensión mensual" required></div><div class="form-group mb-0"><label>Descripción</label><textarea class="form-control" name="description" id="mc-description" rows="2"></textarea></div></div>
 <div class="mc-section"><div class="mc-section-title"><i class="fa fa-users text-info mr-2"></i>Aplicación académica</div><div class="form-row"><div class="form-group col-md-6"><label>Año académico <span class="text-danger">*</span></label><select class="form-control" name="academic_year_id" id="mc-year" required><option value="">Seleccione</option><?php foreach($years as $y): ?><option value="<?php echo (int)$y['id']; ?>"><?php echo htmlspecialchars($y['year'].($y['is_active']?' (Activo)':' (Borrador)')); ?></option><?php endforeach; ?></select></div><div class="form-group col-md-6"><label>Nivel <span class="text-danger">*</span></label><select class="form-control" name="level" id="mc-level" required><option value="">Seleccione</option><option>Inicial</option><option>Primaria</option><option>Secundaria</option></select></div></div><label>Grados <span class="text-danger">*</span></label><div id="mc-grades" class="mc-grades"><small class="text-muted">Seleccione un nivel.</small></div></div>
 <div class="mc-section"><div class="mc-section-title"><i class="fa fa-coins text-success mr-2"></i>Importe</div><div class="form-group mb-0"><label>Monto base (S/) <span class="text-danger">*</span></label><input type="number" class="form-control text-right" name="total_amount" id="mc-amount" min="0" step="0.01" value="0.00" required><small class="text-muted">Modificarlo no altera las deudas que ya fueron generadas.</small></div></div>
 <div class="text-right"><button type="button" class="btn btn-secondary mr-2" data-dismiss="modal">Cancelar</button><button class="btn btn-primary"><i class="fa fa-save mr-1"></i>Guardar</button></div>
</form>
<script>(function($){const id=<?php echo $id; ?>,map={Inicial:['3°','4°','5°'],Primaria:['1°','2°','3°','4°','5°','6°'],Secundaria:['1°','2°','3°','4°','5°']};let selected=[];
function esc(v){return $('<div>').text(v||'').html()}function grades(){let list=map[$('#mc-level').val()]||[];$('#mc-grades').html(list.length?list.map(g=>'<label class="mc-grade mb-0"><input type="checkbox" name="grades[]" value="'+esc(g)+'" '+(selected.includes(g)?'checked':'')+'> '+esc(g)+'</label>').join(''):'<small class="text-muted">Seleccione un nivel.</small>')}
$('#mc-level').on('change',function(){selected=[];grades()});if(id){$.getJSON('concepts_api.php',{action:'get',id:id}).done(function(r){if(r.status!=1){$('#concept-msg').html('<div class="alert alert-danger">'+esc(r.message)+'</div>');return}let c=r.concept;selected=c.normalized_grades||[];$('#mc-name').val(c.course);$('#mc-description').val(c.description);$('#mc-year').val(c.academic_year_id);$('#mc-level').val(c.level);$('#mc-amount').val(parseFloat(c.total_amount||0).toFixed(2));grades();if(+c.dependencies.deudas||+c.dependencies.pagos)$('#concept-msg').html('<div class="alert alert-info small">Este concepto tiene historial financiero. Los cambios no modificarán las deudas ni pagos existentes.</div>')}).fail(x=>$('#concept-msg').html('<div class="alert alert-danger">'+esc((x.responseJSON||{}).message||'No se pudo cargar.')+'</div>'))}
$('#concept-form').on('submit',function(e){e.preventDefault();if(!$(this).find('input[name="grades[]"]:checked').length){$('#concept-msg').html('<div class="alert alert-warning">Seleccione al menos un grado.</div>');return}start_load();$.ajax({url:'concepts_api.php?action=save',method:'POST',data:$(this).serialize(),dataType:'json'}).done(function(r){if(r.status==1){alert_toast(r.message,'success');$('#uni_modal').modal('hide');$(document).trigger('concepts:changed')}else $('#concept-msg').html('<div class="alert alert-danger">'+esc(r.message)+'</div>')}).fail(x=>$('#concept-msg').html('<div class="alert alert-danger">'+esc((x.responseJSON||{}).message||'Error del servidor.')+'</div>')).always(end_load)});})(jQuery);</script>
