<?php
include_once __DIR__.'/includes/session_check.php';require_login_modal();include __DIR__.'/db_connect.php';
$schoolId=(int)($_SESSION['login_school_id']??0);$courseId=(int)($_GET['course_id']??0);$yearId=(int)($_GET['academic_year_id']??0);
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$stmt=$conn->prepare('SELECT ac.name,ac.level,ay.year FROM academic_courses ac INNER JOIN academic_year ay ON ay.id=ac.academic_year_id WHERE ac.id=? AND ac.school_id=? AND ac.academic_year_id=?');$stmt->bind_param('iii',$courseId,$schoolId,$yearId);$stmt->execute();$course=$stmt->get_result()->fetch_assoc();$stmt->close();
if(!$course){echo '<div class="alert alert-danger">El curso no existe o pertenece a otro año académico.</div>';exit;}
?>
<style>.acomp-summary{background:#f4f7fc;border-left:4px solid #4285f4;border-radius:7px;padding:11px 13px}.acomp-inactive{opacity:.58}.acomp-table td{vertical-align:middle!important}</style>
<div class="container-fluid">
 <div class="acomp-summary mb-3"><strong><?php echo htmlspecialchars($course['name']); ?></strong><div class="small text-muted"><?php echo htmlspecialchars($course['level'].' · '.$course['year']); ?></div></div>
 <div id="acomp-msg"></div>
 <form id="acomp-form" class="border rounded p-3 mb-3">
  <input type="hidden" name="id" id="acomp-id"><input type="hidden" name="course_id" value="<?php echo $courseId; ?>"><input type="hidden" name="academic_year_id" value="<?php echo $yearId; ?>"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['csrf_token']); ?>">
  <div class="form-row"><div class="form-group col-md-4"><label class="font-weight-bold">Docente</label><select name="teacher_id" id="acomp-teacher" class="form-control" required><option value="">Seleccione</option></select></div><div class="form-group col-md-5"><label class="font-weight-bold">Competencia</label><input name="name" id="acomp-name" class="form-control" maxlength="255" required></div><div class="form-group col-md-3"><label class="font-weight-bold">Porcentaje</label><div class="input-group"><input name="percentage" id="acomp-percentage" class="form-control" type="number" min="0" max="100" step="0.01" value="0" required><div class="input-group-append"><span class="input-group-text">%</span></div></div></div></div>
  <div class="text-right"><button type="button" id="acomp-cancel" class="btn btn-sm btn-secondary d-none">Cancelar edición</button> <button class="btn btn-sm btn-primary"><i class="fa fa-save mr-1"></i>Guardar competencia</button></div>
 </form>
 <div class="table-responsive"><table class="table table-bordered table-hover acomp-table"><thead><tr><th>Docente</th><th>Competencia</th><th class="text-center">%</th><th class="text-center">Uso</th><th class="text-center">Estado</th><th class="text-center">Acciones</th></tr></thead><tbody id="acomp-body"><tr><td colspan="6" class="text-center"><i class="fa fa-spinner fa-spin"></i></td></tr></tbody></table></div>
</div>
<script>(function($){var api='academic_management_api.php',course=<?php echo $courseId; ?>,year=<?php echo $yearId; ?>,csrf=<?php echo json_encode($_SESSION['csrf_token']); ?>,items=[];function e(v){return $('<div>').text(v==null?'':v).html()}function reset(){document.getElementById('acomp-form').reset();$('#acomp-id').val('');$('#acomp-percentage').val('0');$('#acomp-cancel').addClass('d-none')}function load(){$.getJSON(api,{action:'competencies',course_id:course,academic_year_id:year}).done(function(r){items=r.competencies||[];$('#acomp-teacher').html('<option value="">Seleccione</option>'+(r.teachers||[]).map(t=>'<option value="'+t.id+'">'+e(t.name)+'</option>').join(''));if(!(r.teachers||[]).length)$('#acomp-msg').html('<div class="alert alert-warning">Primero debes asignar al menos un docente a este curso para registrar competencias.</div>');let h='';items.forEach(function(c){h+='<tr class="'+(+c.is_active?'':'acomp-inactive')+'"><td>'+e(c.teacher_name)+'</td><td>'+e(c.name)+'</td><td class="text-center">'+e(c.percentage)+'</td><td class="text-center"><span class="badge badge-info">'+c.usage_count+' evaluaciones</span></td><td class="text-center"><span class="badge badge-'+(+c.is_active?'success':'secondary')+'">'+(+c.is_active?'Activa':'Inactiva')+'</span></td><td class="text-center"><button class="btn btn-sm btn-outline-primary acomp-edit" data-id="'+c.id+'"><i class="fa fa-edit"></i></button> <button class="btn btn-sm btn-outline-'+(+c.is_active?'danger':'success')+' acomp-toggle" data-id="'+c.id+'" data-active="'+(+c.is_active?0:1)+'"><i class="fa fa-'+(+c.is_active?'ban':'check')+'"></i></button></td></tr>'});$('#acomp-body').html(h||'<tr><td colspan="6" class="text-center text-muted">No hay competencias registradas para este curso y año.</td></tr>')}).fail(x=>$('#acomp-msg').html('<div class="alert alert-danger">'+e((x.responseJSON||{}).message||'No se pudo cargar.')+'</div>'))}
$('#acomp-form').submit(function(x){x.preventDefault();start_load();$.post(api+'?action=save_competency',$(this).serialize(),null,'json').done(function(r){if(r.status==1){alert_toast(r.message,'success');reset();load();$(document).trigger('academic:changed')}else $('#acomp-msg').html('<div class="alert alert-danger">'+e(r.message)+'</div>')}).fail(x=>$('#acomp-msg').html('<div class="alert alert-danger">'+e((x.responseJSON||{}).message||'Error del servidor.')+'</div>')).always(end_load)});$(document).on('click','.acomp-edit',function(){let id=+$(this).data('id'),c=items.find(x=>+x.id===id);if(!c)return;$('#acomp-id').val(c.id);$('#acomp-teacher').val(c.teacher_id);$('#acomp-name').val(c.name);$('#acomp-percentage').val(c.percentage);$('#acomp-cancel').removeClass('d-none')});$('#acomp-cancel').click(reset);$(document).on('click','.acomp-toggle',function(){let id=$(this).data('id'),active=$(this).data('active');if(!confirm(active?'¿Reactivar esta competencia?':'¿Desactivar esta competencia? Las evaluaciones existentes conservarán su relación.'))return;start_load();$.post(api+'?action=toggle_competency',{id:id,is_active:active,academic_year_id:year,csrf_token:csrf},null,'json').done(function(r){alert_toast(r.message,r.status==1?'success':'danger');if(r.status==1){load();$(document).trigger('academic:changed')}}).always(end_load)});load()})(jQuery);</script>
