<?php
ob_start();
include_once 'includes/session_check.php';
include 'db_connect.php';
header('Content-Type: application/json; charset=utf-8');
function prOut(array $data,int $code=200):void{while(ob_get_level())ob_end_clean();http_response_code($code);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function prBind(mysqli_stmt $stmt,string $types,array &$params):void{if($types==='')return;$args=[$types];foreach($params as &$value)$args[]=&$value;call_user_func_array([$stmt,'bind_param'],$args);}
function prMoney($value):string{return 'S/ '.number_format((float)$value,2);}
$school=(int)($_SESSION['login_school_id']??0);$draw=(int)($_GET['draw']??1);if($school<=0||empty($_SESSION['login_id']))prOut(['draw'=>$draw,'recordsTotal'=>0,'recordsFiltered'=>0,'data'=>[]],403);
$check=$conn->query("SHOW TABLES LIKE 'payment_operations'");if(!$check||!$check->num_rows)prOut(['draw'=>$draw,'recordsTotal'=>0,'recordsFiltered'=>0,'data'=>[],'error'=>'Ejecute sql/payments_module_upgrade.sql.'],409);
$snapshots=false;$check=$conn->query("SHOW TABLES LIKE 'payment_concept_snapshots'");if($check&&$check->num_rows)$snapshots=true;$discountSnapshots=false;$check=$conn->query("SHOW TABLES LIKE 'payment_discount_snapshots'");if($check&&$check->num_rows)$discountSnapshots=true;
$start=max(0,(int)($_GET['start']??0));$length=min(100,max(10,(int)($_GET['length']??25)));$method=(int)($_GET['payment_method_id']??0);$where=['po.school_id=?'];$types='i';$params=[$school];
$add=function(string $sql,string $type,$value)use(&$where,&$types,&$params){if($value===''||$value===0)return;$where[]=$sql;$types.=$type;$params[]=$value;};
$add('DATE(po.payment_date)>=?','s',trim($_GET['start_date']??''));$add('DATE(po.payment_date)<=?','s',trim($_GET['end_date']??''));$add('s.nivel=?','s',trim($_GET['nivel_educativo']??''));$add('s.grado=?','s',trim($_GET['grado']??''));$add('s.seccion=?','s',trim($_GET['seccion']??''));$add('s.id=?','i',(int)($_GET['student_id']??0));$add('s.status=?','s',trim($_GET['student_status']??''));$status=trim($_GET['operation_status']??'');if(in_array($status,['Confirmado','Anulado'],true))$add('po.status=?','s',$status);
if($method>0){$where[]='EXISTS(SELECT 1 FROM payment_operation_methods fm WHERE fm.operation_id=po.id AND fm.payment_method_id=?)';$types.='i';$params[]=$method;}
$year=(int)($_GET['academic_year_id']??0);if($year>0){$where[]='EXISTS(SELECT 1 FROM payments fp INNER JOIN student_ef_list fe ON fe.id=fp.ef_id INNER JOIN courses fc ON fc.id=fe.course_id WHERE fp.operation_id=po.id AND fc.academic_year_id=?)';$types.='i';$params[]=$year;}
$course=(int)($_GET['course_id']??0);if($course>0){$where[]='EXISTS(SELECT 1 FROM payments fp INNER JOIN student_ef_list fe ON fe.id=fp.ef_id WHERE fp.operation_id=po.id AND fe.course_id=?)';$types.='i';$params[]=$course;}
$search=trim($_GET['search']['value']??'');if($search!==''){$like='%'.$search.'%';$searchParts=['s.name LIKE ?','s.id_no LIKE ?','po.receipt_full LIKE ?'];$types.='sss';array_push($params,$like,$like,$like);if($snapshots){$searchParts[]='EXISTS(SELECT 1 FROM payment_concept_snapshots sc WHERE sc.payment_operation_id=po.id AND sc.concept_name LIKE ?)';$types.='s';$params[]=$like;}$where[]='('.implode(' OR ',$searchParts).')';}
$whereSql=implode(' AND ',$where);$totalStmt=$conn->prepare('SELECT COUNT(*) total FROM payment_operations WHERE school_id=?');$totalStmt->bind_param('i',$school);$totalStmt->execute();$recordsTotal=(int)$totalStmt->get_result()->fetch_assoc()['total'];$totalStmt->close();
$countStmt=$conn->prepare("SELECT COUNT(*) total FROM payment_operations po INNER JOIN student s ON s.id=po.student_id WHERE $whereSql");prBind($countStmt,$types,$params);$countStmt->execute();$recordsFiltered=(int)$countStmt->get_result()->fetch_assoc()['total'];$countStmt->close();
$amountExpr=$method>0?'(SELECT COALESCE(SUM(sm.amount),0) FROM payment_operation_methods sm WHERE sm.operation_id=po.id AND sm.payment_method_id='.(int)$method.')':'po.total_amount';$discountExpr=$discountSnapshots?'COALESCE((SELECT SUM(sd.discount_amount) FROM payment_discount_snapshots sd WHERE sd.payment_operation_id=po.id),0)':'0';
$summaryStmt=$conn->prepare("SELECT COUNT(*) count,COALESCE(SUM(CASE WHEN q.operation_status='Confirmado' THEN q.reported_amount ELSE 0 END),0) confirmed,COALESCE(SUM(CASE WHEN q.operation_status='Anulado' THEN q.reported_amount ELSE 0 END),0) cancelled,COALESCE(SUM(q.discount_amount),0) discounts FROM (SELECT po.id,po.status operation_status,$amountExpr reported_amount,$discountExpr discount_amount FROM payment_operations po INNER JOIN student s ON s.id=po.student_id WHERE $whereSql) q");prBind($summaryStmt,$types,$params);$summaryStmt->execute();$summary=$summaryStmt->get_result()->fetch_assoc();$summaryStmt->close();
$view=trim($_GET['view']??'detail');
if(in_array($view,['student','concept','method','daily'],true)){
 if($view==='student'){
  $base="SELECT s.id,s.id_no,s.name student_name,s.nivel,s.grado,s.seccion,COUNT(*) operations,SUM(po.status='Confirmado') confirmed_operations,SUM(po.status='Anulado') cancelled_operations,COALESCE(SUM(CASE WHEN po.status='Confirmado' THEN $amountExpr ELSE 0 END),0) confirmed_amount,COALESCE(SUM(CASE WHEN po.status='Anulado' THEN $amountExpr ELSE 0 END),0) cancelled_amount,COALESCE(SUM($discountExpr),0) discount_amount,MAX(po.payment_date) last_payment FROM payment_operations po INNER JOIN student s ON s.id=po.student_id WHERE $whereSql GROUP BY s.id,s.id_no,s.name,s.nivel,s.grado,s.seccion";
  $order='confirmed_amount DESC,student_name';
 }elseif($view==='daily'){
  $base="SELECT DATE(po.payment_date) payment_day,COUNT(*) operations,SUM(po.status='Confirmado') confirmed_operations,SUM(po.status='Anulado') cancelled_operations,COUNT(DISTINCT po.student_id) students,COALESCE(SUM(CASE WHEN po.status='Confirmado' THEN $amountExpr ELSE 0 END),0) confirmed_amount,COALESCE(SUM(CASE WHEN po.status='Anulado' THEN $amountExpr ELSE 0 END),0) cancelled_amount,COALESCE(SUM($discountExpr),0) discount_amount FROM payment_operations po INNER JOIN student s ON s.id=po.student_id WHERE $whereSql GROUP BY DATE(po.payment_date)";
  $order='payment_day DESC';
 }elseif($view==='method'){
  $methodExtra=$method>0?' AND pom.payment_method_id='.(int)$method:'';
  $base="SELECT pom.payment_method_id,COALESCE(pm.name,'No especificado') method_name,COUNT(DISTINCT po.id) operations,COUNT(DISTINCT po.student_id) students,COALESCE(SUM(CASE WHEN po.status='Confirmado' THEN pom.amount ELSE 0 END),0) confirmed_amount,COALESCE(SUM(CASE WHEN po.status='Anulado' THEN pom.amount ELSE 0 END),0) cancelled_amount FROM payment_operations po INNER JOIN student s ON s.id=po.student_id INNER JOIN payment_operation_methods pom ON pom.operation_id=po.id LEFT JOIN payment_methods pm ON pm.id=pom.payment_method_id WHERE $whereSql$methodExtra GROUP BY pom.payment_method_id,pm.name";
  $order='confirmed_amount DESC,method_name';
 }else{
  $snapshotJoin=$snapshots?' LEFT JOIN payment_concept_snapshots pcs ON pcs.payment_operation_id=po.id AND pcs.debt_id=ef.id ':'';
  $snapshotName=$snapshots?"MAX(NULLIF(pcs.concept_name,''))":'NULL';
  $base="SELECT ef.course_id,COALESCE($snapshotName,MAX(NULLIF(c.course,'')),CONCAT('Concepto histórico #',ef.course_id)) concept_name,MAX(COALESCE(ay.year,'')) academic_year,COUNT(DISTINCT po.id) operations,COUNT(DISTINCT po.student_id) students,COALESCE(SUM(CASE WHEN po.status='Confirmado' THEN p.amount ELSE 0 END),0) confirmed_amount,COALESCE(SUM(CASE WHEN po.status='Anulado' THEN p.amount ELSE 0 END),0) cancelled_amount FROM payment_operations po INNER JOIN student s ON s.id=po.student_id INNER JOIN payments p ON p.operation_id=po.id INNER JOIN student_ef_list ef ON ef.id=p.ef_id LEFT JOIN courses c ON c.id=ef.course_id LEFT JOIN academic_year ay ON ay.id=c.academic_year_id $snapshotJoin WHERE $whereSql GROUP BY ef.course_id";
  $order='confirmed_amount DESC,concept_name';
 }
 $countParams=$params;$countStmt=$conn->prepare("SELECT COUNT(*) total FROM ($base) grouped_rows");if(!$countStmt)prOut(['draw'=>$draw,'recordsTotal'=>0,'recordsFiltered'=>0,'data'=>[],'error'=>$conn->error],500);prBind($countStmt,$types,$countParams);$countStmt->execute();$groupTotal=(int)$countStmt->get_result()->fetch_assoc()['total'];$countStmt->close();
 $dataParams=$params;$groupStmt=$conn->prepare("$base ORDER BY $order LIMIT $start,$length");if(!$groupStmt)prOut(['draw'=>$draw,'recordsTotal'=>0,'recordsFiltered'=>0,'data'=>[],'error'=>$conn->error],500);prBind($groupStmt,$types,$dataParams);$groupStmt->execute();$groupResult=$groupStmt->get_result();$data=[];while($row=$groupResult->fetch_assoc())$data[]=$row;$groupStmt->close();
 prOut(['draw'=>$draw,'recordsTotal'=>$groupTotal,'recordsFiltered'=>$groupTotal,'data'=>$data,'summary'=>['count'=>(int)$summary['count'],'confirmed'=>(float)$summary['confirmed'],'cancelled'=>(float)$summary['cancelled'],'discounts'=>(float)$summary['discounts']]]);
}
$legacy="(p.operation_id=po.id OR (p.operation_id IS NULL AND po.receipt_series='LEG' AND ef.student_id=po.student_id AND CONVERT(po.receipt_full USING utf8mb4) COLLATE utf8mb4_general_ci=CONVERT(CONCAT('LEG-',po.school_id,'-',po.student_id,'-',p.receipt_no) USING utf8mb4) COLLATE utf8mb4_general_ci))";
$fallback="(SELECT GROUP_CONCAT(DISTINCT CONCAT(COALESCE(c.course,CONCAT('Concepto histórico #',ef.course_id)),IF(ay.year IS NOT NULL,CONCAT(' · ',ay.year),'')) ORDER BY p.id SEPARATOR ' | ') FROM payments p INNER JOIN student_ef_list ef ON ef.id=p.ef_id LEFT JOIN courses c ON c.id=ef.course_id LEFT JOIN academic_year ay ON ay.id=c.academic_year_id WHERE $legacy)";$conceptExpr=$snapshots?"COALESCE((SELECT GROUP_CONCAT(DISTINCT CONCAT(COALESCE(NULLIF(sc.concept_name,''),'Concepto histórico'),IF(COALESCE(sc.academic_year_label,'')<>'',CONCAT(' · ',sc.academic_year_label),'')) ORDER BY sc.id SEPARATOR ' | ') FROM payment_concept_snapshots sc WHERE sc.payment_operation_id=po.id),$fallback)":$fallback;
$orderMap=['po.payment_date','po.receipt_full','s.name','po.id','po.id','po.id',$amountExpr,'po.status','po.id'];$orderIndex=(int)($_GET['order'][0]['column']??0);$direction=strtolower($_GET['order'][0]['dir']??'desc')==='asc'?'ASC':'DESC';$orderBy=$orderMap[$orderIndex]??'po.payment_date';
$sql="SELECT po.id,po.receipt_full,po.payment_date,po.status operation_status,po.cancellation_reason,s.id_no,s.name student_name,s.nivel,s.grado,s.seccion,u.name created_by,$conceptExpr concepts,$discountExpr discount_amount,(SELECT GROUP_CONCAT(CONCAT(COALESCE(pm.name,'No especificado'),': S/ ',FORMAT(pom.amount,2)) ORDER BY pom.id SEPARATOR ' | ') FROM payment_operation_methods pom LEFT JOIN payment_methods pm ON pm.id=pom.payment_method_id WHERE pom.operation_id=po.id) methods,$amountExpr filtered_amount FROM payment_operations po INNER JOIN student s ON s.id=po.student_id LEFT JOIN users u ON u.id=po.created_by WHERE $whereSql ORDER BY $orderBy $direction,po.id DESC LIMIT $start,$length";$stmt=$conn->prepare($sql);if(!$stmt)prOut(['draw'=>$draw,'recordsTotal'=>0,'recordsFiltered'=>0,'data'=>[],'error'=>$conn->error],500);prBind($stmt,$types,$params);$stmt->execute();$result=$stmt->get_result();$data=[];
while($row=$result->fetch_assoc()){$id=(int)$row['id'];$cancel=$row['operation_status']==='Anulado'&&$row['cancellation_reason']?'<div class="small text-danger">'.htmlspecialchars($row['cancellation_reason']).'</div>':'';$data[]=['<strong>'.date('d/m/Y',strtotime($row['payment_date'])).'</strong><div class="small text-muted">'.date('H:i',strtotime($row['payment_date'])).'</div>','<strong>'.htmlspecialchars($row['receipt_full']).'</strong><div class="small text-muted">'.htmlspecialchars($row['created_by']?:'Sistema').'</div>','<strong>'.htmlspecialchars($row['student_name']).'</strong><div class="small text-muted">'.htmlspecialchars($row['id_no'].' · '.$row['nivel'].' · '.$row['grado'].' '.$row['seccion']).'</div>','<div class="pr-concepts">'.htmlspecialchars($row['concepts']?:'Concepto no disponible').'</div>','<div class="pr-methods">'.htmlspecialchars($row['methods']?:'No especificado').'</div>',prMoney($row['discount_amount']),'<div class="text-right font-weight-bold">'.prMoney($row['filtered_amount']).'</div>','<span class="badge badge-'.($row['operation_status']==='Confirmado'?'success':'danger').'">'.htmlspecialchars($row['operation_status']).'</span>'.$cancel,'<button type="button" class="btn btn-sm btn-outline-primary" onclick="uni_modal(\'Detalle del pago\',\'view_payment.php?operation_id='.$id.'\',\'modal-xl\')"><i class="fas fa-eye"></i></button>'];}
$stmt->close();prOut(['draw'=>$draw,'recordsTotal'=>$recordsTotal,'recordsFiltered'=>$recordsFiltered,'data'=>$data,'summary'=>['count'=>(int)$summary['count'],'confirmed'=>(float)$summary['confirmed'],'cancelled'=>(float)$summary['cancelled'],'discounts'=>(float)$summary['discounts']]]);
?>
