<?php
date_default_timezone_set('America/Lima');
include_once __DIR__.'/includes/session_check.php';
require_login_modal();
include __DIR__.'/db_connect.php';
$school=(int)($_SESSION['login_school_id']??0);$user=(int)($_SESSION['login_id']??0);$id=(int)($_GET['id']??0);
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$csrf=$_SESSION['csrf_token'];
$role=$conn->prepare('SELECT type,is_director FROM users WHERE id=? AND school_id=? LIMIT 1');$role->bind_param('ii',$user,$school);$role->execute();$roleData=$role->get_result()->fetch_assoc();$role->close();
$allowed=$roleData&&(int)$roleData['type']===1;
if(!$allowed){echo '<div class="alert alert-danger">No tiene permiso para autorizar solicitudes.</div>';return;}
$stmt=$conn->prepare("SELECT r.*,u.name AS requester,st.name AS student_name,st.id_no,a.fecha,a.hora AS attendance_time,a.estado AS attendance_status,a.notes AS attendance_notes FROM attendance_change_requests r INNER JOIN users u ON u.id=r.requested_by LEFT JOIN asistencia a ON a.id=r.attendance_id LEFT JOIN student st ON st.id=a.student_id WHERE r.id=? AND r.school_id=? LIMIT 1");$stmt->bind_param('ii',$id,$school);$stmt->execute();$request=$stmt->get_result()->fetch_assoc();$stmt->close();
if(!$request){echo '<div class="alert alert-warning">La solicitud no existe o pertenece a otra institución.</div>';return;}
$payload=json_decode($request['request_payload'],true)?:[];$wanted=$payload['requested']??[];
?>
<style>.arr-box{border:1px solid #e4e7ec;border-radius:8px;padding:12px;background:#f8fafc}.arr-label{font-size:.75rem;color:#667085;text-transform:uppercase;font-weight:700}.arr-value{color:#344054;font-weight:600}.arr-arrow{display:flex;align-items:center;justify-content:center;color:#4e73df;font-size:1.2rem}@media(max-width:767px){.arr-arrow{transform:rotate(90deg);padding:8px}}</style>
<div id="arr-message"></div>
<div class="mb-3"><span class="badge badge-warning"><?=htmlspecialchars($request['request_type'])?></span> <span class="badge <?=$request['status']==='Pendiente'?'badge-primary':'badge-secondary'?>"><?=htmlspecialchars($request['status'])?></span></div>
<div class="row mb-3"><div class="col-md-6"><div class="arr-box h-100"><div class="arr-label">Solicitado por</div><div class="arr-value"><?=htmlspecialchars($request['requester'])?></div><div class="small text-muted mt-2"><?=htmlspecialchars($request['created_at'])?></div></div></div><div class="col-md-6"><div class="arr-box h-100"><div class="arr-label">Motivo</div><div class="arr-value"><?=htmlspecialchars($request['reason']?:'Sin motivo adicional')?></div></div></div></div>
<?php if($request['request_type']==='Editar nómina'):$changes=$payload['changes']??[];?>
<div class="mb-2 font-weight-bold"><?=htmlspecialchars(($payload['date']??'').' · '.($payload['nivel']??'').' '.($payload['grado']??'').' '.($payload['seccion']??''))?></div>
<div class="table-responsive"><table class="table table-sm table-bordered mb-0"><thead class="thead-light"><tr><th>Estudiante</th><th>Estado anterior</th><th>Hora anterior</th><th>Estado solicitado</th><th>Hora solicitada</th><th>Observación</th></tr></thead><tbody><?php foreach($changes as $change):$previous=$change['previous']??[];$requested=$change['requested']??[];?><tr><td><strong><?=htmlspecialchars($change['student_name']??'Estudiante')?></strong><div class="small text-muted"><?=htmlspecialchars($change['student_code']??'')?></div></td><td><?=htmlspecialchars($previous['status']??'—')?></td><td><?=htmlspecialchars($previous['time']??'—')?></td><td><strong><?=htmlspecialchars($requested['status']??'—')?></strong></td><td><strong><?=htmlspecialchars($requested['time']??'—')?></strong></td><td><?=htmlspecialchars($requested['notes']??'—')?></td></tr><?php endforeach;?></tbody></table></div>
<div class="alert alert-info mt-3 mb-0">Al aprobar se aplicarán juntos los <?=count($changes)?> cambios de esta solicitud.</div>
<?php elseif($request['request_type']==='Editar registro'):?>
<div class="mb-2 font-weight-bold"><?=htmlspecialchars($request['student_name']?:'Estudiante')?> · <?=htmlspecialchars($request['fecha']?:($payload['date']??''))?></div>
<div class="row align-items-stretch"><div class="col-md-5"><div class="arr-box h-100"><div class="arr-label mb-2">Registro actual</div><div>Estado: <strong><?=htmlspecialchars($request['attendance_status'])?></strong></div><div>Hora: <strong><?=htmlspecialchars($request['attendance_time'])?></strong></div><div>Observación: <?=htmlspecialchars($request['attendance_notes']?:'—')?></div></div></div><div class="col-md-2 arr-arrow"><i class="fas fa-arrow-right"></i></div><div class="col-md-5"><div class="arr-box h-100 border-primary"><div class="arr-label mb-2">Cambio solicitado</div><div>Estado: <strong><?=htmlspecialchars($wanted['status']??'')?></strong></div><div>Hora: <strong><?=htmlspecialchars($wanted['time']??'')?></strong></div><div>Observación: <?=htmlspecialchars($wanted['notes']??'—')?></div></div></div></div>
<?php elseif($request['request_type']==='Reabrir día'):?>
<div class="arr-box"><div class="arr-label mb-2">Día que se solicita reabrir</div><div class="arr-value"><?=htmlspecialchars(($payload['date']??'').' · '.($payload['nivel']??'').' '.($payload['grado']??'').' '.($payload['seccion']??''))?></div></div>
<?php else:?>
<div class="arr-box"><div class="arr-label mb-2">Detalle</div><div class="arr-value"><?=htmlspecialchars($request['student_name']?:'Registro de asistencia')?></div><div class="small text-muted mt-2"><?=htmlspecialchars($request['request_type'])?></div></div>
<?php endif;?>
<?php if($request['status']==='Pendiente'):?><div class="form-group mt-3"><label>Observación de la revisión</label><textarea id="arr-notes" class="form-control" maxlength="255" placeholder="Opcional al aprobar; recomendable al rechazar"></textarea></div><div class="d-flex justify-content-end"><button type="button" class="btn btn-outline-danger mr-2 arr-review" data-decision="Rechazada"><i class="fas fa-times mr-1"></i>Rechazar</button><button type="button" class="btn btn-success arr-review" data-decision="Aprobada"><i class="fas fa-check mr-1"></i>Aprobar y aplicar</button></div><?php else:?><div class="alert alert-info mt-3 mb-0">Esta solicitud ya fue revisada.</div><?php endif;?>
<script>
(function($){$('.arr-review').click(function(){let button=$(this),decision=button.data('decision');if(decision==='Rechazada'&&!$('#arr-notes').val().trim()){return $('#arr-message').html('<div class="alert alert-warning">Indique el motivo del rechazo.</div>')}$('.arr-review').prop('disabled',true);$.post('attendance_api.php?action=review_request',{csrf_token:<?=json_encode($csrf)?>,id:<?=json_encode($id)?>,decision:decision,notes:$('#arr-notes').val()},null,'json').done(function(r){if(!r.status){$('.arr-review').prop('disabled',false);return $('#arr-message').html('<div class="alert alert-danger">'+$('<div>').text(r.message).html()+'</div>')}alert_toast(r.message,'success');setTimeout(function(){let item=$('.attendance-request-open[data-id="<?=htmlspecialchars((string)$id,ENT_QUOTES,'UTF-8')?>"]'),card=item.closest('.card');item.remove();if(card.length&&!card.find('.attendance-request-open').length)card.remove();$('#uni_modal').modal('hide');$(document).trigger('attendance:request-reviewed',[<?=json_encode($id)?>])},500)}).fail(function(x){$('.arr-review').prop('disabled',false);$('#arr-message').html('<div class="alert alert-danger">'+$('<div>').text((x.responseJSON||{}).message||'No se pudo revisar la solicitud.').html()+'</div>')})})})(jQuery);
</script>
