<?php
include_once __DIR__.'/../db_connect.php';
$school=(int)($_SESSION['login_school_id']??0);$ready=false;$q=$conn->query("SHOW COLUMNS FROM asistencia LIKE 'school_id'");if($q&&$q->num_rows)$ready=true;
?>
<style>
.ar-header{background:#fff;border:1px solid #e3e6f0;border-left:4px solid #4e73df;border-radius:.55rem;padding:1.15rem 1.35rem}.ar-kpi{border:1px solid #e3e6f0;border-radius:.55rem;background:#fff;padding:1rem;height:100%}.ar-kpi small{color:#6e7891;font-weight:700;text-transform:uppercase}.ar-kpi strong{display:block;color:#263754;font-size:1.4rem;margin-top:.2rem}.ar-table td{vertical-align:middle}.select2-container{width:100%!important}
</style>
<div class="container-fluid py-3">
 <div class="ar-header d-flex flex-wrap align-items-center justify-content-between mb-3"><div><h1 class="h4 mb-1 text-gray-800"><i class="fas fa-chart-bar text-primary mr-2"></i>Reporte de asistencia</h1><div class="text-muted small">Seguimiento de marcaciones, incidencias y cierres por periodo.</div></div><div class="mt-2 mt-md-0"><button id="ar-print" class="btn btn-outline-primary btn-sm mr-1"><i class="fas fa-print mr-1"></i>Vista previa</button><button id="ar-export" class="btn btn-primary btn-sm"><i class="fas fa-file-excel mr-1"></i>Exportar Excel</button></div></div>
 <?php if(!$ready):?><div class="alert alert-warning">Ejecute manualmente <strong>sql/attendance_module_upgrade.sql</strong>.</div><?php endif;?><div id="ar-error" class="alert alert-danger d-none"></div>
 <div class="card shadow-sm mb-3"><div class="card-body pb-2"><div class="form-row">
  <div class="col-lg-2 col-md-4 mb-2"><label class="small font-weight-bold">Año académico</label><select id="ar-year" class="form-control form-control-sm"></select></div><div class="col-lg-2 col-md-4 mb-2"><label class="small font-weight-bold">Desde</label><input id="ar-from" type="date" class="form-control form-control-sm"></div><div class="col-lg-2 col-md-4 mb-2"><label class="small font-weight-bold">Hasta</label><input id="ar-to" type="date" class="form-control form-control-sm"></div>
  <div class="col-lg-2 col-md-4 mb-2"><label class="small font-weight-bold">Nivel</label><select id="ar-level" class="form-control form-control-sm"><option value="">Todos</option></select></div><div class="col-lg-2 col-md-4 mb-2"><label class="small font-weight-bold">Grado</label><select id="ar-grade" class="form-control form-control-sm"><option value="">Todos</option></select></div><div class="col-lg-2 col-md-4 mb-2"><label class="small font-weight-bold">Sección</label><select id="ar-section" class="form-control form-control-sm"><option value="">Todas</option></select></div>
  <div class="col-lg-4 col-md-6 mb-2"><label class="small font-weight-bold">Estudiante</label><select id="ar-student" class="form-control form-control-sm"><option value="">Todos</option></select></div><div class="col-lg-2 col-md-3 mb-2"><label class="small font-weight-bold">Tipo</label><select id="ar-type" class="form-control form-control-sm"><option value="">Todos</option><option>Entrada</option><option>Salida</option></select></div><div class="col-lg-2 col-md-3 mb-2"><label class="small font-weight-bold">Estado</label><select id="ar-status" class="form-control form-control-sm"><option value="">Todos</option><option>Presente</option><option>Tarde</option><option>Ausente</option><option>Ausente Justificada</option><option>Permiso</option></select></div><div class="col-lg-2 col-md-3 mb-2"><label class="small font-weight-bold">Origen</label><select id="ar-source" class="form-control form-control-sm"><option value="">Todos</option><option value="Aula">Aula</option><option value="Escáner">Escáner</option><option value="Manual">Manual</option></select></div><div class="col-lg-2 col-md-3 mb-2 d-flex align-items-end"><button id="ar-clear" class="btn btn-light btn-sm btn-block border"><i class="fas fa-eraser mr-1"></i>Limpiar</button></div>
 </div></div></div>
 <div class="row mb-3"><div class="col-md-2 col-6 mb-2"><div class="ar-kpi"><small>Marcaciones</small><strong id="ar-total">0</strong></div></div><div class="col-md-2 col-6 mb-2"><div class="ar-kpi"><small>Presentes</small><strong id="ar-present">0</strong></div></div><div class="col-md-2 col-6 mb-2"><div class="ar-kpi"><small>Tardanzas</small><strong id="ar-late">0</strong></div></div><div class="col-md-2 col-6 mb-2"><div class="ar-kpi"><small>Ausencias</small><strong id="ar-absent">0</strong></div></div><div class="col-md-2 col-6 mb-2"><div class="ar-kpi"><small>Justificadas</small><strong id="ar-justified">0</strong></div></div><div class="col-md-2 col-6 mb-2"><div class="ar-kpi"><small>Asistencia</small><strong id="ar-rate">0%</strong></div></div></div>
 <div class="card shadow-sm"><div class="card-header bg-white d-flex flex-wrap justify-content-between align-items-center"><div class="btn-group btn-group-sm ar-view"><button data-view="detail" class="btn btn-primary">Detalle</button><button data-view="student" class="btn btn-outline-primary">Por estudiante</button><button data-view="class" class="btn btn-outline-primary">Por aula</button><button data-view="incidents" class="btn btn-outline-primary">Incidencias</button><button data-view="daily" class="btn btn-outline-primary">Control diario</button></div><small class="text-muted mt-2 mt-md-0">Los indicadores consideran solo entradas vigentes.</small></div><div class="card-body"><div class="table-responsive"><table id="ar-table" class="table table-bordered table-hover table-sm ar-table" width="100%"></table></div></div></div>
</div>
<script>
(function($){const ready=<?php echo $ready?'true':'false';?>,api='attendance_report_data.php';let table=null,view='detail',years=[];function esc(v){return $('<div>').text(v==null?'':v).html()}function fmtDate(v){if(!v)return'—';let p=String(v).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:v}function badge(v){let c=v==='Presente'?'success':v==='Tarde'?'warning':v==='Ausente'?'danger':v==='Ausente Justificada'?'info':v==='Permiso'?'primary':'secondary';return'<span class="badge badge-'+c+'">'+esc(v)+'</span>'}function rate(r){let n=Number(r.marks||0);return n?(((Number(r.present||0)+Number(r.late||0))*100/n).toFixed(1)+'%'):'0%'}function metricCols(){return[{data:'marks'},{data:'present'},{data:'late'},{data:'absent'},{data:'justified'},{data:'permission'},{data:null,render:rate}]}function summaryStudent(){return[{data:null,render:r=>'<strong>'+esc(r.student_name)+'</strong><div class="small text-muted">'+esc(r.id_no)+'</div>'},{data:null,render:r=>esc(r.nivel+' · '+r.grado+' '+r.seccion)},...metricCols()]}
const configs={detail:{heads:['Fecha','Estudiante','Aula','Hora','Tipo','Estado','Origen','Detalle'],cols:[{data:'fecha',render:fmtDate},{data:null,render:r=>'<strong>'+esc(r.student_name)+'</strong><div class="small text-muted">'+esc(r.id_no)+'</div>'},{data:null,render:r=>esc(r.nivel+' · '+r.grado+' '+r.seccion)},{data:'hora',render:v=>v?String(v).substring(0,5):'—'},{data:'tipo'},{data:'estado',render:badge},{data:'source',defaultContent:'Manual'},{data:'id',orderable:false,render:id=>'<button class="btn btn-sm btn-outline-primary ar-detail" data-id="'+id+'"><i class="fas fa-eye"></i></button>'}]},student:{heads:['Estudiante','Aula','Marcaciones','Presentes','Tardanzas','Ausencias','Justificadas','Permisos','% asistencia'],cols:summaryStudent()},incidents:{heads:['Estudiante','Aula','Marcaciones','Presentes','Tardanzas','Ausencias','Justificadas','Permisos','% asistencia'],cols:summaryStudent()},class:{heads:['Aula','Estudiantes','Marcaciones','Presentes','Tardanzas','Ausencias','Justificadas','Permisos','% asistencia'],cols:[{data:null,render:r=>'<strong>'+esc(r.nivel+' · '+r.grado+' '+r.seccion)+'</strong>'},{data:'students'},...metricCols()]},daily:{heads:['Fecha','Aula','Marcados','Presentes','Tardanzas','Ausencias','Control'],cols:[{data:'fecha',render:fmtDate},{data:null,render:r=>esc(r.nivel+' · '+r.grado+' '+r.seccion)},{data:'marked'},{data:'present'},{data:'late'},{data:'absent'},{data:'closure_status',render:v=>'<span class="badge badge-'+(v==='Cerrada'?'success':v==='Reabierta'?'warning':'secondary')+'">'+esc(v)+'</span>'}]}};
function filters(){return{academic_year_id:$('#ar-year').val(),date_from:$('#ar-from').val(),date_to:$('#ar-to').val(),nivel:$('#ar-level').val(),grado:$('#ar-grade').val(),seccion:$('#ar-section').val(),student_id:$('#ar-student').val(),tipo:$('#ar-type').val(),estado:$('#ar-status').val(),source:$('#ar-source').val(),view:view}}function showSummary(s){s=s||{};$('#ar-total').text(s.total||0);$('#ar-present').text(s.present||0);$('#ar-late').text(s.late||0);$('#ar-absent').text(s.absent||0);$('#ar-justified').text(s.justified||0);$('#ar-rate').text((s.attendance_rate||0)+'%')}
function init(){if(!ready||!$.fn.DataTable)return;let c=configs[view];if(table){table.destroy();$('#ar-table').empty()}$('#ar-table').append('<thead><tr>'+c.heads.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody></tbody>');table=$('#ar-table').DataTable({serverSide:true,processing:true,pageLength:25,lengthMenu:[[25,50,100],[25,50,100]],order:[],ajax:{url:api,data:d=>$.extend(d,filters()),dataSrc:r=>{showSummary(r.summary);$('#ar-error').addClass('d-none');return r.data||[]},error:x=>{let m='No se pudo cargar el reporte.';try{m=JSON.parse(x.responseText).message||m}catch(e){}$('#ar-error').removeClass('d-none').text(m)}},columns:c.cols,language:{search:'Buscar:',lengthMenu:'Mostrar _MENU_',processing:'Consultando asistencia...',zeroRecords:'No se encontraron registros',info:'Mostrando _START_ a _END_ de _TOTAL_',infoEmpty:'Sin registros',paginate:{previous:'Anterior',next:'Siguiente'}}})}
function fill(sel,items,label){let v=$(sel).val();$(sel).html('<option value="">'+label+'</option>'+items.map(x=>'<option value="'+esc(x.value||x.id||x)+'">'+esc(x.label||x.name||x)+'</option>').join('')).val(v||'')}function options(){return $.getJSON(api+'?action=options',$.extend({},filters())).done(r=>{fill('#ar-grade',r.grades||[],'Todos');fill('#ar-section',r.sections||[],'Todas');fill('#ar-student',(r.students||[]).map(s=>({id:s.id,name:s.name+' ('+s.id_no+') · '+s.nivel+' '+s.grado+' '+s.seccion})),'Todos')})}
if(ready)$.getJSON(api+'?action=meta').done(r=>{years=r.years||[];$('#ar-year').html(years.map(y=>'<option value="'+y.id+'" data-from="'+y.start_date+'" data-to="'+y.end_date+'" '+(Number(y.is_active)===1?'selected':'')+'>'+esc(y.year)+(Number(y.is_active)===1?' · Activo':'')+'</option>').join(''));fill('#ar-level',r.levels||[],'Todos');let y=years.find(x=>Number(x.is_active)===1)||years[0];if(y){let today=new Date().toISOString().slice(0,10);$('#ar-from').val(y.start_date);$('#ar-to').val(y.end_date<today?y.end_date:today)}options().always(init)});
$('#ar-year').change(function(){let o=$(this).find(':selected');$('#ar-from').val(o.data('from')||'');$('#ar-to').val(o.data('to')||'');init()});$('#ar-level').change(()=>{$('#ar-grade,#ar-section,#ar-student').val('');options().always(init)});$('#ar-grade').change(()=>{$('#ar-section,#ar-student').val('');options().always(init)});$('#ar-section').change(()=>{$('#ar-student').val('');options().always(init)});$('#ar-student,#ar-from,#ar-to,#ar-type,#ar-status,#ar-source').change(init);$('.ar-view button').click(function(){view=$(this).data('view');$('.ar-view button').removeClass('btn-primary').addClass('btn-outline-primary');$(this).addClass('btn-primary').removeClass('btn-outline-primary');init()});$('#ar-clear').click(function(){$('#ar-level,#ar-grade,#ar-section,#ar-student,#ar-type,#ar-status,#ar-source').val('');options().always(init)});$(document).on('click','.ar-detail',function(){uni_modal('Trazabilidad de asistencia','view_attendance_record.php?id='+$(this).data('id'),'modal-lg')});function query(){return $.param(filters())}$('#ar-export').click(()=>location.href='export_attendance_excel.php?'+query());$('#ar-print').click(()=>uni_modal('Vista previa del reporte','print_attendance_report.php?'+query(),'modal-xl'))})(jQuery);
</script>
