<?php
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$csrf=$_SESSION['csrf_token'];
?>
<style>
.risk-wrap{max-width:1500px;margin:auto;padding:.4rem 0 2rem}.risk-hero,.risk-box,.risk-card{background:#fff;border:1px solid #e3e6f0;border-radius:.7rem}.risk-hero{padding:1.15rem 1.3rem;border-left:4px solid #4e73df}.risk-title{font-size:1.35rem;font-weight:800;color:#263754;margin:0}.risk-sub{font-size:.82rem;color:#6e7891;margin-top:.25rem}.risk-card{padding:1rem;height:100%}.risk-card small{font-weight:700;color:#7b8499}.risk-card strong{display:block;font-size:1.65rem;color:#263754;margin-top:.35rem}.risk-icon{width:42px;height:42px;border-radius:.6rem;display:flex;align-items:center;justify-content:center;font-size:1.05rem}.risk-danger{background:#fdecec;color:#d94b4b}.risk-warning{background:#fff7e6;color:#c88700}.risk-success{background:#e8f8ef;color:#1e9e58}.risk-primary{background:#edf2ff;color:#4e73df}.risk-head{padding:.9rem 1rem;border-bottom:1px solid #edf0f5;display:flex;align-items:center;justify-content:space-between}.risk-head h5{font-size:.96rem;font-weight:800;color:#263754;margin:0}.risk-body{padding:1rem}.risk-table{font-size:.79rem}.risk-badge{display:inline-block;padding:.28rem .55rem;border-radius:1rem;font-weight:800;font-size:.7rem}.risk-badge-Alto{background:#fdecec;color:#c83333}.risk-badge-Medio{background:#fff4d6;color:#9d6a00}.risk-badge-Bajo{background:#e8f8ef;color:#18854b}.risk-factor{font-size:.72rem;color:#667085;line-height:1.45}.risk-bar-row{display:grid;grid-template-columns:minmax(120px,1fr) 2fr 45px;gap:.6rem;align-items:center;margin:.65rem 0;font-size:.76rem}.risk-track{height:10px;background:#edf0f5;border-radius:8px;overflow:hidden}.risk-fill{height:100%;background:#4e73df;border-radius:8px}.risk-empty{text-align:center;padding:2rem;color:#858796}.risk-note{font-size:.75rem;color:#6e7891}.risk-actions .btn{margin:.1rem}.risk-filter label{font-size:.7rem;font-weight:800;color:#6e7891;text-transform:uppercase}.risk-filter .form-control{font-size:.8rem;height:36px}.risk-modal-kpi{border:1px solid #e3e6f0;border-radius:.6rem;padding:.8rem;text-align:center;height:100%}.risk-modal-kpi small{display:block;color:#7b8499}.risk-modal-kpi strong{font-size:1.25rem;color:#263754}.risk-change{border-left:3px solid #4e73df;background:#f8f9fc;padding:.55rem .7rem;margin:.45rem 0;border-radius:.25rem;font-size:.8rem}.risk-status-Pendiente{background:#fff4d6;color:#9d6a00}.risk-status-Enproceso{background:#edf2ff;color:#3657b3}.risk-status-Completada{background:#e8f8ef;color:#18854b}.risk-status-Cancelada{background:#f1f2f4;color:#667085}.risk-model-warning{border-left:4px solid #f6c23e}.risk-loading{padding:4rem;text-align:center;color:#6e7891}@media(max-width:767px){.risk-bar-row{grid-template-columns:95px 1fr 35px}.risk-title{font-size:1.1rem}.risk-actions .btn{width:100%;margin-bottom:.25rem}}
</style>

<div class="risk-wrap">
  <section class="risk-hero mb-3 d-flex flex-wrap justify-content-between align-items-center">
    <div><h1 class="risk-title"><i class="fas fa-brain text-primary mr-2"></i>Alerta Temprana Inteligente</h1><div class="risk-sub">Estima el riesgo del bimestre siguiente usando únicamente información disponible al cierre del último bimestre válido.</div></div>
    <button class="btn btn-sm btn-outline-primary mt-2 mt-md-0" id="risk-refresh"><i class="fas fa-sync-alt mr-1"></i>Actualizar</button>
  </section>

  <div id="risk-alert"></div>
  <section class="risk-box mb-3 risk-filter"><div class="risk-body"><div class="row align-items-end">
    <div class="col-md-3 mb-2"><label>Nivel</label><select id="risk-level" class="form-control"><option value="">Todos</option><option>Inicial</option><option>Primaria</option><option>Secundaria</option></select></div>
    <div class="col-md-2 mb-2"><label>Grado</label><select id="risk-grade" class="form-control"><option value="">Todos</option><option value="1">1°</option><option value="2">2°</option><option value="3">3°</option><option value="4">4°</option><option value="5">5°</option><option value="6">6°</option></select></div>
    <div class="col-md-2 mb-2"><label>Sección</label><input id="risk-section" class="form-control" maxlength="10" placeholder="Ej. A"></div>
    <div class="col-md-2 mb-2"><label>Bimestre base cerrado</label><select id="risk-bimester" class="form-control"><option value="">Último cerrado</option><option value="1">I</option><option value="2">II</option><option value="3">III</option></select></div>
    <div class="col-md-3 mb-2"><button class="btn btn-primary btn-block" id="risk-apply"><i class="fas fa-filter mr-1"></i>Aplicar filtros</button></div>
  </div></div></section>

  <div id="risk-loading" class="risk-loading"><div class="spinner-border text-primary mb-2"></div><div>Calculando alertas...</div></div>
  <main id="risk-content" class="d-none">
    <div id="risk-cards" class="row"></div>
    <div class="row">
      <div class="col-xl-8 mb-3"><section class="risk-box h-100"><div class="risk-head"><h5><i class="fas fa-user-shield text-danger mr-2"></i>Estudiantes priorizados</h5><small class="text-muted">Ordenados por probabilidad estimada</small></div><div class="table-responsive"><table class="table table-hover mb-0 risk-table"><thead class="thead-light"><tr><th>Estudiante</th><th>Aula</th><th>Riesgo</th><th>Factores</th><th>Interv.</th><th class="text-right">Acciones</th></tr></thead><tbody id="risk-students"></tbody></table></div></section></div>
      <div class="col-xl-4 mb-3"><section class="risk-box h-100"><div class="risk-head"><h5><i class="fas fa-project-diagram text-primary mr-2"></i>Factores predominantes</h5></div><div class="risk-body" id="risk-factors"></div></section></div>
    </div>

    <div class="row">
      <div class="col-xl-8 mb-3"><section class="risk-box"><div class="risk-head"><h5><i class="fas fa-hands-helping text-primary mr-2"></i>Intervenciones y seguimiento</h5><span id="risk-intervention-kpis" class="risk-note"></span></div><div class="table-responsive"><table class="table table-hover mb-0 risk-table"><thead class="thead-light"><tr><th>Estudiante</th><th>Intervención</th><th>Estado</th><th>Seguimiento</th><th>Riesgo inicial</th><th class="text-right">Acción</th></tr></thead><tbody id="risk-interventions"></tbody></table></div></section></div>
      <div class="col-xl-4 mb-3"><section class="risk-box h-100"><div class="risk-head"><h5><i class="fas fa-chart-line text-success mr-2"></i>Medición de seguimiento</h5></div><div class="risk-body" id="risk-effectiveness"></div></section></div>
    </div>
  </main>
</div>

<div class="modal fade" id="riskScenarioModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Simulación de escenario</h5><button class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body" id="risk-scenario-body"></div><div class="modal-footer"><button class="btn btn-secondary" data-dismiss="modal">Cerrar</button><button class="btn btn-primary" id="risk-scenario-intervene"><i class="fas fa-hands-helping mr-1"></i>Registrar intervención</button></div></div></div></div>

<div class="modal fade" id="riskInterventionModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="risk-intervention-form"><div class="modal-header"><h5 class="modal-title">Nueva intervención</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body">
<input type="hidden" name="student_id" id="risk-int-student"><div class="alert alert-light border" id="risk-int-student-label"></div>
<div class="form-group"><label>Tipo</label><select class="form-control" name="intervention_type" id="risk-int-type" required><option>Reforzamiento académico</option><option>Tutoría académica</option><option>Seguimiento de asistencia</option><option>Plan de puntualidad</option><option>Comunicación con apoderado</option><option>Acompañamiento socioeducativo</option><option>Seguimiento tutorial</option></select></div>
<div class="form-group"><label>Título</label><input class="form-control" name="title" id="risk-int-title" maxlength="160" required></div>
<div class="row"><div class="col-md-6 form-group"><label>Fecha planificada</label><input type="date" class="form-control" name="planned_date"></div><div class="col-md-6 form-group"><label>Fecha de seguimiento</label><input type="date" class="form-control" name="followup_date"></div></div>
<div class="form-group"><label>Observaciones</label><textarea class="form-control" name="notes" rows="3" maxlength="1000" placeholder="Acciones acordadas, responsables, observaciones..."></textarea></div>
<div class="risk-note"><i class="fas fa-info-circle mr-1"></i>La probabilidad y nivel de riesgo se guardan automáticamente como línea base del bimestre objetivo.</div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Guardar intervención</button></div></form></div></div>

<div class="modal fade" id="riskUpdateModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="risk-update-form"><div class="modal-header"><h5 class="modal-title">Actualizar seguimiento</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body">
<input type="hidden" name="id" id="risk-up-id"><div class="alert alert-light border" id="risk-up-label"></div>
<div class="form-group"><label>Estado</label><select class="form-control" name="status" id="risk-up-status"><option>Pendiente</option><option>En proceso</option><option>Completada</option><option>Cancelada</option></select></div>
<div class="form-group"><label>Resultado observado</label><select class="form-control" name="outcome" id="risk-up-outcome"><option value="">Sin evaluar</option><option>Mejoró</option><option>Sin cambio</option><option>Empeoró</option><option>No evaluado</option></select></div>
<div class="form-group"><label>Próximo seguimiento</label><input type="date" class="form-control" name="followup_date" id="risk-up-followup"></div>
<div class="form-group"><label>Observaciones</label><textarea class="form-control" name="notes" id="risk-up-notes" rows="3" maxlength="1000"></textarea></div>
<div class="risk-note"><i class="fas fa-chart-line mr-1"></i>Si todavía no existe un nuevo bimestre cerrado, la intervención puede completarse pero la medición predictiva posterior quedará pendiente.</div>
</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Actualizar</button></div></form></div></div>

<script>
(function($){
 const API='risk_dashboard_api.php',CSRF=<?php echo json_encode($csrf); ?>; let cache=null,currentStudent=null;
 const esc=v=>$('<div>').text(v==null?'':v).html(); const pct=v=>(Number(v||0)*100).toFixed(1)+'%';
 const statusClass=s=>'risk-status-'+String(s||'').replace(/\s+/g,'');
 function params(){const q=new URLSearchParams({action:'dashboard'});[['level','#risk-level'],['grade','#risk-grade'],['section','#risk-section'],['bimestre','#risk-bimester']].forEach(([k,s])=>{let v=$(s).val();if(v)q.set(k,v)});return q.toString()}
 function notice(text,type='warning'){$('#risk-alert').html('<div class="alert alert-'+type+'">'+esc(text)+'</div>')}
 function card(label,value,tone,icon){return '<div class="col-xl-3 col-md-6 mb-3"><div class="risk-card"><div class="d-flex justify-content-between"><div><small>'+esc(label)+'</small><strong>'+esc(value)+'</strong></div><span class="risk-icon risk-'+tone+'"><i class="fas '+icon+'"></i></span></div></div></div>'}
 function factorText(f){if(!f)return '';let raw=Number(f.value||0),v=f.feature==='attendance_rate_30d'?raw.toFixed(1)+'%':(['grade_mean_current','grade_mean_previous','grade_trend'].includes(f.feature)?raw.toFixed(2):raw.toFixed(0));return esc(f.label||f.feature)+': '+v}
 async function load(){ $('#risk-loading').removeClass('d-none');$('#risk-content').addClass('d-none');$('#risk-alert').empty();try{let r=await fetch(API+'?'+params(),{credentials:'same-origin'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'No se pudo cargar el panel.');cache=d;render(d)}catch(e){notice(e.message,'danger')}finally{$('#risk-loading').addClass('d-none')}}
 function render(d){$('#risk-content').removeClass('d-none');if(!d.model.available)notice('El modelo debe reentrenarse con la política temporal de bimestres cerrados antes de mostrar predicciones.','warning');else if(!d.migration_ready)notice('La predicción funciona, pero falta ejecutar sql/predictive_interventions_upgrade.sql para registrar intervenciones.','warning');
 let s=d.summary||{};$('#risk-cards').html(card('Riesgo alto',s.high||0,'danger','fa-exclamation-triangle')+card('Riesgo medio',s.medium||0,'warning','fa-exclamation-circle')+card('Riesgo bajo',s.low||0,'success','fa-check-circle')+card('Evaluados',s.evaluated||0,'primary','fa-users'));
 let rows='';(d.predictions||[]).forEach(x=>{let st=x.student,f=(x.factors||[]).map(factorText).join('<br>'),base=x.bimester_label||x.bimester,target=x.target_bimester_label||x.target_bimester;rows+='<tr><td><strong>'+esc(st.name)+'</strong><div class="text-muted small">'+esc(base)+' cerrado → riesgo en '+esc(target)+(x.base_closed_at?' · corte '+esc(x.base_closed_at):'')+'</div></td><td>'+esc(st.nivel)+'<br>'+esc(st.grado)+'° '+esc(st.seccion)+'</td><td><span class="risk-badge risk-badge-'+esc(x.level)+'">'+esc(x.level)+' · '+pct(x.probability)+'</span></td><td class="risk-factor">'+(f||'Sin factor dominante')+'</td><td class="text-center"><span class="badge badge-light border">'+esc(x.open_interventions||0)+'</span></td><td class="text-right risk-actions"><button class="btn btn-sm btn-outline-primary risk-sim" data-id="'+st.id+'"><i class="fas fa-project-diagram"></i></button><button class="btn btn-sm btn-primary risk-new" data-id="'+st.id+'"><i class="fas fa-hands-helping"></i></button></td></tr>'});$('#risk-students').html(rows||'<tr><td colspan="6" class="risk-empty">No hay predicciones disponibles. Verifica que exista un bimestre cerrado y un modelo v3 entrenado.</td></tr>');
 let factors=d.factors||[],max=Math.max(...factors.map(x=>Number(x.count||0)),1),fh='';factors.forEach(x=>fh+='<div class="risk-bar-row"><span>'+esc(x.label)+'</span><div class="risk-track"><div class="risk-fill" style="width:'+(Number(x.count||0)/max*100)+'%"></div></div><strong>'+esc(x.count)+'</strong></div>');$('#risk-factors').html(fh||'<div class="risk-empty">Sin factores agregados.</div>');
 renderInterventions(d.interventions||[],d.intervention_summary||{});let e=d.effectiveness||{};$('#risk-effectiveness').html('<div class="row"><div class="col-6 mb-2"><div class="risk-modal-kpi"><small>Intervenciones medidas</small><strong>'+esc(e.measured||0)+'</strong></div></div><div class="col-6 mb-2"><div class="risk-modal-kpi"><small>Con menor riesgo</small><strong>'+esc(e.improved||0)+'</strong></div></div></div>'+(e.average_probability_reduction!=null?'<div class="alert alert-light border mt-2 mb-0"><strong>Reducción media observada:</strong> '+(Number(e.average_probability_reduction)*100).toFixed(1)+' puntos porcentuales.<div class="risk-note mt-1">Es una comparación antes/después; por sí sola no prueba causalidad.</div></div>':'<div class="risk-empty">Las mediciones posteriores aparecen cuando exista un nuevo bimestre cerrado después de la intervención.</div>'))}
 function renderInterventions(rows,sum){let html='';rows.forEach(r=>html+='<tr><td><strong>'+esc(r.student_name)+'</strong><div class="small text-muted">'+esc(r.nivel)+' · '+esc(r.grado)+'° '+esc(r.seccion)+'</div></td><td>'+esc(r.intervention_type)+'<div class="small text-muted">'+esc(r.title)+'</div></td><td><span class="risk-badge '+statusClass(r.status)+'">'+esc(r.status)+'</span>'+(r.status==='Completada'&&r.post_risk_probability==null?'<div class="small text-muted mt-1">Medición posterior pendiente</div>':'')+'</td><td>'+esc(r.followup_date||'—')+'</td><td>'+(r.risk_probability!=null?pct(r.risk_probability):'—')+'</td><td class="text-right"><button class="btn btn-sm btn-outline-secondary risk-edit" data-id="'+r.id+'"><i class="fas fa-edit"></i></button></td></tr>');$('#risk-interventions').html(html||'<tr><td colspan="6" class="risk-empty">Todavía no hay intervenciones registradas.</td></tr>');$('#risk-intervention-kpis').text('Pendientes: '+(sum['Pendiente']||0)+' · En proceso: '+(sum['En proceso']||0)+' · Seguimientos vencidos: '+(sum['Seguimientos vencidos']||0))}
 function findPrediction(id){return (cache?.predictions||[]).find(x=>Number(x.student.id)===Number(id))}
 async function studentDetail(id){let r=await fetch(API+'?action=student&student_id='+encodeURIComponent(id),{credentials:'same-origin'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'No se pudo consultar al estudiante.');return d}
 $(document).on('click','.risk-sim',async function(){try{let d=await studentDetail($(this).data('id'));currentStudent=d.student;let cf=d.counterfactual,p=d.prediction;if(!cf.available){$('#risk-scenario-body').html('<div class="alert alert-warning">No hay información suficiente o no existe un bimestre cerrado válido para simular cambios.</div>')}else{let rec=cf.recommended,base=p.bimester_label||p.bimester,target=p.target_bimester_label||p.target_bimester,h='<div class="alert alert-light border"><strong>Base:</strong> '+esc(base)+' bimestre cerrado'+(p.base_closed_at?' ('+esc(p.base_closed_at)+')':'')+' · <strong>Objetivo:</strong> riesgo en '+esc(target)+' bimestre.</div><div class="row mb-3"><div class="col-6"><div class="risk-modal-kpi"><small>Riesgo estimado</small><strong>'+esc(p.level)+' · '+pct(p.probability)+'</strong></div></div><div class="col-6"><div class="risk-modal-kpi"><small>Escenario recomendado</small><strong>'+(rec?esc(rec.level)+' · '+pct(rec.probability):'Ya es bajo')+'</strong></div></div></div>';if(rec){h+='<h6 class="font-weight-bold">'+esc(rec.name)+'</h6>';rec.changes.forEach(c=>h+='<div class="risk-change"><strong>'+esc(c.label)+'</strong>: '+(c.feature==='attendance_rate_30d'?Number(c.before).toFixed(1)+'%':Number(c.before).toFixed(1))+' → '+(c.feature==='attendance_rate_30d'?Number(c.after).toFixed(1)+'%':Number(c.after).toFixed(1))+'</div>')}h+='<div class="alert alert-light border mt-3 mb-0"><i class="fas fa-info-circle mr-1"></i>Simulación del comportamiento del modelo. No constituye una predicción causal ni garantiza que estas acciones produzcan exactamente ese cambio.</div>';$('#risk-scenario-body').html(h)}$('#riskScenarioModal').modal('show')}catch(e){notice(e.message,'danger')}});
 function openNew(id){let x=findPrediction(id);if(!x)return;currentStudent=x.student;$('#risk-int-student').val(x.student.id);$('#risk-int-student-label').html('<strong>'+esc(x.student.name)+'</strong><br><small>'+esc(x.student.nivel)+' · '+esc(x.student.grado)+'° '+esc(x.student.seccion)+' · riesgo '+esc(x.level)+' '+pct(x.probability)+'</small>');$('#risk-int-type').val(x.suggested?.type||'Seguimiento tutorial');$('#risk-int-title').val(x.suggested?.title||'Seguimiento preventivo de riesgo académico');$('#riskInterventionModal').modal('show')}
 $(document).on('click','.risk-new',function(){openNew($(this).data('id'))});$('#risk-scenario-intervene').on('click',function(){if(currentStudent){$('#riskScenarioModal').modal('hide');openNew(currentStudent.id)}});
 $('#risk-intervention-form').on('submit',async function(e){e.preventDefault();let fd=new FormData(this);fd.set('action','create_intervention');fd.set('csrf_token',CSRF);try{let r=await fetch(API,{method:'POST',body:fd,credentials:'same-origin'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'No se pudo guardar.');$('#riskInterventionModal').modal('hide');notice(d.message,'success');this.reset();load()}catch(err){notice(err.message,'danger')}});
 $(document).on('click','.risk-edit',function(){let id=Number($(this).data('id')),r=(cache?.interventions||[]).find(x=>Number(x.id)===id);if(!r)return;$('#risk-up-id').val(r.id);$('#risk-up-label').html('<strong>'+esc(r.student_name)+'</strong><br><small>'+esc(r.intervention_type)+' · '+esc(r.title)+'</small>');$('#risk-up-status').val(r.status);$('#risk-up-outcome').val(r.outcome||'');$('#risk-up-followup').val(r.followup_date||'');$('#risk-up-notes').val(r.notes||'');$('#riskUpdateModal').modal('show')});
 $('#risk-update-form').on('submit',async function(e){e.preventDefault();let fd=new FormData(this);fd.set('action','update_intervention');fd.set('csrf_token',CSRF);try{let r=await fetch(API,{method:'POST',body:fd,credentials:'same-origin'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'No se pudo actualizar.');$('#riskUpdateModal').modal('hide');notice(d.message,'success');load()}catch(err){notice(err.message,'danger')}});
 $('#risk-refresh,#risk-apply').on('click',load); load();
})(jQuery);
</script>