<?php
require_once __DIR__.'/predictive_course_risk.php';
require_once __DIR__.'/predictive_interventions.php';

function edu_course_interventions_ready(mysqli $conn): bool {
    return edu_risk_interventions_ready($conn)&&edu_predictive_column_exists($conn,'student_risk_interventions','course_id')&&edu_predictive_column_exists($conn,'student_risk_interventions','course_name');
}
function edu_course_intervention_find_course(array $prediction,int $courseId): ?array {foreach((array)($prediction['courses']??[]) as $c)if((int)$c['course_id']===$courseId)return$c;return null;}
function edu_course_intervention_suggestion(array $course): array {
    $f=(array)($course['features']??[]);if(($f['attendance_rate_30d']??null)!==null&&(float)$f['attendance_rate_30d']<85)return['type'=>'Seguimiento de asistencia','title'=>'Seguimiento de asistencia y rendimiento en '.$course['course_name']];if((float)($f['absent_30d']??0)>=3)return['type'=>'Seguimiento de asistencia','title'=>'Plan de asistencia para '.$course['course_name']];if((float)($f['late_30d']??0)>=3)return['type'=>'Plan de puntualidad','title'=>'Plan de puntualidad y seguimiento en '.$course['course_name']];return['type'=>'Reforzamiento académico','title'=>'Reforzamiento en '.$course['course_name']];
}
function edu_course_create_intervention(mysqli $conn,array $actor,array $data): array {
    if((int)($actor['type']??0)!==1)return['ok'=>false,'message'=>'Solo administración puede registrar intervenciones.'];if(!edu_course_interventions_ready($conn))return['ok'=>false,'message'=>'Falta ejecutar sql/predictive_course_risk_upgrade.sql para vincular intervenciones a cursos.'];
    $studentId=(int)($data['student_id']??0);$courseId=(int)($data['course_id']??0);if($studentId<=0||$courseId<=0)return['ok'=>false,'message'=>'Selecciona un estudiante y un curso.'];$prediction=edu_course_risk_student_prediction($conn,$actor,$studentId,null,false);if(empty($prediction['available']))return['ok'=>false,'message'=>'No hay una predicción v6 disponible para este estudiante.'];$course=edu_course_intervention_find_course($prediction,$courseId);if(!$course)return['ok'=>false,'message'=>'El curso seleccionado no pertenece a la predicción actual del estudiante.'];
    $type=trim((string)($data['intervention_type']??''));if(!in_array($type,edu_risk_intervention_types(),true))return['ok'=>false,'message'=>'Tipo de intervención no válido.'];$title=trim((string)($data['title']??''));if($title===''||mb_strlen($title,'UTF-8')>160)return['ok'=>false,'message'=>'Escribe un título de hasta 160 caracteres.'];$notes=trim((string)($data['notes']??''));if(mb_strlen($notes,'UTF-8')>1000)return['ok'=>false,'message'=>'Las observaciones no pueden superar 1000 caracteres.'];$planned=trim((string)($data['planned_date']??''));$followup=trim((string)($data['followup_date']??''));foreach([$planned,$followup] as $d)if($d!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$d))return['ok'=>false,'message'=>'Fecha no válida.'];$planned=$planned?:null;$followup=$followup?:null;
    $schoolId=(int)$actor['school_id'];$yearId=(int)$prediction['academic_year_id'];$source=(int)$prediction['source_bimester'];$target=(int)$prediction['target_bimester'];$prob=(float)$course['probability'];$level=(string)$course['level'];$courseName=(string)$course['course_name'];$userId=edu_risk_actor_user_id($actor);
    $stmt=$conn->prepare("INSERT INTO student_risk_interventions (school_id,academic_year_id,student_id,course_id,course_name,source_bimester,target_bimester,risk_probability,risk_level,intervention_type,title,notes,status,planned_date,followup_date,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'Pendiente',?,?,?,?)");if(!$stmt)return['ok'=>false,'message'=>'No pude preparar la intervención.'];$types='iiiisiidssssssii';$params=[$schoolId,$yearId,$studentId,$courseId,$courseName,$source,$target,$prob,$level,$type,$title,$notes,$planned,$followup,$userId,$userId];edu_predictive_bind($stmt,$types,$params);if(!$stmt->execute()){$stmt->close();return['ok'=>false,'message'=>'No pude registrar la intervención.'];}$id=(int)$stmt->insert_id;$stmt->close();edu_risk_log($conn,$id,$schoolId,$studentId,$userId,'create_course_intervention',['course_id'=>$courseId,'course_name'=>$courseName,'risk_probability'=>$prob,'risk_level'=>$level,'source_bimester'=>$source,'target_bimester'=>$target]);return['ok'=>true,'id'=>$id,'message'=>'Intervención registrada para '.$courseName.'.'];
}
function edu_course_update_intervention(mysqli $conn,array $actor,int $id,array $data): array {
    if(!edu_course_interventions_ready($conn))return edu_risk_update_intervention($conn,$actor,$id,$data);$schoolId=(int)($actor['school_id']??0);$stmt=$conn->prepare('SELECT * FROM student_risk_interventions WHERE id=? AND school_id=? LIMIT 1');if(!$stmt)return['ok'=>false,'message'=>'No pude consultar la intervención.'];$stmt->bind_param('ii',$id,$schoolId);$stmt->execute();$row=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$row)return['ok'=>false,'message'=>'No encontré la intervención.'];if(empty($row['course_id']))return edu_risk_update_intervention($conn,$actor,$id,$data);
    $status=trim((string)($data['status']??$row['status']));if(!in_array($status,edu_risk_statuses(),true))return['ok'=>false,'message'=>'Estado no válido.'];$outcome=trim((string)($data['outcome']??($row['outcome']??'')));if($outcome!==''&&!in_array($outcome,edu_risk_outcomes(),true))return['ok'=>false,'message'=>'Resultado no válido.'];$notes=trim((string)($data['notes']??($row['notes']??'')));$followup=trim((string)($data['followup_date']??($row['followup_date']??'')));if($followup!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$followup))return['ok'=>false,'message'=>'Fecha no válida.'];$followup=$followup?:null;$outcome=$outcome?:null;$completed=$row['completed_at']??null;$post=$row['post_risk_probability']!==null?(float)$row['post_risk_probability']:null;$pending=false;
    if($status==='Completada'){$completed=date('Y-m-d H:i:s');if($outcome===null)$outcome='No evaluado';$latest=edu_predictive_latest_closed_bimester($conn,$schoolId,(int)$row['academic_year_id']);if($latest!==null&&$latest>(int)$row['source_bimester']&&$latest<4){$p=edu_course_risk_student_prediction($conn,$actor,(int)$row['student_id'],$latest,false);$c=!empty($p['available'])?edu_course_intervention_find_course($p,(int)$row['course_id']):null;if($c)$post=(float)$c['probability'];else{$post=null;$pending=true;}}else{$post=null;$pending=true;}}
    $userId=edu_risk_actor_user_id($actor);$stmt=$conn->prepare('UPDATE student_risk_interventions SET status=?,outcome=?,notes=?,followup_date=?,completed_at=?,post_risk_probability=?,updated_by=? WHERE id=? AND school_id=?');if(!$stmt)return['ok'=>false,'message'=>'No pude preparar la actualización.'];$types='sssssdiii';$params=[$status,$outcome,$notes,$followup,$completed,$post,$userId,$id,$schoolId];edu_predictive_bind($stmt,$types,$params);if(!$stmt->execute()){$stmt->close();return['ok'=>false,'message'=>'No pude actualizar la intervención.'];}$stmt->close();edu_risk_log($conn,$id,$schoolId,(int)$row['student_id'],$userId,'update_course_intervention',['course_id'=>(int)$row['course_id'],'status'=>$status,'post_course_risk_probability'=>$post,'measurement_pending'=>$pending]);$msg='Intervención actualizada.';if($pending)$msg.=' La medición posterior del mismo curso queda pendiente hasta un nuevo cierre válido.';return['ok'=>true,'message'=>$msg,'measurement_pending'=>$pending];
}
