<?php
require_once __DIR__.'/predictive_course_risk.php';
require_once __DIR__.'/predictive_course_interventions.php';

function edu_predictive_is_query(string $message): bool {
    $n=function_exists('edu_chat_normalize')?edu_chat_normalize($message):strtolower(trim($message));
    foreach(['alerta temprana','curso en riesgo','cursos en riesgo','riesgo academico','riesgo futuro','predecir','prediccion','probabilidad','tendencia','rendimiento critico','puede desaprobar','puede jalar','por que esta en riesgo','asistencia y riesgo'] as $x)if(strpos($n,$x)!==false)return true;return false;
}
function edu_course_chat_student_from_message(mysqli $conn,array $actor,string $message,array $history=[]): string {
    $n=function_exists('edu_chat_normalize')?edu_chat_normalize($message):strtolower($message);$best='';$bestLen=0;
    foreach(edu_predictive_students($conn,$actor,[],'',500) as $s){$name=trim((string)$s['name']);$nn=function_exists('edu_chat_normalize')?edu_chat_normalize($name):strtolower($name);if($nn!==''&&strpos($n,$nn)!==false&&strlen($nn)>$bestLen){$best=$name;$bestLen=strlen($nn);}}
    if($best!=='')return$best;
    if(strpos($n,'el primero')!==false||strpos($n,'la primera')!==false){for($i=count($history)-1;$i>=0;$i--){if(($history[$i]['role']??'')!=='assistant')continue;$text=(string)($history[$i]['text']??'');if(preg_match('/(?:^|\n)1\.\s+(.+?)\s+—/u',$text,$m))return trim($m[1]);}}
    $patterns=['/\bcursos?\s+en\s+riesgo\s+(?:de|del|para)\s+(.+)$/','/\briesgo\s+(?:de|del|para)\s+(.+)$/','/\bpara\s+(.+)$/'];foreach($patterns as $p)if(preg_match($p,$n,$m))return trim((string)$m[1]," .,:;?¿!¡");return'';
}
function edu_course_chat_course_from_message(mysqli $conn,array $actor,string $message): ?string {return function_exists('edu_chat_find_course')?edu_chat_find_course($conn,(int)$actor['school_id'],function_exists('edu_chat_normalize')?edu_chat_normalize($message):strtolower($message)):null;}
function edu_course_chat_resolve_student(mysqli $conn,array $actor,string $name,array $entities=[]): array {
    if(trim($name)==='')return['ok'=>false,'result'=>edu_chat_result('Indica el nombre del estudiante. Por ejemplo: “¿Qué cursos están en riesgo de Juan Pérez?”')];$matches=edu_predictive_students($conn,$actor,$entities,$name,8);if(!$matches)return['ok'=>false,'result'=>edu_chat_result('No encontré un estudiante activo que coincida con ese nombre.')];if(count($matches)>1){$lines=[];foreach($matches as $i=>$s)$lines[]=($i+1).'. '.$s['name'].' — '.$s['nivel'].' · '.$s['grado'].'° '.$s['seccion'];return['ok'=>false,'result'=>edu_chat_result("Encontré varias coincidencias. Especifica el nombre completo o el aula:\n".implode("\n",$lines))];}return['ok'=>true,'student'=>$matches[0]];
}
function edu_course_chat_trend(array $history): string {if(!$history)return'sin tendencia comparable';$parts=[];foreach($history as $p)$parts[]=edu_predictive_bimester_label((int)$p['bimester']).' '.number_format((float)$p['course_mean_current'],1);return implode(' → ',$parts);}
function edu_course_chat_general_result(mysqli $conn,array $actor,array $student,?int $bimester=null): array {
    $p=edu_course_risk_student_prediction($conn,$actor,(int)$student['id'],$bimester,false);if(empty($p['available'])){$reason=$p['reason']??'';$msg=$reason==='model'?'El nuevo modelo por curso todavía no está entrenado. Debe generarse course_risk_model.json antes de mostrar probabilidades.':'No hay un bimestre cerrado con información suficiente para analizar cursos de '.$student['name'].'.';$r=edu_chat_result($msg);$r['tools_used']=['course_risk_model'];return$r;}
    $g=$p['general'];$lines=[];$lines[]=$student['name'].' — prioridad académica general: '.$g['level'].'.';$lines[]='Base: '.$p['source_bimester_label'].' bimestre cerrado → se estima el '.$p['target_bimester_label'].' bimestre.';$lines[]=$g['attention_courses'].' curso(s) requieren atención. La prioridad general se deriva de los cursos; no es un porcentaje adicional inventado.';
    foreach(array_slice($p['courses'],0,8) as $c){if($c['level']==='Bajo'&&$g['attention_courses']>0)continue;$f=$c['features'];$lines[]='• '.$c['course_name'].': '.$c['level'].' ('.number_format($c['probability']*100,1).'%) · tendencia '.edu_course_chat_trend($c['history_same_year']).' · promedio actual '.($f['course_mean_current']===null?'sin dato':number_format($f['course_mean_current'],1)).'.';}
    $first=$p['courses'][0]['features']??[];if(($first['attendance_rate_30d']??null)!==null)$lines[]='Asistencia previa al cierre: '.number_format((float)$first['attendance_rate_30d'],1).'%; ausencias '.(int)$first['absent_30d'].'; tardanzas '.(int)$first['late_30d'].'.';$lines[]='“Riesgo” significa probabilidad de rendimiento crítico en ese curso el siguiente bimestre; no garantiza que el estudiante vaya a desaprobar.';
    $r=edu_chat_result(implode("\n",$lines),['¿Por qué está en riesgo su curso con mayor alerta?','Muéstrame la tendencia de uno de sus cursos','¿Cómo influye su asistencia?'],[],[edu_chat_action('Abrir Alerta Temprana Inteligente','risk_dashboard','fa-brain')]);$r['tools_used']=['course_risk_model'];return$r;
}
function edu_course_chat_specific_result(mysqli $conn,array $actor,array $student,string $courseName,?int $bimester=null): array {
    $p=edu_course_risk_student_prediction($conn,$actor,(int)$student['id'],$bimester,true);if(empty($p['available']))return edu_chat_result('No hay una predicción por curso disponible para '.$student['name'].'.');$needle=edu_course_risk_norm($courseName);$course=null;foreach($p['courses'] as $c)if(edu_course_risk_norm((string)$c['course_name'])===$needle){$course=$c;break;}if(!$course)return edu_chat_result('No encontré '.$courseName.' entre los cursos con información disponible para '.$student['name'].'.');
    $f=$course['features'];$lines=[];$lines[]=$student['name'].' — '.$course['course_name'].': riesgo '.$course['level'].' de rendimiento crítico en el '.$p['target_bimester_label'].' bimestre ('.number_format($course['probability']*100,1).'%).';$lines[]='Tendencia del año: '.edu_course_chat_trend($course['history_same_year']).'.';$lines[]='Promedio actual del curso: '.($f['course_mean_current']===null?'sin dato':number_format($f['course_mean_current'],1)).' · referencia crítica: menos de '.edu_predictive_critical_threshold().'.';$lines[]='Evaluaciones/calificaciones bajas: '.(int)$f['low_grade_cells'].' de '.(int)$f['graded_cells'].'. Calificaciones faltantes: '.(int)$f['missing_grade_cells'].'; las faltantes no se convierten en cero.';
    if($f['attendance_rate_30d']!==null)$lines[]='Asistencia: '.number_format((float)$f['attendance_rate_30d'],1).'%; ausencias '.(int)$f['absent_30d'].'; tardanzas '.(int)$f['late_30d'].'.';else$lines[]='Asistencia: no hay registros suficientes en la ventana previa al cierre.';
    if($f['class_students_critical_rate']!==null)$lines[]='Contexto del aula: '.number_format((float)$f['class_students_critical_rate']*100,1).'% de estudiantes con datos del curso están en zona crítica; promedio del aula '.number_format((float)$f['class_course_mean_current'],1).'.';
    if($course['reasons']){$lines[]='Motivos principales de la alerta:';foreach($course['reasons'] as $reason)$lines[]='• '.$reason;}
    if(!empty($course['history_across_years'])){$lines[]='Historia del mismo curso:';foreach($course['history_across_years'] as $y){$parts=[];foreach($y['periods'] as $pp)$parts[]=$pp['label'].' '.number_format((float)$pp['mean'],1);$lines[]='• '.$y['year'].': '.implode(' → ',$parts).'.';}}
    if(empty($f['evaluation_date_available'])&&(int)$f['missing_grade_cells']>0)$lines[]='No hay una fecha académica específica de evaluación disponible para afirmar si las calificaciones faltantes coinciden con una ausencia.';elseif(($f['missing_eval_absence_overlap']??null)!==null&&(int)$f['missing_eval_absence_overlap']>0)$lines[]='Hay '.(int)$f['missing_eval_absence_overlap'].' evaluación(es) sin nota cuya fecha coincide con ausencia. Es una asociación para revisar, no prueba de causalidad.';
    $lines[]='La estimación combina estas señales históricas; no afirma que una ausencia o un docente sean la causa del resultado.';$r=edu_chat_result(implode("\n",$lines),['¿Qué otros cursos están en riesgo?','¿Cómo ha evolucionado este curso por años?','Abrir Alerta Temprana Inteligente'],[],[edu_chat_action('Abrir Alerta Temprana Inteligente','risk_dashboard','fa-brain')]);$r['tools_used']=['course_risk_model_detail'];return$r;
}
function edu_course_chat_model_report(): array {$m=edu_course_risk_model_load();if(empty($m['available']))return edu_chat_result('El modelo predictivo por curso todavía no está entrenado o no es válido.');$tr=$m['training']??[];$met=$m['metrics']['holdout_grouped_student']??[];$schema=(int)($m['schema_version']??0);$variant=(string)($m['model_variant']??'');$lines=['Modelo actual: v'.$schema.' · '.$variant.'.','Objetivo: estimar si el mismo curso presentará rendimiento crítico en el siguiente bimestre.','No usa teacher_id como predictor.'];if($schema>=7)$lines[]='La v7 incorpora trayectoria del mismo año, historial de años anteriores, dinámica de evaluaciones, competencias, asistencia y contexto del aula.';else$lines[]='La versión actual usa rendimiento del curso, tendencia, evaluaciones, asistencia y contexto del aula.';if(isset($tr['rows']))$lines[]='Entrenamiento: '.(int)$tr['rows'].' filas curso-periodo de '.(int)($tr['students']??0).' estudiantes.';foreach(['recall'=>'Recall','precision'=>'Precision','f1'=>'F1','roc_auc'=>'ROC-AUC','brier_score'=>'Brier','ece'=>'ECE'] as $k=>$label)if(isset($met[$k])&&$met[$k]!==null)$lines[]=$label.': '.number_format((float)$met[$k],3).'.';$r=edu_chat_result(implode("\n",$lines));$r['tools_used']=['course_risk_model'];return$r;}
function edu_predictive_try(mysqli $conn,array $actor,string $message,array $state=[],array $history=[]): ?array {
    if((int)($actor['type']??0)!==1)return null;$n=function_exists('edu_chat_normalize')?edu_chat_normalize($message):strtolower(trim($message));$entities=function_exists('edu_chat_adv_entities')?edu_chat_adv_entities($n,$state):(function_exists('edu_chat_entities')?edu_chat_entities($n):[]);
    if(edu_chat_has($n,['modelo predictivo','metricas del modelo','como funciona el modelo','modelo de riesgo']))return edu_course_chat_model_report();
    if(edu_chat_has($n,['intervencion','intervenciones','seguimiento'])&&function_exists('edu_risk_interventions_chat_result')){$name=edu_course_chat_student_from_message($conn,$actor,$message,$history);return edu_risk_interventions_chat_result($conn,$actor,$name,$entities);}
    if(!edu_predictive_is_query($message)&&!edu_chat_has($n,['riesgo','critico','tendencia','desaprobar','jalar']))return null;$name=edu_course_chat_student_from_message($conn,$actor,$message,$history);$resolved=edu_course_chat_resolve_student($conn,$actor,$name,$entities);if(empty($resolved['ok']))return$resolved['result'];$course=edu_course_chat_course_from_message($conn,$actor,$message);$b=!empty($entities['bimestre'])?(int)$entities['bimestre']:null;if($course)return edu_course_chat_specific_result($conn,$actor,$resolved['student'],$course,$b);return edu_course_chat_general_result($conn,$actor,$resolved['student'],$b);
}
