<?php
require_once __DIR__.'/predictive_course_risk.php';
require_once __DIR__.'/predictive_course_history.php';
require_once __DIR__.'/predictive_interventions.php';

function edu_course_dashboard_filter_options(mysqli $conn,array $actor): array {
    $schoolId=(int)($actor['school_id']??0);$levels=[];$grades=[];$sections=[];$courses=[];if($schoolId<=0)return compact('levels','grades','sections','courses');
    $stmt=$conn->prepare("SELECT DISTINCT TRIM(s.nivel) nivel,CAST(s.grado AS UNSIGNED) grado,UPPER(TRIM(COALESCE(NULLIF(s.seccion,''),'U'))) seccion FROM student s WHERE s.school_id=? AND LOWER(TRIM(COALESCE(s.status,'Activo'))) IN ('activo','active') ORDER BY FIELD(TRIM(s.nivel),'Inicial','Primaria','Secundaria'),CAST(s.grado AS UNSIGNED),seccion");if($stmt){$stmt->bind_param('i',$schoolId);$stmt->execute();$res=$stmt->get_result();while($r=$res->fetch_assoc()){$l=(string)$r['nivel'];$g=(int)$r['grado'];$s=(string)$r['seccion'];if($l!==''&&!in_array($l,$levels,true))$levels[]=$l;if($l!==''&&$g>0){$grades[$l]=$grades[$l]??[];if(!in_array($g,$grades[$l],true))$grades[$l][]=$g;$key=$l.'|'.$g;$sections[$key]=$sections[$key]??[];if($s!==''&&!in_array($s,$sections[$key],true))$sections[$key][]=$s;}}$stmt->close();}
    $year=edu_predictive_academic_year($conn,$schoolId,null);if($year){$yearId=(int)$year['id'];$hasYear=edu_predictive_column_exists($conn,'teacher_courses','academic_year_id');$sql="SELECT DISTINCT ac.id,ac.name FROM teacher_courses tc INNER JOIN academic_courses ac ON ac.id=tc.course_id WHERE tc.school_id=?".($hasYear?' AND tc.academic_year_id=?':'')." ORDER BY ac.name";$stmt=$conn->prepare($sql);if($stmt){if($hasYear)$stmt->bind_param('ii',$schoolId,$yearId);else$stmt->bind_param('i',$schoolId);$stmt->execute();$res=$stmt->get_result();while($r=$res->fetch_assoc())$courses[]=['id'=>(int)$r['id'],'name'=>(string)$r['name']];$stmt->close();}}
    foreach($grades as &$a)sort($a,SORT_NUMERIC);unset($a);foreach($sections as &$a)sort($a,SORT_NATURAL);unset($a);return compact('levels','grades','sections','courses');
}
function edu_course_dashboard_data(mysqli $conn,array $actor,array $filters=[]): array {
    if((int)($actor['type']??0)!==1)return['ok'=>false,'message'=>'Este módulo está disponible únicamente para administración.'];$model=edu_course_risk_model_load();$academic=[];foreach(['level','grade','section'] as $k)if(!empty($filters[$k]))$academic[$k]=$filters[$k];$search=trim((string)($filters['search']??''));$risk=trim((string)($filters['risk_level']??''));if(!in_array($risk,['Alto','Medio','Bajo'],true))$risk='';$courseId=(int)($filters['course_id']??0);$bim=!empty($filters['bimestre'])?(int)$filters['bimestre']:null;$students=edu_predictive_students($conn,$actor,$academic,$search,250);$items=[];$summary=['Alto'=>0,'Medio'=>0,'Bajo'=>0,'attention_courses'=>0,'high_courses'=>0];$patterns=[];$evaluated=0;
    if(!empty($model['available']))foreach($students as $student){$p=edu_course_risk_student_prediction($conn,$actor,(int)$student['id'],$bim,false);if(empty($p['available']))continue;$courses=(array)$p['courses'];if($courseId>0)$courses=array_values(array_filter($courses,static fn($c)=>(int)$c['course_id']===$courseId));if(!$courses)continue;$general=edu_course_risk_general_priority($courses);$evaluated++;$summary[$general['level']]++;$summary['attention_courses']+=(int)$general['attention_courses'];$summary['high_courses']+=(int)$general['high_courses'];if($risk!==''&&$general['level']!==$risk)continue;$top=array_slice($courses,0,4);$attendance=null;$absent=null;$late=null;
        foreach($courses as $c){$f=(array)$c['features'];if($attendance===null&&$f['attendance_rate_30d']!==null)$attendance=(float)$f['attendance_rate_30d'];if($absent===null&&$f['absent_30d']!==null)$absent=(float)$f['absent_30d'];if($late===null&&$f['late_30d']!==null)$late=(float)$f['late_30d'];$key=edu_course_risk_norm((string)$c['course_name']).'|'.edu_course_risk_norm((string)$student['nivel']).'|'.(int)$student['grado'].'|'.edu_course_risk_norm((string)$student['seccion']);if(!isset($patterns[$key])&&$f['class_students_critical_rate']!==null)$patterns[$key]=['course_name'=>$c['course_name'],'nivel'=>$student['nivel'],'grado'=>$student['grado'],'seccion'=>$student['seccion'],'class_mean'=>$f['class_course_mean_current'],'critical_student_rate'=>$f['class_students_critical_rate'],'low_grade_rate'=>$f['class_low_grade_rate_current'],'evaluations_count'=>$f['evaluations_count_current'],'students_with_data'=>$f['class_students_with_data']??0];}
        $items[]=['student'=>$p['student'],'source_bimester'=>$p['source_bimester'],'source_label'=>$p['source_bimester_label'],'target_bimester'=>$p['target_bimester'],'target_label'=>$p['target_bimester_label'],'base_closed_at'=>$p['base_closed_at'],'general'=>$general,'courses'=>$top,'course_count'=>count($courses),'attendance'=>['rate'=>$attendance,'absent'=>$absent,'late'=>$late]];}
    usort($items,static function($a,$b){$rank=['Alto'=>3,'Medio'=>2,'Bajo'=>1];$r=($rank[$b['general']['level']]??0)<=>($rank[$a['general']['level']]??0);if($r!==0)return$r;$r=($b['general']['attention_courses']??0)<=>($a['general']['attention_courses']??0);return$r!==0?$r:(($b['general']['max_course_probability']??0)<=>($a['general']['max_course_probability']??0));});$patterns=array_values($patterns);usort($patterns,static fn($a,$b)=>($b['critical_student_rate']??0)<=>($a['critical_student_rate']??0));$patterns=array_slice($patterns,0,12);
    $interventionFilters=$academic;if(!empty($filters['intervention_status']))$interventionFilters['status']=$filters['intervention_status'];$interventions=edu_risk_list_interventions($conn,$actor,$interventionFilters,100);if($search!=='')$interventions=array_values(array_filter($interventions,static fn($r)=>stripos((string)($r['student_name']??''),$search)!==false));$period=$items[0]??null;$courseInterventionReady=edu_risk_interventions_ready($conn)&&edu_predictive_column_exists($conn,'student_risk_interventions','course_id')&&edu_predictive_column_exists($conn,'student_risk_interventions','course_name');
    return['ok'=>true,'model'=>['available'=>!empty($model['available']),'reason'=>$model['reason']??null,'created_at'=>$model['created_at']??null,'schema_version'=>$model['schema_version']??null,'variant'=>$model['model_variant']??null,'thresholds'=>$model['risk_thresholds']??[]],'period'=>['base'=>$period['source_label']??null,'target'=>$period['target_label']??null,'cutoff'=>$period['base_closed_at']??null],'filters'=>edu_course_dashboard_filter_options($conn,$actor),'summary'=>['evaluated'=>$evaluated,'high'=>$summary['Alto'],'medium'=>$summary['Medio'],'low'=>$summary['Bajo'],'attention_courses'=>$summary['attention_courses'],'high_courses'=>$summary['high_courses'],'matched'=>count($items)],'students'=>array_slice($items,0,120),'course_patterns'=>$patterns,'interventions'=>$interventions,'migration_ready'=>$courseInterventionReady];
}
function edu_course_dashboard_student_detail(mysqli $conn,array $actor,int $studentId,?int $bimester=null): array {
    $p=edu_course_risk_student_prediction($conn,$actor,$studentId,$bimester,false);if(empty($p['available']))return['ok'=>false,'message'=>'No hay datos/modelo predictivo suficientes para este estudiante.','reason'=>$p['reason']??null];$schoolId=(int)($actor['school_id']??0);foreach($p['courses'] as $i=>$course){$history=edu_course_risk_history_linked($conn,$studentId,$schoolId,(string)$course['course_name']);$p['courses'][$i]['history_across_years']=$history;$p['courses'][$i]['history_summary']=edu_course_risk_history_direction($history);}return['ok'=>true,'prediction'=>$p];
}
